### ISSUE TITLE
[BUG] Graphical glitch + exception when using programs menu

### ISSUE THREAD

**Issue by 1nikolas** [bottlesdevs/Bottles#1091]
**Describe the bug**
When trying to refresh applications menu, an exception is thrown and the bottle becomes inaccessible (even after restarting the app)

**Installation**
 - Method: aur (yay)
 - Version: 2022.2.14-trento

**To Reproduce**
1. Create a bottle
2. Run an executable
3. Try to refresh applications
4. Bottle becomes inaccessible 

**Expected behavior**
Can enter bottle and have the app appear on applications

**Screenshots**
Let the video explain instead:
https://streamable.com/z35m3j

**Desktop (please complete the following information):**
 - OS: ArchLinux
 - Version: Latest
 - Display server: Xorg

**Additional context**

Log:
```
(19:32:28) INFO Bottles Started! 
(19:32:32) WARNING Cannot find states.yml file for bottle: [test] 
Traceback (most recent call last):
  File "/usr/share/bottles/bottles/views/list.py", line 149, in show_details
    self.window.show_details_view(config=self.config)
  File "/usr/share/bottles/bottles/window.py", line 291, in show_details_view
    self.page_details.set_config(config)
  File "/usr/share/bottles/bottles/views/details.py", line 176, in set_config
    self.view_programs.update(config=config)
  File "/usr/share/bottles/bottles/views/bottle_programs.py", line 120, in update
    programs = self.manager.get_programs(self.config)
  File "/usr/share/bottles/bottles/backend/managers/manager.py", line 633, in get_programs
    executable_path = self.__getLnkData(program)
  File "/usr/share/bottles/bottles/backend/managers/manager.py", line 542, in __getLnkData
    return content[-1].decode(decode)
TypeError: decode() argument 'encoding' must be str, not None
```

**Comment by mirkobrombin** [comment]
Thanks for reporting
