### ISSUE TITLE
[BUG] Graphical glitch + exception when using programs menu #2

### ISSUE THREAD

**Issue by 1nikolas** [bottlesdevs/Bottles#1093]
Same bug as #1091 but different exception. Using upstream from aur

```
Traceback (most recent call last):
  File "/usr/share/bottles/bottles/views/list.py", line 149, in show_details
    self.window.show_details_view(config=self.config)
  File "/usr/share/bottles/bottles/window.py", line 293, in show_details_view
    self.page_details.set_config(config)
  File "/usr/share/bottles/bottles/views/details.py", line 177, in set_config
    self.view_programs.update(config=config)
  File "/usr/share/bottles/bottles/views/bottle_programs.py", line 120, in update
    programs = self.manager.get_programs(self.config)
  File "/usr/share/bottles/bottles/backend/managers/manager.py", line 660, in get_programs
    executable_path = self.__getLnkData(program)
  File "/usr/share/bottles/bottles/backend/managers/manager.py", line 564, in __getLnkData
    return content[-1].decode(decode)
UnicodeDecodeError: 'utf-16-le' codec can't decode byte 0x65 in position 30: truncated data

```

**Comment by 1nikolas** [comment]
Setting the correct system locale fixes the issue. Thank you!

**Comment by mirkobrombin** [comment]
You are welcome!
