### ISSUE TITLE
[BUG] Got "ValueError" when launching bottles

### ISSUE THREAD

**Issue by jyi2ya** [bottlesdevs/Bottles#1114]
**Describe the bug**
Bottles crashes and print lots of error message.

```plain
% [1] jyi@Syameimaru-Aya ~
0 bottles 
Traceback (most recent call last):
  File "/usr/bin/bottles", line 56, in <module>
    from bottles import main
  File "/usr/share/bottles/bottles/main.py", line 32, in <module>
    from bottles.window import MainWindow
  File "/usr/share/bottles/bottles/window.py", line 35, in <module>
    from bottles.views.details import DetailsView
  File "/usr/share/bottles/bottles/views/details.py", line 25, in <module>
    from bottles.views.bottle_details import BottleView
  File "/usr/share/bottles/bottles/views/bottle_details.py", line 36, in <module>
    from bottles.dialogs.generic import MessageDialog
  File "/usr/share/bottles/bottles/dialogs/generic.py", line 20, in <module>
    gi.require_version('GtkSource', '4')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available for version %s' %
ValueError: Namespace GtkSource not available for version 4
```

**Installation**
 - Method: Meson build
 - Version: 2022.2.28-trento-2

**To Reproduce**
1. Download latest code using `git`
2. Build a .deb package using `dh_auto_configure` and `dpkg-buildpackage`
3. Install the .deb package using `apt`
4. Run `bottles` in command line
5. See error

**Expected behavior**
The program starts and displays its UI.

**Desktop (please complete the following information):**
 - OS: Debian
 - Version: Debian GNU/Linux bookworm/sid
 - Display server: Xorg

**Additional context**
I guess that the dependency `gir1.2-gtksource-4` is missing. Bottles runs well after installing the package.

**Comment by mirkobrombin** [comment]
Should not be a bug, just a missing dependency (right?)

**Comment by jyi2ya** [comment]
> Should not be a bug, just a missing dependency (right?)

Yes.
