### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by jekanev** [bottlesdevs/Bottles#1127]
**Describe the bug**
run without network lead to error 
flatpak run --unshare=network com.usebottles.bottles

**Installation**
 - Method: [flatpak]
 - Version [2022.2.28-trento-3]

**To Reproduce**

 flatpak run --unshare=network com.usebottles.bottles
Gtk-Message: 22:26:24.498: Failed to load module "canberra-gtk-module"
(22:26:25) ERROR Could not get index for components repository 
(22:26:25) ERROR Could not get index for dependencies repository 
(22:26:25) ERROR Could not get index for installers repository 
Traceback (most recent call last):
  File "/app/share/bottles/bottles/backend/repos/repo.py", line 36, in __get_catalog
    with urllib.request.urlopen(index) as url:
  File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 501, in open
    req = Request(fullurl, data)
  File "/usr/lib/python3.9/urllib/request.py", line 320, in __init__
    self.full_url = url
  File "/usr/lib/python3.9/urllib/request.py", line 346, in full_url
    self._parse()
  File "/usr/lib/python3.9/urllib/request.py", line 375, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/share/bottles/bottles/main.py", line 166, in do_command_line
    self.do_activate()
  File "/app/share/bottles/bottles/main.py", line 231, in do_activate
    win = MainWindow(
  File "/app/share/bottles/bottles/window.py", line 86, in __init__
    self.manager = Manager(self)
  File "/app/share/bottles/bottles/backend/managers/manager.py", line 104, in __init__
    self.component_manager = ComponentManager(self)
  File "/app/share/bottles/bottles/backend/managers/component.py", line 44, in __init__
    self.__repo = manager.repository_manager.get_repo("components")
  File "/app/share/bottles/bottles/backend/managers/repository.py", line 61, in get_repo
    return repo["cls"](repo["url"], repo["index"])
  File "/app/share/bottles/bottles/backend/repos/repo.py", line 32, in __init__
    self.catalog = self.__get_catalog(index)
  File "/app/share/bottles/bottles/backend/repos/repo.py", line 38, in __get_catalog
    except (urllib.error.HTTPError, urllib.error.URLError, YAMLError):
NameError: name 'YAMLError' is not defined

**Expected behavior**
i do not my see no bottles list

**Comment by mirkobrombin** [comment]
I think you are preventing Bottles to reach its repositories with such argument. So it will still fail

**Comment by jekanev** [comment]
The previous version ran without problems, is it possible to disable checking repositories?, in addition, if the network is down and I run it without an argument, the same error is present.

**Comment by mirkobrombin** [comment]
I’ll push an hotfix later

**Comment by jekanev** [comment]
ok ty.
