### ISSUE TITLE
[BUG] TypeError: bottles/backend/managers/notifications.py: argument of type 'int' is not iterable

### ISSUE THREAD

**Issue by STiAT** [bottlesdevs/Bottles#1165]
**Describe the bug**
Starting up bottles triggers an exception (and within that a exeption notification in KDE at least). The reason is some TypeError in notifications.py.

**Installation**
 - Method: FC35 packages
 - Version 2022.2.28-trento

**To Reproduce**
Just start bottles.

**Expected behavior**
Not to throw a TypeError

**Screenshots**
```
(20:12:45) INFO Performing Bottles checks... 
(20:12:45) INFO Dxvks found:
         - dxvk-1.9.4
 
(20:12:45) INFO Vkd3ds found:
         - vkd3d-proton-2.5
 
(20:12:45) INFO Nvapis found:
         - dxvk-nvapi-v0.5.2
 
(20:12:45) INFO Runners found:
         - sys-wine-7.2
         - caffe-7.2
 
Traceback (most recent call last):
  File "/usr/share/bottles/bottles/main.py", line 167, in do_command_line
    self.do_activate()
  File "/usr/share/bottles/bottles/main.py", line 232, in do_activate
    win = MainWindow(
  File "/usr/share/bottles/bottles/window.py", line 165, in __init__
    self.__on_start()
  File "/usr/share/bottles/bottles/window.py", line 235, in __on_start
    self.check_notifications()
  File "/usr/share/bottles/bottles/window.py", line 345, in check_notifications
    messages = NotificationsManager().messages
  File "/usr/share/bottles/bottles/backend/managers/notifications.py", line 37, in __init__
    self.__get_messages()
  File "/usr/share/bottles/bottles/backend/managers/notifications.py", line 58, in __get_messages
    if message.get("id") in self.data.list().get("notifications"):
TypeError: argument of type 'int' is not iterable

```

**Desktop (please complete the following information):**
 - OS: Fedora
 - Version 35
 - Display server: Xorg
- Desktop Environment: KDE

**Comment by STiAT** [comment]
Yep, thank you very much, can confirm this fixes the issue! That was indeed fast :-).

**Comment by mirkobrombin** [comment]
Thanks for reporting
