### ISSUE TITLE
[BUG] ERROR Could not get index for components, depedencies, and installers repository.

### ISSUE THREAD

**Issue by pegasusearl** [bottlesdevs/Bottles#1167]
**Describe the bug**
Does not run. GUI shown but it does nothing.

**Installation**
 - Method: AUR
 - Version The GUI does nothing so I cannot access About section, But it's version 2022.2.28-4 according to the package manager.

**To Reproduce**
1. Run bottles
2. It will took quite a while to load
3. Once it loads, it shows GUI. and it doesn't respond to anything except popup when you press option button. Even if you click Documentation, Forum, Health Check, it will do nothing.

**Expected behavior**
I don't know what I expected, I haven't used Bottle before.

**Video**
https://www.youtube.com/watch?v=4sQL73aMobE
```
$bottles                                                          ✔ 
(07:09:01) ERROR Could not get index for components repository 
(07:09:21) ERROR Could not get index for dependencies repository 
(07:09:41) ERROR Could not get index for installers repository 
Traceback (most recent call last):
  File "/usr/share/bottles/bottles/backend/repos/repo.py", line 36, in __get_catalog
    with urllib.request.urlopen(index) as url:
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 503, in open
    req = Request(fullurl, data)
  File "/usr/lib/python3.10/urllib/request.py", line 322, in __init__
    self.full_url = url
  File "/usr/lib/python3.10/urllib/request.py", line 348, in full_url
    self._parse()
  File "/usr/lib/python3.10/urllib/request.py", line 377, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/bottles/bottles/main.py", line 166, in do_command_line
    self.do_activate()
  File "/usr/share/bottles/bottles/main.py", line 231, in do_activate
    win = MainWindow(
  File "/usr/share/bottles/bottles/window.py", line 86, in __init__
    self.manager = Manager(self)
  File "/usr/share/bottles/bottles/backend/managers/manager.py", line 104, in __init__
    self.component_manager = ComponentManager(self)
  File "/usr/share/bottles/bottles/backend/managers/component.py", line 44, in __init__
    self.__repo = manager.repository_manager.get_repo("components")
  File "/usr/share/bottles/bottles/backend/managers/repository.py", line 61, in get_repo
    return repo["cls"](repo["url"], repo["index"])
  File "/usr/share/bottles/bottles/backend/repos/repo.py", line 32, in __init__
    self.catalog = self.__get_catalog(index)
  File "/usr/share/bottles/bottles/backend/repos/repo.py", line 38, in __get_catalog
    except (urllib.error.HTTPError, urllib.error.URLError, YAMLError):
NameError: name 'YAMLError' is not defined. Did you mean: 'NameError'?
```

**Desktop (please complete the following information):**
 - OS: Manjaro Gnome
 - Version : I don't know
 - Display server: Xorg
**Additional context**
First time installed bottle. 

```
neofetch --backend off                                           ✔ 
friska@Everlight-R2 
------------------- 
OS: Manjaro Linux x86_64 
Kernel: 5.15.25-1-MANJARO 
Uptime: 26 mins 
Packages: 1635 (pacman), 2 (flatpak), 8 (snap) 
Shell: zsh 5.8.1 
Resolution: 1920x1080, 1920x1080 
DE: GNOME 41.4 
WM: Mutter 
WM Theme: Matcha-light-sea 
Theme: Vertex-Dark [GTK2/3] 
Icons: Fluent-green-dark [GTK2/3] 
Terminal: gnome-terminal 
CPU: AMD Ryzen 5 3500 (6) @ 3.600GHz 
GPU: NVIDIA GeForce GTX 1650 
Memory: 5139MiB / 15921MiB 
```

**Comment by mirkobrombin** [comment]
The AUR package is missing a release which fix this.

**Comment by pegasusearl** [comment]
ah I'm sorry I should have tried git version before posting.
Git version seems to ran just fine. `bottles-git` from aur.

**Comment by mirkobrombin** [comment]
We still need to update the bottles package to latest one :D

**Comment by Ryhon0** [comment]
I'm having this exact same issue with the latest versions on the AUR (2022.3.28-1 and 2022.2.28.trento.4.r62.gfd622b29-2), does not happen on the flathub release
