### ISSUE TITLE
[Flathub beta] [Bug]: TypeError: object of type 'bool' has no len()

### ISSUE THREAD

**Issue by thopiekar** [bottlesdevs/Bottles#1235]
Just downloaded the latest beta package. Getting this here:
```
thopiekar@home-linux:~$ flatpak run com.usebottles.bottles 
(19:42:08) INFO Performing Bottles checks... 
(19:42:08) INFO Runners found:
         - sys-wine-7.0
 
Traceback (most recent call last):
  File "/app/share/bottles/bottles/main.py", line 166, in do_command_line
    self.do_activate()
  File "/app/share/bottles/bottles/main.py", line 231, in do_activate
    win = MainWindow(
  File "/app/share/bottles/bottles/window.py", line 115, in __init__
    page_details = DetailsView(self)
  File "/app/share/bottles/bottles/views/details.py", line 57, in __init__
    self.view_preferences = PreferencesView(window, config)
  File "/app/share/bottles/bottles/views/bottle_preferences.py", line 153, in __init__
    if RuntimeManager.get_runtimes("steam"):
  File "/app/share/bottles/bottles/backend/managers/runtime.py", line 33, in get_runtimes
    if _filter not in runtimes or len(runtimes[_filter]) == 0:
TypeError: object of type 'bool' has no len()

```

**Comment by thopiekar** [comment]
Oh, well doesn't seem to be the same as master at the moment.

Why is *develop* so strongly diverged from *master*?

**Comment by mirkobrombin** [comment]
Develop branch is actually not maintained. I'm almost alone with development and I feel more comfortable using the main one

**Comment by thopiekar** [comment]
Hmm.. If the content in develop is pointless, then remove or rename the branch maybe. Something like *old-develop*...
And from personal experience work on features per branch and merge only into develop what's finished.
Yes, it will slow down development, but you won't get issue reports from people with a mixture of different bugs.

I mean, it's just a personal recommendation of course :wink:
