### ISSUE TITLE
The build is successful, but it cannot be started. How to solve it?

### ISSUE THREAD

**Issue by Liu-Peiming** [bottlesdevs/Bottles#1269]
**I build successfully with the source code, but bottles did not appear in the application panel. The following information appears when I run the "bottles" command in the terminal:**
`Traceback (most recent call last):
  File "/usr/local/bin/bottles", line 42, in <module>
    from bottles import main
  File "/usr/local/share/bottles/bottles/main.py", line 33, in <module>
    from bottles.window import MainWindow
  File "/usr/local/share/bottles/bottles/window.py", line 26, in <module>
    from bottles.widgets.message import MessageEntry
  File "/usr/local/share/bottles/bottles/widgets/message.py", line 22, in <module>
    from bottles.backend.managers.notifications import NotificationsManager  # pyright: reportMissingImports=false
  File "/usr/local/share/bottles/bottles/backend/managers/notifications.py", line 18, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'`

How to solve it?

**Comment by mirkobrombin** [comment]
```
ModuleNotFoundError: No module named 'yaml'
```

you have to install the yaml python package, refer to your distro. In Ubuntu it's python3-yaml, Arch Linux is python-yaml.
