### ISSUE TITLE
[Bug]: Hanging on "Loading..." with library enabled

### ISSUE THREAD

**Issue by ghtesting2020** [bottlesdevs/Bottles#1311]
### Describe the bug

Updated to newest version and enabled library. I added a game to the library but the library screen was blank. When I close and open bottles again hoping it may show up there it will never load anymore. I see  this error when run via terminal. I do not know if related.

```
Traceback (most recent call last):
  File "/app/share/bottles/bottles/window.py", line 239, in set_manager
    self.page_library = LibraryView(self)
  File "/app/share/bottles/bottles/views/library.py", line 44, in __init__
    self.update()
  File "/app/share/bottles/bottles/views/library.py", line 56, in update
    entry = LibraryEntry(self.window, u, e)
  File "/app/share/bottles/bottles/widgets/library.py", line 50, in __init__
    self.program = self.__get_program()
  File "/app/share/bottles/bottles/widgets/library.py", line 80, in __get_program
    programs = self.manager.get_programs(self.config)
  File "/app/share/bottles/bottles/backend/managers/manager.py", line 633, in get_programs
    bottle = ManagerUtils.get_bottle_path(config)
  File "/app/share/bottles/bottles/backend/utils/manager.py", line 80, in get_bottle_path
    if config.get("IsLayer"):
AttributeError: 'NoneType' object has no attribute 'get'
```

### To Reproduce

1) update  bottles to 2022 04 14
2) launch bottles offline
3) enable library experimental feature
4) add a game to library
5) go to library view and do not see game
6) close bottles and open again
it never loads

### Package

Flatpak from Flathub

### Distribution

arch

### Health Check

```shell
No issues before update
```

**Comment by mirkobrombin** [comment]
The library is hardly under development. To make it works again, delete the library.yml file

**Comment by ghtesting2020** [comment]
This still seems to be an issue. When library is enabled and I added a game, I cannot launch Bottles the next time. I have to kill it, delete the library.yml file and then disable library next launch.
