### ISSUE TITLE
[Bug]: bottles-cli -- The resource at “/com/usebottles/bottles/about.ui” does not exist (0)

### ISSUE THREAD

**Issue by kmoad** [bottlesdevs/Bottles#1322]
### Describe the bug

Exception when using `bottles-cli`

```
[kyle@discovery ~]$ flatpak run --command=bottles-cli com.usebottles.bottles --help
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/gi/_gtktemplate.py", line 226, in validate_resource_path
    Gio.resources_get_info(path, Gio.ResourceLookupFlags.NONE)
gi.repository.GLib.GError: g-resource-error-quark: The resource at “/com/usebottles/bottles/about.ui” does not exist (0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/bin/bottles-cli", line 45, in <module>
    from bottles.backend.managers.manager import Manager
  File "/app/share/bottles/bottles/backend/managers/manager.py", line 45, in <module>
    from bottles.backend.managers.installer import InstallerManager
  File "/app/share/bottles/bottles/backend/managers/installer.py", line 32, in <module>
    from bottles.dialogs.generic import MessageDialog
  File "/app/share/bottles/bottles/dialogs/generic.py", line 288, in <module>
    class AboutDialog(Gtk.AboutDialog):
  File "/usr/lib/python3.9/site-packages/gi/_gtktemplate.py", line 293, in __call__
    validate_resource_path(self.resource_path)
  File "/usr/lib/python3.9/site-packages/gi/_gtktemplate.py", line 231, in validate_resource_path
    Gio.resources_lookup_data(path, Gio.ResourceLookupFlags.NONE)
gi.repository.GLib.GError: g-resource-error-quark: The resource at “/com/usebottles/bottles/about.ui” does not exist (0)
```

Same exception also occurs if I `flatpak run --command=sh com.usebottles.bottles` then run `bottles-cli` within the container.

Here's info about the bottles flatpak I'm using. It's version `2022.4.14-trento`
```
[kyle@discovery ~]$ flatpak info com.usebottles.bottles

Bottles - Run Windows software

          ID: com.usebottles.bottles
         Ref: app/com.usebottles.bottles/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 2022.4.14-trento
     License: GPL-3.0-or-later
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 446.3 MB
     Runtime: org.gnome.Platform/x86_64/42
         Sdk: org.gnome.Sdk/x86_64/42

      Commit: 085f5cd644bf0248e4ec20e7ecd546a6d62d0db988ef7448efcf4ff19948d9a4
      Parent: 0c1daae4a95f9641a594aa1a0ee842f3bddec109ad1ce0a00109bb7154180273
     Subject: add OBSVkCapture to PATH (203ab207)
        Date: 2022-04-14 17:22:52 +0000
```

### To Reproduce

Run
```
flatpak run --command=bottles-cli com.usebottles.bottles --help
```

### Package

Flatpak from Flathub

### Distribution

Fedora 35

### Health Check

```shell
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        nvidia: &amp;id002
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
        intel: &amp;id001
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json
    prime:
        integrated: *id001
        discrete: *id002
Kernel:
    Type: Linux
    Version: 5.16.18-200.fc35.x86_64
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

**Comment by mirkobrombin** [comment]
Thanks for reporting

**Comment by kmoad** [comment]
Thanks for the quick fix!
