### ISSUE TITLE
[Bug]: "FileNotFoundError: [Errno 2] No such file or directory: '/home/valmar/.local/share/bottles/data.yml'"

### ISSUE THREAD

**Issue by Valmar33** [bottlesdevs/Bottles#1358]
### Describe the bug

Git master seems broken, because bottles seems unable to generate or find "data.yml" or "journal.yml"

Terminal output:

```
(00:53:24) ERROR Data file not found. Creating new one.
Traceback (most recent call last):
  File "/usr/share/bottles/bottles/backend/managers/data.py", line 45, in __get_data
    with open(self.__p_data, 'r') as s:
FileNotFoundError: [Errno 2] No such file or directory: '/home/valmar/.local/share/bottles/data.yml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/bottles", line 42, in <module>
    from bottles import main
  File "/usr/share/bottles/bottles/main.py", line 33, in <module>
    from bottles.window import MainWindow
  File "/usr/share/bottles/bottles/window.py", line 26, in <module>
    from bottles.widgets.message import MessageEntry
  File "/usr/share/bottles/bottles/widgets/message.py", line 22, in <module>
    from bottles.backend.managers.notifications import NotificationsManager  # pyright: reportMissingImports=false
  File "/usr/share/bottles/bottles/backend/managers/notifications.py", line 24, in <module>
    from bottles.backend.globals import API
  File "/usr/share/bottles/bottles/backend/globals.py", line 43, in <module>
    class Paths:
  File "/usr/share/bottles/bottles/backend/globals.py", line 67, in Paths
    data = DataManager()
  File "/usr/share/bottles/bottles/backend/managers/data.py", line 41, in __init__
    self.__get_data()
  File "/usr/share/bottles/bottles/backend/managers/data.py", line 48, in __get_data
    logging.error('Data file not found. Creating new one.', )
  File "/usr/share/bottles/bottles/backend/logger.py", line 81, in error
    JournalManager.write(JournalSeverity.ERROR, message)
  File "/usr/share/bottles/bottles/backend/managers/journal.py", line 160, in write
    journal = JournalManager.__get_journal()
  File "/usr/share/bottles/bottles/backend/managers/journal.py", line 50, in __get_journal
    with open(JournalManager.path, "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/valmar/.local/share/bottles/journal.yml'
```

### To Reproduce

Install bottles-git from AUR. Run bottles from terminal.

### Package

AUR ("bottles" package)

### Distribution

Arch Linux

### Health Check

```shell
Can't run the program, so can't get this info, sadly.
```

### Display Protocol

Wayland

### Display Backend used by Bottles

I don't know

**Comment by Valmar33** [comment]
Cheers! :)
