### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by gnarlin** [bottlesdevs/Bottles#1361]
### Describe the bug

Running the beta flatpak version on Ubuntu 22.04 fails with error messages.

### To Reproduce

install Bottles via beta flatpak

### Package

Flatpak from Flathub

### Distribution

Ubuntu 22.04

### Health Check

```shell
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.13.0-40-generic
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

### Additional context

(16:00:30) ERROR Data file not found. Creating new one. 
Traceback (most recent call last):
  File "/app/share/bottles/bottles/backend/managers/data.py", line 45, in __get_data
    with open(self.__p_data, 'r') as s:
FileNotFoundError: [Errno 2] No such file or directory: '/home/kd/.var/app/com.usebottles.bottles/data/bottles/data.yml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/bin/bottles", line 42, in <module>
    from bottles import main
  File "/app/share/bottles/bottles/main.py", line 33, in <module>
    from bottles.window import MainWindow
  File "/app/share/bottles/bottles/window.py", line 26, in <module>
    from bottles.widgets.message import MessageEntry
  File "/app/share/bottles/bottles/widgets/message.py", line 22, in <module>
    from bottles.backend.managers.notifications import NotificationsManager  # pyright: reportMissingImports=false
  File "/app/share/bottles/bottles/backend/managers/notifications.py", line 24, in <module>
    from bottles.backend.globals import API
  File "/app/share/bottles/bottles/backend/globals.py", line 43, in <module>
    class Paths:
  File "/app/share/bottles/bottles/backend/globals.py", line 67, in Paths
    data = DataManager()
  File "/app/share/bottles/bottles/backend/managers/data.py", line 41, in __init__
    self.__get_data()
  File "/app/share/bottles/bottles/backend/managers/data.py", line 48, in __get_data
    logging.error('Data file not found. Creating new one.', )
  File "/app/share/bottles/bottles/backend/logger.py", line 81, in error
    JournalManager.write(JournalSeverity.ERROR, message)
  File "/app/share/bottles/bottles/backend/managers/journal.py", line 160, in write
    journal = JournalManager.__get_journal()
  File "/app/share/bottles/bottles/backend/managers/journal.py", line 50, in __get_journal
    with open(JournalManager.path, "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/kd/.var/app/com.usebottles.bottles/data/bottles/journal.yml'

----------------------------------
I ran: mkdir -p /home/kd/.var/app/com.usebottles.bottles/data/bottles/
and then bottles started normally.

**Comment by mirkobrombin** [comment]
Already fixed, I'll release it on beta soon
