### ISSUE TITLE
[Bug]: bad character range e-b at position 46

### ISSUE THREAD

**Issue by SeanRamey** [bottlesdevs/Bottles#1484]
### Describe the bug

Installed the GOG backup installer version of Close Combat: Last Stand Arnhem, played for a bit, then installed the GOG backup installer version of Close Combat: Gateway to Caen. Bottle couldn't find new programs, so I attempted to manually add the "CCE.EXE" from Close Combat: Gateway to Caen. It seemed to do nothing, but after a bit the other programs were removed from the list on the "Details & Utilites" page. I closed and restarted bottles, and now the bottle that I was using is not responding when clicking on it to open.

### To Reproduce

1. Install GOG backup installer version of Close Combat: Last Stand Arnhem
2. Play for a bit
3. Install GOG backup installer version of Close Combat: Gateway to Caen
4. Attempt to add "CCE.EXE" from Close Combat: Gateway to Caen
5. Close bottles and reopen

### Package

AUR ("bottles" package)

### Distribution

EndeavorOS

### Health Check

```shell
Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/share/vulkan/icd.d/nvidia_icd.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.17.6-arch1-1
Distro:
    Name: EndeavourOS
    Version: Unknown
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.35'
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

### Additional context

I say "same name of executable" because that's my best guess as to what the issue is. Both games use "CCE.EXE" as the name of the main program.

**Comment by SeanRamey** [comment]
@mirkobrombin If needed, I can probably send the whole bottle to you somehow.

**Comment by mirkobrombin** [comment]
No it's not related, Bottles will handle the duplicates if you add the executable from the program list (unless you manually added it in bottle.yml, that breaks everything).

Try starting from terminal and check the output.

**Comment by SeanRamey** [comment]
This is what I get in the terminal when I click on the bottle that doesn't work.
```Traceback (most recent call last):
  File "/usr/share/bottles/bottles/views/list.py", line 154, in show_details
    self.window.show_details_view(config=self.config)
  File "/usr/share/bottles/bottles/window.py", line 326, in show_details_view
    self.page_details.set_config(config)
  File "/usr/share/bottles/bottles/views/details.py", line 189, in set_config
    self.view_programs.update(config=config)
  File "/usr/share/bottles/bottles/views/bottle_programs.py", line 126, in update
    programs = self.manager.get_programs(self.config)
  File "/usr/share/bottles/bottles/backend/managers/manager.py", line 701, in get_programs
    icon = self.__find_program_icon(executable_name)
  File "/usr/share/bottles/bottles/backend/managers/manager.py", line 510, in __find_program_icon
    if fnmatch.fnmatch(name.lower(), pattern.lower()):
  File "/usr/lib/python3.10/fnmatch.py", line 42, in fnmatch
    return fnmatchcase(name, pat)
  File "/usr/lib/python3.10/fnmatch.py", line 76, in fnmatchcase
    match = _compile_pattern(pat)
  File "/usr/lib/python3.10/fnmatch.py", line 52, in _compile_pattern
    return re.compile(res).match
  File "/usr/lib/python3.10/re.py", line 251, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.10/re.py", line 303, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.10/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.10/sre_parse.py", line 950, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.10/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/lib/python3.10/sre_parse.py", line 836, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
  File "/usr/lib/python3.10/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/lib/python3.10/sre_parse.py", line 754, in _parse
    p = _parse_sub(source, state, verbose, nested + 1)
  File "/usr/lib/python3.10/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/lib/python3.10/sre_parse.py", line 836, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
  File "/usr/lib/python3.10/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/lib/python3.10/sre_parse.py", line 598, in _parse
    raise source.error(msg, len(this) + 1 + len(that))
re.error: bad character range e-b at position 46```

**Comment by mirkobrombin** [comment]
Share your bottle.yml

**Comment by SeanRamey** [comment]
[bottle copy.yml.txt](https://github.com/bottlesdevs/Bottles/files/8729646/bottle.copy.yml.txt)
