### ISSUE TITLE
[Bug] (urgent): cannot open any bottle after 2022.5.28-trento update

### ISSUE THREAD

**Issue by ghtesting2020** [bottlesdevs/Bottles#1538]
### Describe the bug

After Bottles loads and you click any bottle none of them will open. error log:
```
Traceback (most recent call last):
  File "/app/share/bottles/bottles/views/list.py", line 159, in show_details
    self.window.show_details_view(config=config)
  File "/app/share/bottles/bottles/window.py", line 339, in show_details_view
    self.page_details.set_config(config)
  File "/app/share/bottles/bottles/views/details.py", line 184, in set_config
    self.view_preferences.set_config(config=config)
  File "/app/share/bottles/bottles/views/bottle_preferences.py", line 337, in set_config
    self.switch_steam_runtime.handler_block_by_func(self.__toggle_steam_runtime)
TypeError: nothing connected to <bound method PreferencesView.__toggle_steam_runtime of <bottle_preferences.PreferencesView object at 0x6352b60f5580 (DetailsPreferences at 0x5a3340d9060)>>
```

### To Reproduce

open bottles
click on any bottle

### Package

Flatpak from Flathub

### Distribution

Arch

### Health Check

```shell
no issues here.
```

**Comment by mirkobrombin** [comment]
Fixed by https://github.com/bottlesdevs/Bottles/releases/tag/2022.5.28-trento-1
