### ISSUE TITLE
[Bug]: Can't open actual "bottle" after starting Bottles

### ISSUE THREAD

**Issue by bikebaranek** [bottlesdevs/Bottles#1542]
### Describe the bug

After today's update and opening "Bottles" when I click actual "bottle" nothing happens. Bottle's preferences are working.

After running Bottles from terminal and reproducing it:

**`$ flatpak run com.usebottles.bottles`**
```Traceback (most recent call last):
  File "/app/share/bottles/bottles/views/list.py", line 159, in show_details
    self.window.show_details_view(config=config)
  File "/app/share/bottles/bottles/window.py", line 339, in show_details_view
    self.page_details.set_config(config)
  File "/app/share/bottles/bottles/views/details.py", line 184, in set_config
    self.view_preferences.set_config(config=config)
  File "/app/share/bottles/bottles/views/bottle_preferences.py", line 337, in set_config
    self.switch_steam_runtime.handler_block_by_func(self.__toggle_steam_runtime)
TypeError: nothing connected to <bound method PreferencesView.__toggle_steam_runtime of <bottle_preferences.PreferencesView object at 0x7f9231529e80 (DetailsPreferences at 0x55a4395bd0e0)>>```

**Bottles version:** 2022.5.28-trento (flatpak from Flathub)

### To Reproduce

1. Open Bottles
2. Click actual "bottle"
3. Nothing happens

### Package

Flatpak from Flathub

### Distribution

Kubuntu 22.04

### Health Check

```shell
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        intel:
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.17.0-11.1-liquorix-amd64
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 8230842368
    Free: 8230694912
RAM:
    MemTotal: 15.3GiB
    MemAvailable: 12.6GiB
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

**Comment by bikebaranek** [comment]
Ok, a few minutes after submitting this bug there was an update available to version **2022.5.28-trento-1** and **now it's fixed.** Thank you.
