### ISSUE TITLE
[Bug]: Can not open any bottle

### ISSUE THREAD

**Issue by VortexAcherontic** [bottlesdevs/Bottles#1563]
### Describe the bug

I opened up an old bottle with the latest version of bottles (build version 2022.5.28-trento-3 from source) and also created a new bottle with the latest version.

Both return the following stack trace:

```
Traceback (most recent call last):
  File "/usr/share/bottles/bottles/views/list.py", line 159, in show_details
    self.window.show_details_view(config=config)
  File "/usr/share/bottles/bottles/window.py", line 339, in show_details_view
    self.page_details.set_config(config)
  File "/usr/share/bottles/bottles/views/details.py", line 184, in set_config
    self.view_preferences.set_config(config=config)
  File "/usr/share/bottles/bottles/views/bottle_preferences.py", line 336, in set_config
    self.switch_runtime.handler_block_by_func(self.__toggle_runtime)
TypeError: nothing connected to <bound method PreferencesView.__toggle_runtime of <bottle_preferences.PreferencesView object at 0x7f6d0a4f82c0 (DetailsPreferences at 0x55b9a2753710)>>
```

### To Reproduce

1. Build bottles from source
2. run bottles
3. open up an old or newly created bottle

### Package

From source

### Distribution

openSUSE Tumbleweed

### Health Check

```shell
Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        nvidia: &amp;id002
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /etc/vulkan/icd.d/nvidia_icd.json
        intel: &amp;id001
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/share/vulkan/icd.d/intel_icd.x86_64.json:/usr/share/vulkan/icd.d/intel_icd.i686.json
    prime:
        integrated: *id001
        discrete: *id002
Kernel:
    Type: Linux
    Version: 5.17.9-1-default
Distro:
    Name: n/a
    Version: opensuse
Disk:
    Total: 991494746112
    Free: 390584340480
RAM:
    MemTotal: 7.7GiB
    MemAvailable: 4.2GiB
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.35'
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

### Additional context

Was about to update the latest version for the openSUSE repos and noticed this while testing.
Maybe it is just me missing something, dunno ^^"

**Comment by mirkobrombin** [comment]
In a few days we will release a total makeover, I ask you to try that release. It should arrive on flathub beta within 24 hours
