### ISSUE TITLE
Can't start bootles.

### ISSUE THREAD

**Issue by TomJuri** [bottlesdevs/Bottles#1689]
When I am trying to run bottles using the .desktop file nothing happens, but when I type bottles in my Terminal Emulator I get this error:

Traceback (most recent call last):
  File "/usr/bin/bottles", line 42, in <module>
    from bottles import main
  File "/usr/share/bottles/bottles/main.py", line 35, in <module>
    from bottles.window import MainWindow
  File "/usr/share/bottles/bottles/window.py", line 36, in <module>
    from bottles.views.details import DetailsView
  File "/usr/share/bottles/bottles/views/details.py", line 35, in <module>
    from bottles.views.bottle_preferences import PreferencesView
  File "/usr/share/bottles/bottles/views/bottle_preferences.py", line 32, in <module>
    from bottles.dialogs.envvars import EnvVarsDialog
  File "/usr/share/bottles/bottles/dialogs/envvars.py", line 25, in <module>
    class EnvVarEntry(Adw.EntryRow):
  File "/usr/lib/python3.9/site-packages/gi/module.py", line 123, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Adw' object has no attribute 'EntryRow'

**Comment by jannuary** [comment]
Sounds like a dependency issue. What packaging format?

**Comment by jannuary** [comment]
> Well, I know it's not officially supported, but I am using the [spikyatlinux gentoo portage overlay](https://github.com/gentoo-mirror/spikyatlinux/tree/master/app-emulation/bottles).

"Use all of them at your own risk. I´ve tested all on my local system, if you find some errors or outdated ebuilds let me know ;-)"
