### ISSUE TITLE
[Bug]: can't remove manually added programs from list

### ISSUE THREAD

**Issue by fkrull** [bottlesdevs/Bottles#1761]
### Describe the bug

Manually added programs can't be removed from the Programs list. Selecting "Remove from list" does nothing.

### To Reproduce

1. Create a new bottle
2. Add a custom program to the Programs list (e.g. explorer.exe in the bottle's windows directory)
3. Select "Remove from list" on the entry

### Package

Flatpak from Flathub

### Distribution

Fedora 36

### Health Check

```shell
Version: 2022.6.28-brescia
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: true
Graphics:
    vendors:
        nvidia: &amp;id002
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
        intel: &amp;id001
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json
    prime:
        integrated: *id001
        discrete: *id002
Kernel:
    Type: Linux
    Version: 5.18.9-200.fc36.x86_64
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 16705499136
    Free: 16705339392
RAM:
    MemTotal: 31.1GiB
    MemAvailable: 22.5GiB
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null
```

### Display Protocol

Wayland

### Display Backend used by Bottles

Wayland

### Additional context

Error message:
```
20:03:02 (INFO) Setting Key None=None for bottle test… 
Traceback (most recent call last):
  File "/app/share/bottles/bottles/widgets/program.py", line 266, in remove_program
    self.config = self.manager.update_config(
  File "/app/share/bottles/bottles/backend/managers/manager.py", line 847, in update_config
    del config[scope][key]
KeyError: None
```

**Comment by mirkobrombin** [comment]
Fixed some commits ago,will be distributed with 2022.7.14
