### ISSUE TITLE
[Bug]: After creating a bottle, application crashes-ish?

### ISSUE THREAD

**Issue by modelmat** [bottlesdevs/Bottles#1765]
### Describe the bug

After creating an Application bottle, GNOME reports that "Bottles has crashed", whilst the window stays up. Clicking on the bottle settings just reports this error:

```
 
Traceback (most recent call last):
  File "/usr/share/bottles/bottles/views/list.py", line 159, in show_details
    self.window.show_details_view(config=config)
  File "/usr/share/bottles/bottles/window.py", line 339, in show_details_view
    self.page_details.set_config(config)
  File "/usr/share/bottles/bottles/views/details.py", line 184, in set_config
    self.view_preferences.set_config(config=config)
  File "/usr/share/bottles/bottles/views/bottle_preferences.py", line 336, in set_config
    self.switch_runtime.handler_block_by_func(self.__toggle_runtime)
TypeError: nothing connected to <bound method PreferencesView.__toggle_runtime of <bottle_preferences.PreferencesView object at 0x7fb4dbf5acc0 (DetailsPreferences at 0x55c9cc341880)>>
```

Restarting the application fixes it.

### To Reproduce

1. Set up an Application Bottle.
2. Click ok on the complete screen.
3. Attempt to do anything aside from go into the hamburger menu.

### Package

Other, unofficial package

### Distribution

Fedora 36 Workstation

### Health Check

```shell
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/share/vulkan/icd.d/radeon_icd.i686.json:/usr/share/vulkan/icd.d/radeon_icd.x86_64.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.18.9-200.fc36.x86_64
Distro:
    Name: Fedora Linux
    Version: '36'
Disk:
    Total: 208403480576
    Free: 97019854848
RAM:
    MemTotal: 14.4GiB
    MemAvailable: 5.2GiB
Tools:
    cabextract: true
    p7zip: false # dnf info p7zip shows that it is installed, so not sure what's up with that
    patool: false
    glibc_min: '2.35'
Bottles_envs: null
```

### Display Protocol

Wayland

### Display Backend used by Bottles

Wayland

**Comment by mirkobrombin** [comment]
Fixed in 2022.6.28
