### ISSUE TITLE
ModuleNotFoundError: No module named 'steamgrid'

### ISSUE THREAD

**Issue by ghost573** [bottlesdevs/Bottles#1845]
Sorry, is this a new dependency or a bug?
Normally new dependencies will give me an error if it's not installed.

```
Traceback (most recent call last):
  File "/usr/bin/bottles", line 43, in <module>
    from bottles import main
  File "/usr/share/bottles/bottles/main.py", line 36, in <module>
    from bottles.window import MainWindow
  File "/usr/share/bottles/bottles/window.py", line 36, in <module>
    from bottles.views.details import DetailsView
  File "/usr/share/bottles/bottles/views/details.py", line 41, in <module>
    from bottles.widgets.program import ProgramEntry
  File "/usr/share/bottles/bottles/widgets/program.py", line 28, in <module>
    from bottles.backend.managers.library import LibraryManager
  File "/usr/share/bottles/bottles/backend/managers/library.py", line 24, in <module>
    from bottles.backend.managers.steamgriddb import SteamGridDBManager
  File "/usr/share/bottles/bottles/backend/managers/steamgriddb.py", line 21, in <module>
    from steamgrid import SteamGridDB
ModuleNotFoundError: No module named 'steamgrid'
```

**Comment by axtloss** [comment]
It's a new dependency, Mirko is working on steamgriddb support for the library mode, so you'll have to install that to use bottles

**Comment by ghost573** [comment]
Ah okay, not a problem.

**Comment by ghost573** [comment]
https://aur.archlinux.org/packages/steamgrid

This is the correct package right?
