### ISSUE TITLE
[Bug]: name 'http' is not defined

### ISSUE THREAD

**Issue by ghtesting2020** [bottlesdevs/Bottles#1856]
### Describe the bug

2022.7.28-brescia

```
name 'http' is not defined  File "/app/share/bottles/bottles/utils/threading.py", line 63, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/window.py", line 191, in get_manager
    mng = Manager(window=window, repo_fn_update=repo_fn_update)

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 112, in __init__
    self.repository_manager = RepositoryManager(repo_fn_update)

  File "/app/share/bottles/bottles/backend/managers/repository.py", line 54, in __init__
    self.__get_index()

  File "/app/share/bottles/bottles/backend/managers/repository.py", line 103, in __get_index
    except (urllib.error.HTTPError, urllib.error.URLError, http.client.RemoteDisconnected):
```

```
flatpak run com.usebottles.bottles
09:32:20 (WARNING) Connection status: offline … 
09:32:20 (WARNING) Connection status: offline … 

(bottles:3): Gtk-CRITICAL **: 09:32:20.890: GtkBox 0x723fe5a8da0 reports a minimum height of 389, but minimum height for width of 1048576 is 390. Expect overlapping widgets.

(bottles:3): Gtk-CRITICAL **: 09:32:20.890: GtkBox 0x723fe5a8f20 reports a minimum height of 84, but minimum height for width of 1048576 is 85. Expect overlapping widgets.

(bottles:3): Gtk-CRITICAL **: 09:32:20.920: GtkBox 0x723fe6771b0 reports a minimum height of 48, but minimum height for width of 1048576 is 49. Expect overlapping widgets.
09:32:20 (INFO) Bottles Started! 
09:32:20 (ERROR) Error while running async job: <function MainWindow.__on_start.<locals>.get_manager at 0x66930031c430>
        Exception: name 'http' is not defined
 

(bottles:3): Gtk-CRITICAL **: 09:32:20.941: GtkBox 0x723fe5a8da0 reports a minimum height of 389, but minimum height for width of 1048576 is 390. Expect overlapping widgets.

(bottles:3): Gtk-CRITICAL **: 09:32:20.942: GtkBox 0x723fe5a8f20 reports a minimum height of 84, but minimum height for width of 1048576 is 85. Expect overlapping widgets.

(bottles:3): Gtk-CRITICAL **: 09:32:20.942: GtkBox 0x723fe6771b0 reports a minimum height of 48, but minimum height for width of 1048576 is 49. Expect overlapping widgets.
  File "/app/share/bottles/bottles/utils/threading.py", line 63, in __target
    result = self.task_func(*args, **kwargs)
  File "/app/share/bottles/bottles/window.py", line 191, in get_manager
    mng = Manager(window=window, repo_fn_update=repo_fn_update)
  File "/app/share/bottles/bottles/backend/managers/manager.py", line 112, in __init__
    self.repository_manager = RepositoryManager(repo_fn_update)
  File "/app/share/bottles/bottles/backend/managers/repository.py", line 54, in __init__
    self.__get_index()
  File "/app/share/bottles/bottles/backend/managers/repository.py", line 103, in __get_index
    except (urllib.error.HTTPError, urllib.error.URLError, http.client.RemoteDisconnected):
Traceback (most recent call last):
  File "/app/share/bottles/bottles/window.py", line 146, in set_manager
    tmp_runners = [x for x in self.manager.runners_available if not x.startswith('sys-')]
AttributeError: 'NoneType' object has no attribute 'runners_available'
```

### To Reproduce

Launch bottles

### Package

Flatpak from Flathub

### Distribution

Arch

### Health Check

```shell
N/A
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

**Comment by ghtesting2020** [comment]
@mirkobrombin are you able to hotfix this? Most of time i play where no internet connection and cannot use Bottles now :(
