### ISSUE TITLE
[Bug]: Bottles Stucks At Loading

### ISSUE THREAD

**Issue by Deissson** [bottlesdevs/Bottles#1993]
### Describe the bug

Bottles stucks at loading, after i added an app to library, and deleted app's bottle 

i cant provide Troubleshooting Logs, so i provided the only logs i can access using `flatpak run com.usebottles.bottles`

### To Reproduce

1. Create a Bottle
2. Add Application to Library
3. Delete Bottle

### Package

Flatpak from Flathub

### Distribution

Fedora 36 (Silverblue)

### Troubleshooting Logs

```shell
06:54:01 (INFO) Bottles Started! 
06:54:05 (INFO) Catalog components loaded 
06:54:05 (INFO) Catalog installers loaded 
06:54:06 (INFO) Catalog dependencies loaded 
06:54:06 (INFO) Performing Bottles checks… 
06:54:06 (INFO) Dxvks found:
	 - dxvk-1.10.3
 
06:54:06 (INFO) Vkd3ds found:
	 - vkd3d-proton-2.6-1-5b73139
 
06:54:06 (INFO) Nvapis found:
	 - dxvk-nvapi-v0.5.4
 
06:54:06 (INFO) Latencyflexs found:
	 - latencyflex-v0.1.0
 
06:54:06 (INFO) Runners found:
	 - sys-wine-7.0
	 - soda-7.0-3
 
06:54:08 (INFO) Library saved 
Traceback (most recent call last):
  File "/app/share/bottles/bottles/frontend/windows/main_window.py", line 158, in set_manager
    self.page_library = LibraryView(self)
  File "/app/share/bottles/bottles/frontend/views/library.py", line 43, in __init__
    self.update()
  File "/app/share/bottles/bottles/frontend/views/library.py", line 56, in update
    entry = LibraryEntry(self, u, e)
  File "/app/share/bottles/bottles/frontend/widgets/library.py", line 84, in __init__
    path = ThumbnailManager.get_path(self.config, entry['thumbnail'])
  File "/app/share/bottles/bottles/backend/managers/thumbnail.py", line 32, in get_path
    return ThumbnailManager.__load_grid(config, uri)
  File "/app/share/bottles/bottles/backend/managers/thumbnail.py", line 42, in __load_grid
    bottle_path = ManagerUtils.get_bottle_path(config)
  File "/app/share/bottles/bottles/backend/utils/manager.py", line 86, in get_bottle_path
    if config.get("Environment") == "Steam":
AttributeError: 'NoneType' object has no attribute 'get'
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

**Comment by Deissson** [comment]
![image](https://user-images.githubusercontent.com/86420878/187056733-9b386377-3e64-47ac-a706-6ca0de70638d.png)

here's an image of the only thing i see (loading doesnt go any further)
