### ISSUE TITLE
[Bug]: unable to launch programs in Steam Deck gaming mode, but can launch from script pointing to executable

### ISSUE THREAD

**Issue by alpha-tango-kilo** [bottlesdevs/Bottles#2020]
### Describe the bug

Programs installed into a bottle can't be found by program name when in the Steam Deck's gaming mode, per reproduction steps

I spent a fair while digging at this, and this is what I found:
- Bottles launched within gaming mode showed only manually added programs, not auto-detected ones
- Creating a script that called `flatpak run --command=bottles-cli com.usebottles.bottles run -b <bottle name> -e <path>` and adding it to Steam could launch the game
- Using the above script approach but with `-p <program name>` only worked with manually added programs

### To Reproduce

1. Create (gaming) bottle
2. Install game
3. Add game to Programs if not present
4. Add program to Steam (at this point the program will launch fine from Bottles, or from Steam while still in desktop mode)
5. Switch to gaming mode
6. Launch game
7. (either stays on Steam spinner or gives up and goes back to game info)

### Package

Flatpak from Flathub

### Distribution

Steam Deck

### Troubleshooting Logs

```shell
Version: 2022.8.28-brescia-2
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.13.0-valve21.1-1-neptune-02211-gc54cda5a36f3
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 7778668544
    Free: 7778525184
RAM:
    MemTotal: 14.5GiB
    MemAvailable: 11.4GiB
Bottles_envs: null

```

### Display Protocol

X11, Wayland

### Additional context

Flatseal non-default setttings:

![image](https://user-images.githubusercontent.com/12728900/188280440-465050fc-33d7-40fe-a750-8ee918fab314.png)

![image](https://user-images.githubusercontent.com/12728900/188280478-bcf4c4ac-e826-45c3-8b20-23b1765cab19.png)

**Comment by mirkobrombin** [comment]
Some useful logs? I don't have a steam deck to test (and no time for setting up a vm), idk how steam is launched but I assume you can launch it trough your terminal to catch some logs.

**Comment by alpha-tango-kilo** [comment]
See logs in below message. I'm afraid they're not the most informative. The only way I can get logs when launching games in gaming mode is by using a script I write myself, which is added as a non-Steam game. In this case, it's `flatpak run --command=bottles-cli com.usebottles.bottles run -b <bottle name> -p <program name> &>$HOME/bottles.log`. The script correctly launches the game if run from a terminal in desktop mode, which eliminates the possibility of user error.

The "ERROR: ld.so" stuff comes from Steam chucking around a whole load of environment variables when you launch a game through it. You also get these logs when successfully launching a game, so I think they're just noise.

**Comment by alpha-tango-kilo** [comment]
```
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
[80m21:49:19 [1m(INFO)[0m [36mForcing offline mode[0m [0m
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
Program Cult Of The Lamb not found
```

**Comment by codingismy11to7** [comment]
I'm getting the exact same thing. At one point I added an `export LD_PRELOAD=` line to my script before launching, in which case I only ended up with the two lines (Forcing offline mode & Program <x> not found).

Wondering if this is some kind of steam+flatpak issue, and not an issue with bottles (but if you install Chrome it uses flatpak and launches fine, so maybe that's not the case)

**Comment by herbzhao** [comment]
Can confirm, the game installed in bottles can run in bottles. After using add to steam button the game won't run either in game mode or desktop mode in steam. It even won't run with a desktop shortcut generated by bottles.

**Comment by alpha-tango-kilo** [comment]
> Can confirm, the game installed in bottles can run in bottles. After using add to steam button the game won't run either in game mode or desktop mode in steam. It even won't run with a desktop shortcut generated by bottles.

@herbzhao that's a different issue to this one then. I can run games from Bottles fine in desktop mode, and through Steam in desktop mode. You may want to grab some logs and file a separate issue

**Comment by herbzhao** [comment]
In the meantime, i have found this as a solution, as you stated, you can create a .sh file. and add this as a non-steam game. also works. 
```
#!/bin/bash
flatpak run --command=bottles-cli com.usebottles.bottles run -b {bottle_name} -p "{programme name}"
```

**Comment by herbzhao** [comment]
Boilr has successfully implemented the add to steam, for anyone who is still having this problem.

**Comment by alpha-tango-kilo** [comment]
Can confirm Boilr works fine on programs installed in a bottle that have been manually added manually to the programs list. This appears to be because Boilr uses the `flatpak run` command to launch programs too ([seen here](https://github.com/PhilipK/BoilR/blob/c933c84b0cffd0f5a2d9bbfe799c16e9ad1d841f/src/bottles/platform.rs#L25-L29), as opposed to the `xdg-open` command that Bottles adds to Steam

**Comment by apcamargo** [comment]
Also had this problem. I had to add the executable to Programs manually (because I just copied the folder from an external drive) and it didn't launch when I added it to Steam via Bottles. Using Boilr did fix the issue.

**Comment by theauditioner** [comment]
Hi all i am trying to launch a wii u game from gaming mode, it worked fine before now it keeps crashing annoyingly, is this forum the fix for it??

**Comment by mirkobrombin** [comment]
Please open a new issue in the programs repository.

The topic issue should be already fixed. Can someone confirm?

**Comment by apcamargo** [comment]
I have the same experience. My shortcuts only work when I use BoilR.

**Comment by pamohe** [comment]
> This is all too much it'd supposed to be a gaming unit for emulators but it doesn't work - should we just return it??

It really is a lot more complicated that I had anticipated. Such a buggy and difficult experience.

**Comment by Scvairy** [comment]
> flatpak run --command=bottles-cli com.usebottles.bottles run -b {bottle_name} -p "{programme name}"

For this command I have an error "TypeError: unsupported operand type(s) for +: NoneType and str"
I fixed this manually patching in bottles-cli line 574:
```
-_args = program.get("arguments", "") + " " + _args
+_args = (program.get("arguments", "") or "") + " " + _args
```

**Comment by 4903000** [comment]
Workaround: Place a single space as command arguments in the launch options of the program's shortcut. If the launch options dialog doesn't appear, try removing and re-adding the program.

For developers: This issue is not specific to the Steam Deck or SteamOS, my Fedora system is also affected. The above workaround works on different systems and different games. The issue also doesn't involve anything Steam related; just running games through the xdg-open URL interface exhibits the same behavior. 

The traceback printed when a game fails to launch is:
```
09:10:46 (INFO) Forcing offline mode 
Traceback (most recent call last):
  File "/app/bin/bottles-cli", line 652, in <module>
    cli = CLI()
          ^^^^^
  File "/app/bin/bottles-cli", line 150, in __init__
    self.__process_args()
  File "/app/bin/bottles-cli", line 199, in __process_args
    self.run_program()
  File "/app/bin/bottles-cli", line 574, in run_program
    _args = program.get("arguments", "") + " " + _args
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```
The traceback printed when the launch options dialog fails to open is:
```
Traceback (most recent call last):
  File "/app/share/bottles/bottles/frontend/widgets/program.py", line 134, in show_launch_options_view
    dialog = LaunchOptionsDialog(self, self.config, self.program)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/bottles/bottles/frontend/windows/launchoptions.py", line 82, in __init__
    self.entry_arguments.set_text(program.get("arguments", ""))
TypeError: Argument 1 does not allow None as a value
```
In both cases it seems like the string literal `""` isn't interpreted as a string when returned by get() as the default argument. If this is a recent change in Python, you may have a lot of errors like this in your software.

**Comment by koplo199** [comment]
@4903000 Both errors will be fixed by #3211. It was a regression caused by the latest big refactoring, not a recent change in Python, so there shouldn't be more errors like these fortunately

**Comment by DragonKumera** [comment]
This is the exact same issue I am having. Started after updating bottles from 51.9 to 51.10 then 51.9 as some reason there was an update?

**Comment by gregthwuen** [comment]
These problems still persist on the newest release 51.13. Using the `xdg-open` command, a window opens and wants me to choose one of my bottles, with no program launching after that:

```
Executable file path does not exist or is not accessible by the Flatpak: bottles:run/{bottle_name}/{program_name}
Not a common executable type, trying to launch it anyway.
[...]
ShellExecuteEx exception seems occurred.
```

The `flatpak run` command behaves even more weird. Executing it from the command line or a standalone script, the program successfully starts.

But executing the same command through Steam, even with the help of Bash or the script that worked before, I always get the error `Program {program_name} not found`.

Is it possible that Steam somehow messes up the environment and Bottles can't handle this?

**Comment by gregthwuen** [comment]
I tested around a little more and indeed, even when just launching Bottles through Steam with `flatpak run com.usebottles.bottles`, none of the programs are listed in my bottles. Maybe someone has an idea what's happening there?

**Comment by CannGramps** [comment]
This fix worked for me.  First, in bottles click the options dialog for the game and add to library.  Then, after you add the steam shortcut, open the properties for the program in steam and under target change xdg-open to flatpak.

And under Launch options change

bottles:run/'bottle_name'/'Game_Name'
to
run --command=bottles-cli com.usebottles.bottles run -b 'bottle_name' -p 'Game_Name'

**Comment by alpha-tango-kilo** [comment]
> And under Launch options change
> 
> bottles:run/'bottle_name'/'Game_Name'
> to
> run --command=bottles-cli com.usebottles.bottles run -b 'bottle_name' -p 'Game_Name'

Yeah that looks like an improved version of my workaround, without the intermediary script. Would still be good for this to 'just work' though

**Comment by alpha-tango-kilo** [comment]
Re-tested this and games do now appear to launch correctly in Steam Deck gaming mode, so I'm happy for the issue to stay closed. Thanks for continually improving Bottles!
