### ISSUE TITLE
[Crash report]  Destination path '/mnt/hd1/Program

### ISSUE THREAD

**Issue by Qeatrix** [bottlesdevs/Bottles#2054]
This crash report was generated by Bottles.

**Details**
* **package**: Other
* **version**: 2022.8.28-brescia-2

**Log**
```python3
Destination path '/mnt/hd1/Programs/AppsRunners/Bottles/Game-[Hard]/cache/gl_shader/GLCache' already exists  File "/usr/share/bottles/bottles/frontend/utils/threading.py", line 63, in __target
    result = self.task_func(*args, **kwargs)

  File "/usr/share/bottles/bottles/frontend/windows/main_window.py", line 204, in get_manager
    mng = Manager(window=window, repo_fn_update=repo_fn_update)

  File "/usr/share/bottles/bottles/backend/managers/manager.py", line 136, in __init__
    times.update(self.checks(install_latest=False, first_run=True))

  File "/usr/share/bottles/bottles/backend/managers/manager.py", line 193, in checks
    self.check_bottles()

  File "/usr/share/bottles/bottles/backend/managers/manager.py", line 841, in check_bottles
    process_bottle(b)

  File "/usr/share/bottles/bottles/backend/managers/manager.py", line 834, in process_bottle
    shutil.move(os.path.join(_bottle, c), os.path.join(_bottle, "cache", "gl_shader"))

  File "/usr/lib/python3.10/shutil.py", line 813, in move
    raise Error("Destination path '%s' already exists" % real_dst)

```

**Comment by twiztedtbone** [comment]
Can confirm I'm getting this as well. To add some more detail, this happens on launch and prevents Bottles from opening. In the main window, it gets to "Fetched 3 of 3 packages" and just hangs indefinitely. In terminal, you get the following:

```
18:24:33 (INFO) Bottles Started! 
18:24:35 (INFO) Catalog components loaded 
18:24:35 (INFO) Catalog installers loaded 
18:24:36 (INFO) Catalog dependencies loaded 
18:24:36 (INFO) Performing Bottles checks… 
18:24:36 (INFO) Dxvks found:
	 - dxvk-1.10.2
	 - dxvk-1.10.3
	 - dxvk-1.10.1
 
18:24:36 (INFO) Vkd3ds found:
	 - vkd3d-proton-2.6
	 - vkd3d-proton-2.6-1-5b73139
 
18:24:36 (INFO) Nvapis found:
	 - dxvk-nvapi-v0.5.4
	 - dxvk-nvapi-v0.5.3
	 - dxvk-nvapi-v0.5.2
 
18:24:36 (INFO) Latencyflexs found:
	 - latencyflex-v0.1.0
 
18:24:36 (INFO) Runners found:
	 - sys-wine-7.17
	 - GE-Proton7-17
	 - caffe-7.10-1
	 - soda-7.0-2
	 - caffe-7.15
	 - soda-7.0-3
 
18:24:37 (ERROR) Error while running async job: <function MainWindow.__on_start.<locals>.get_manager at 0x7f3a16a74820>
	Exception: Destination path '/volumes/scratch/bottles/Games/cache/gl_shader/GLCache' already exists
 
  File "/usr/share/bottles/bottles/frontend/utils/threading.py", line 63, in __target
    result = self.task_func(*args, **kwargs)
  File "/usr/share/bottles/bottles/frontend/windows/main_window.py", line 204, in get_manager
    mng = Manager(window=window, repo_fn_update=repo_fn_update)
  File "/usr/share/bottles/bottles/backend/managers/manager.py", line 136, in __init__
    times.update(self.checks(install_latest=False, first_run=True))
  File "/usr/share/bottles/bottles/backend/managers/manager.py", line 193, in checks
    self.check_bottles()
  File "/usr/share/bottles/bottles/backend/managers/manager.py", line 841, in check_bottles
    process_bottle(b)
  File "/usr/share/bottles/bottles/backend/managers/manager.py", line 834, in process_bottle
    shutil.move(os.path.join(_bottle, c), os.path.join(_bottle, "cache", "gl_shader"))
  File "/usr/lib/python3.10/shutil.py", line 813, in move
    raise Error("Destination path '%s' already exists" % real_dst)
Traceback (most recent call last):
  File "/usr/share/bottles/bottles/frontend/windows/main_window.py", line 150, in set_manager
    tmp_runners = [x for x in self.manager.runners_available if not x.startswith('sys-')]
AttributeError: 'NoneType' object has no attribute 'runners_available'
```

Using Arch and the formerly official AUR package from @francescomasala.

Thanks guys, keep doing what you're doing!
