### ISSUE TITLE
[Bug]: Check for available disk space

### ISSUE THREAD

**Issue by D3SOX** [bottlesdevs/Bottles#2066]
### Describe the bug

When creating a version, the program should check if there is enough disk space beforehand and show an error. Currently, I only see an error in the console.

It seems like because I closed the program, it saved a partial version state. How can I clean up the versions?

### To Reproduce

1. Have not enough disk space to create a version of a bottle
2. Try to create one

### Package

Flatpak from Flathub

### Distribution

Arch Linux

### Troubleshooting Logs

```shell
Version: 2022.8.28-brescia-2
Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.19.7-269-tkg-pds
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 16787369984
    Free: 16787222528
RAM:
    MemTotal: 31.3GiB
    MemAvailable: 9.2GiB
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

### Additional context

Logs:
```
OSError: [Errno 28] No space left on device: '/home/nico/.var/app/com.usebottles.bottles/data/bottles/bottles/Immortals-Fenyx-Rising__161/drive_c/Program Files (x86)/Ubisoft/Ubisoft Game Launcher/games/Immortals Fenyx Rising/dlc_24/DataPC_ORP_DLC_3_Showroom.forge' -> '/home/nico/.var/app/com.usebottles.bottles/data/bottles/bottles/Immortals-Fenyx-Rising__161/.fvs/data/d/b9ca3c32a6c9c80d62b31d088695046feaec57e7'

During handling of the above exception, another exception occurred:

OSError: [Errno 28] No space left on device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/app/share/bottles/bottles/frontend/utils/threading.py", line 73, in __target
    logging.write_log([str(exception), traceback_info])
  File "/app/share/bottles/bottles/backend/logger.py", line 103, in write_log
    crash_log.write(d)
OSError: [Errno 28] No space left on device
```

**Comment by mirkobrombin** [comment]
There is no way to predict the application size when expanded/installed

**Comment by D3SOX** [comment]
> There is no way to predict the application size when expanded/installed

Ok but it should still display an error message.

**Comment by mirkobrombin** [comment]
Not really, we have no control on what is going to be unpacked, we also don't know what was unpacked

**Comment by TheEvilSkeleton** [comment]
Out of storage can lead to different behavior depending on what's happening. There's no way we can predict this without making it computationally taxing, which isn't worth investing.
