### ISSUE TITLE
[Crash report]  'crash after enabling steam bottles'  

### ISSUE THREAD

**Issue by breningham** [bottlesdevs/Bottles#2103]
This crash report was generated by Bottles.

**Details**
* **package**: Flatpak
* **version**: 2022.8.28-brescia-2

**Log**
```python3
'name'  File "/app/share/bottles/bottles/frontend/utils/threading.py", line 63, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/frontend/windows/main_window.py", line 204, in get_manager
    mng = Manager(window=window, repo_fn_update=repo_fn_update)

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 136, in __init__
    times.update(self.checks(install_latest=False, first_run=True))

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 193, in checks
    self.check_bottles()

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 849, in check_bottles
    self.steam_manager.update_bottles()

  File "/app/share/bottles/bottles/backend/managers/steam.py", line 303, in update_bottles
    prefixes = self.list_prefixes()

  File "/app/share/bottles/bottles/backend/managers/steam.py", line 271, in list_prefixes
    if _acf["AppState"]["name"] == "Proton Experimental":

```

**Comment by breningham** [comment]
- Crashes on launch after enabling "Steam proton prefixes" 

- Crashlog from terminal: 

```
(process:2): Adwaita-WARNING **: 19:02:14.430: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
19:02:14 (INFO) Bottles Started! 
19:02:15 (INFO) Catalog components loaded 
19:02:15 (INFO) Catalog installers loaded 
19:02:15 (INFO) Catalog dependencies loaded 
19:02:15 (INFO) Performing Bottles checks… 
19:02:15 (INFO) Dxvks found:
         - dxvk-1.10.3
 
19:02:15 (INFO) Vkd3ds found:
         - vkd3d-proton-2.6-1-5b73139
 
19:02:15 (INFO) Nvapis found:
         - dxvk-nvapi-v0.5.4
 
19:02:15 (INFO) Latencyflexs found:
         - latencyflex-v0.1.0
 
19:02:15 (INFO) Runners found:
         - sys-wine-7.0
         - soda-7.0-3
 
19:02:15 (INFO) Bottles found:
         - BattleDotNet
 
19:02:15 (ERROR) Error while running async job: <function MainWindow.__on_start.<locals>.get_manager at 0x7f6c67be6200>
        Exception: 'name'
 
  File "/app/share/bottles/bottles/frontend/utils/threading.py", line 63, in __target
    result = self.task_func(*args, **kwargs)
  File "/app/share/bottles/bottles/frontend/windows/main_window.py", line 204, in get_manager
    mng = Manager(window=window, repo_fn_update=repo_fn_update)
  File "/app/share/bottles/bottles/backend/managers/manager.py", line 136, in __init__
    times.update(self.checks(install_latest=False, first_run=True))
  File "/app/share/bottles/bottles/backend/managers/manager.py", line 193, in checks
    self.check_bottles()
  File "/app/share/bottles/bottles/backend/managers/manager.py", line 849, in check_bottles
    self.steam_manager.update_bottles()
  File "/app/share/bottles/bottles/backend/managers/steam.py", line 303, in update_bottles
    prefixes = self.list_prefixes()
  File "/app/share/bottles/bottles/backend/managers/steam.py", line 271, in list_prefixes
    if _acf["AppState"]["name"] == "Proton Experimental":
Traceback (most recent call last):
  File "/app/share/bottles/bottles/frontend/windows/main_window.py", line 150, in set_manager
    tmp_runners = [x for x in self.manager.runners_available if not x.startswith('sys-')]
AttributeError: 'NoneType' object has no attribute 'runners_available'
```
