### ISSUE TITLE
[Bug]: Newly-added custom executables can't be immediately used

### ISSUE THREAD

**Issue by Nocifer** [bottlesdevs/Bottles#2147]
### Describe the bug

When I add a new executable, I can't launch it or change its launch options until I either restart Bottles or rename the executable.

Adding the game and then trying to change the launch options:

```
13:03:50 (INFO) Setting Key 25dce9f7-89f5-4aec-bc70-1270fb7838f6={'executable': 'Borderlands.exe', 'name': 'Borderlands', 'path': '/home/nocifer/Games/Tales from the Borderlands/Borderlands.exe', 'id': '25dce9f7-89f5-4aec-bc70-1270fb7838f6'} for bottle Default… 
Traceback (most recent call last):
  File "/app/share/bottles/bottles/frontend/widgets/program.py", line 134, in show_launch_options_view
    dialog = LaunchOptionsDialog(self, self.config, self.program)
  File "/app/share/bottles/bottles/frontend/windows/launchoptions.py", line 126, in __init__
    self.action_cwd.set_subtitle(program["folder"])
KeyError: 'folder'
```

Trying to launch the executable:

```
13:04:00 (ERROR) Error while running async job: <function ProgramEntry.run_executable.<locals>._run at 0x7fb508bdeb00>
        Exception: 'arguments'
 
  File "/app/share/bottles/bottles/frontend/utils/threading.py", line 63, in __target
    result = self.task_func(*args, **kwargs)
  File "/app/share/bottles/bottles/frontend/widgets/program.py", line 180, in _run
    WineExecutor.run_program(self.config, self.program, with_terminal)
  File "/app/share/bottles/bottles/backend/wine/executor.py", line 121, in run_program
    args=program["arguments"],
```

### To Reproduce

1. Add a new executable
2. Try to launch it or change its launch options

### Package

Flatpak from Flathub

### Distribution

Arch Linux

### Troubleshooting Logs

```shell
Version: 2022.9.28.1
Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.19.13-arch1-1
Distro:
    Name: GNOME
    Version: '43'
Disk:
    Total: 8337104896
    Free: 8336949248
RAM:
    MemTotal: "16,7\_GB"
    MemAvailable: "11,9\_GB"
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

**Comment by sigzegv** [comment]
Issue still present when clicking "change its launch options" just after adding an executable (using bottles v51.5 on debian 12)
