### ISSUE TITLE
[Bug]: Crash on ArchLinux with Python 3.10.7

### ISSUE THREAD

**Issue by Geequlim** [bottlesdevs/Bottles#2152]
### Describe the bug

Cannot start bottles with python 3.10.7 on Arch Linux
Package is installed from AUR https://aur.archlinux.org/packages/bottles

### To Reproduce

1. Install from AUR https://aur.archlinux.org/packages/bottles
2. Run bottles

### Package

Other, unofficial package

### Distribution

Arch Linux

### Troubleshooting Logs

```shell
Traceback (most recent call last):
  File "/usr/bin/bottles", line 43, in <module>
    from bottles.frontend import main
  File "/usr/share/bottles/bottles/frontend/main.py", line 37, in <module>
    from bottles.frontend.windows.main_window import MainWindow
  File "/usr/share/bottles/bottles/frontend/windows/main_window.py", line 34, in <module>
    from bottles.backend.managers.manager import Manager
  File "/usr/share/bottles/bottles/backend/managers/manager.py", line 43, in <module>
    from bottles.backend.managers.component import ComponentManager
  File "/usr/share/bottles/bottles/backend/managers/component.py", line 22, in <module>
    import requests
  File "/home/geequlim/.local/lib/python3.10/site-packages/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/home/geequlim/.local/lib/python3.10/site-packages/requests/utils.py", line 30, in <module>
    from .cookies import RequestsCookieJar, cookiejar_from_dict
  File "/home/geequlim/.local/lib/python3.10/site-packages/requests/cookies.py", line 164, in <module>
    class RequestsCookieJar(cookielib.CookieJar, collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'
```
```


### Display Protocol

X11

### Display Backend used by Bottles

X11

### Additional context

_No response_

**Comment by mirkobrombin** [comment]
I confirm the bug with py 3.10.7 (that could wait a while to arrive)

**Comment by mirkobrombin** [comment]
Reading the log better and looking at the Bottles code I concluded that the bug is not in Bottles but in a package that uses (requests). The maintainer of that package must update it to the latest version if available.
