### ISSUE TITLE
[Bug]: Traceback on "Change Launch Options"

### ISSUE THREAD

**Issue by faveoled** [bottlesdevs/Bottles#2157]
### Describe the bug

Traceback on "Change Launch Options"
```
Traceback (most recent call last):
  File "/app/share/bottles/bottles/frontend/widgets/program.py", line 134, in show_launch_options_view
    dialog = LaunchOptionsDialog(self, self.config, self.program)
  File "/app/share/bottles/bottles/frontend/windows/launchoptions.py", line 126, in __init__
    self.action_cwd.set_subtitle(program["folder"])
KeyError: 'folder'

```

### To Reproduce

Set working directory in launch options
Move actual working directory (Not sure about that)
Open "Change Launch Options" 

### Package

Flatpak from Flathub

### Distribution

Ubuntu 22.04.1

### Troubleshooting Logs

```shell
Version: 2022.9.28.1
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        intel:
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.15.0-48-generic
Distro:
    Name: GNOME
    Version: '43'
Disk:
    Total: 4084727808
    Free: 4084584448
RAM:
    MemTotal: "8.2\_GB"
    MemAvailable: "4.8\_GB"
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

**Comment by mirkobrombin** [comment]
Fixed some commits ago, will be distributed with 2022.10.14
