### ISSUE TITLE
[Bug]: Cannot rename bottle

### ISSUE THREAD

**Issue by marcelohdez** [bottlesdevs/Bottles#2304]
### Describe the bug

When trying to change the name of a bottle, nothing happens graphically, but on terminal it is printed:
```
Traceback (most recent call last):
  File "/app/share/bottles/bottles/frontend/views/bottle_preferences.py", line 216, in __save_name
    if not self.__valid_name:
AttributeError: 'PreferencesView' object has no attribute '_PreferencesView__valid_name'. Did you mean: '_PreferencesView__save_name'?
```
I was been able to change the bottle's name by directly editing the .yml file.

### To Reproduce

1. Open a bottle's settings
2. Change the name
3. Click the check-mark, press enter, or do any thing that should change the name
4. Back out of bottle's settings
5. See the name has not changed

### Package

Flatpak from Flathub

### Distribution

Fedora 37

### Troubleshooting Logs

```shell
Version: 2022.11.14
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.0.8-300.fc37.x86_64
Distro:
    Name: GNOME
    Version: '43'
Disk:
    Total: 8343384064
    Free: 8343240704
RAM:
    MemTotal: "16.7\_GB"
    MemAvailable: "10.2\_GB"
Bottles_envs: null
```

### Display Protocol

Wayland

### Display Backend used by Bottles

I don't know

**Comment by tur1ngb0x** [comment]
I am affected by this as well.

**Bug**
```
$ flatpak info com.usebottles.bottles
```
```
Traceback (most recent call last):
  File "/app/share/bottles/bottles/frontend/views/bottle_preferences.py", line 216, in __save_name
    if not self.__valid_name:
AttributeError: 'PreferencesView' object has no attribute '_PreferencesView__valid_name'. Did you mean: '_PreferencesView__save_name'?
```

**Reproduce**
1. Open settings of any bottle.
2. Change name, apply, go back.
3. Bottle name is unchanged.

**Package**
```
$ flatpak info com.usebottles.bottles
```
```
Bottles - Run Windows Software

          ID: com.usebottles.bottles
         Ref: app/com.usebottles.bottles/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 2022.11.14
     License: GPL-3.0-only
      Origin: flathub
  Collection: org.flathub.Stable
Installation: user
   Installed: 473.7 MB
     Runtime: org.gnome.Platform/x86_64/43
         Sdk: org.gnome.Sdk/x86_64/43

      Commit: 2a3c78b0e693837c5ffcafa2b3059b96ee3579952145e7b9d7a667b20d260519
      Parent: 7ab4ed9b55720be65fdd1aaebdadbcbd861701b47da156e8f53a0b2d33e3eb67
     Subject: 2022.11.14 (176cbc97)
        Date: 2022-11-14 08:28:32 +0000
```

**Distribution**
```
$ cat /etc/os-release
```
```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```

**Display Protocol**
X11

**Display Backend Bottles**
X11

**Comment by mirkobrombin** [comment]
Fixed in #2313
