### ISSUE TITLE
[Bug]: 'Result' object has no attribute 'get' 

### ISSUE THREAD

**Issue by JamesClarke7283** [bottlesdevs/Bottles#2307]
### Describe the bug

'Result' object has no attribute 'get'  File "/app/share/bottles/bottles/frontend/utils/threading.py", line 63, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/backend/wine/wineprogram.py", line 72, in launch_terminal
    self.launch(args=args, terminal=True, action_name="launch_terminal")

  File "/app/share/bottles/bottles/backend/wine/wineprogram.py", line 58, in launch
    res = WineCommand(

  File "/app/share/bottles/bottles/backend/wine/winecommand.py", line 100, in __init__
    self.cwd = self.__get_cwd(cwd)

  File "/app/share/bottles/bottles/backend/wine/winecommand.py", line 112, in __get_cwd
    if config.get("Environment", "Custom") == "Steam":

### To Reproduce

1. Open Up Bottles

### Package

Flatpak from Flathub

### Distribution

Debian 11

### Troubleshooting Logs

```shell
Version: 2022.11.14
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        intel:
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.0.0-4-amd64
Distro:
    Name: GNOME
    Version: '43'
Disk:
    Total: 4125835264
    Free: 4125691904
RAM:
    MemTotal: "8.3\_GB"
    MemAvailable: "3.5\_GB"
Bottles_envs: null
```

### Display Protocol

Wayland

### Display Backend used by Bottles

Wayland

### Additional context

It must have crashed last time i open it up now and it works.

**Comment by SuperSamus** [comment]
I have the same issue, but reproduced differently.
Closing a program launched with `Run Executable`, will return the following error, which make launching something else impossible until going back to the bottles list, then to the bottle again. Going to a sub-menu of the bottle instead makes going back to the bottles list impossible (the back button is disabled).
```
  File "/nix/store/a356kir9zdwxg2k1yvkasvbn7qqvaj21-bottles-2022.11.14/share/bottles/bottles/frontend/views/bottle_details.py", line 330, in update_programs
    process_programs()
  File "/nix/store/a356kir9zdwxg2k1yvkasvbn7qqvaj21-bottles-2022.11.14/share/bottles/bottles/frontend/views/bottle_details.py", line 311, in process_programs
    wineserver_status = WineServer(self.config).is_alive()
  File "/nix/store/a356kir9zdwxg2k1yvkasvbn7qqvaj21-bottles-2022.11.14/share/bottles/bottles/backend/utils/decorators.py", line 44, in wrapped_f
    return f(*args, **kwargs)
  File "/nix/store/a356kir9zdwxg2k1yvkasvbn7qqvaj21-bottles-2022.11.14/share/bottles/bottles/backend/wine/wineserver.py", line 25, in is_alive
    if not config.get("Runner"):
AttributeError: 'Result' object has no attribute 'get'
```

Not using Flatpak.

**Comment by teleprint-me** [comment]
I'm getting the same issue using a system install.

I'm attempting to use WolvenKit inside of Bottles and a dep is .Net 6 (this isn't listed as an available dep and most deps that are available are very out of date) which runs and I have to close it out once it finishes executing. I was able to reproduce SuperSamus' issue as well by going back and forth between the menus.

I use journalctl to watch my system as it runs so I can catch anything that's going wrong as it's happening by just doing `journalctl -xb -f` which will just use stdout and follow any system actions. It's amazing for debugging issues. 

```
Nov 23 23:18:36 blackbox com.usebottles.bottles.desktop[2466]: 23:18:36 (INFO) Opening the file manager in the path … 
Nov 23 23:18:36 blackbox com.usebottles.bottles.desktop[2466]: Traceback (most recent call last):
Nov 23 23:18:36 blackbox com.usebottles.bottles.desktop[2466]:   File "/usr/share/bottles/bottles/frontend/views/bottle_details.py", line 532, in run_browse
Nov 23 23:18:36 blackbox com.usebottles.bottles.desktop[2466]:     ManagerUtils.open_filemanager(self.config)
Nov 23 23:18:36 blackbox com.usebottles.bottles.desktop[2466]:   File "/usr/share/bottles/bottles/backend/utils/manager.py", line 53, in open_filemanager
Nov 23 23:18:36 blackbox com.usebottles.bottles.desktop[2466]:     bottle_path = ManagerUtils.get_bottle_path(config)
Nov 23 23:18:36 blackbox com.usebottles.bottles.desktop[2466]:   File "/usr/share/bottles/bottles/backend/utils/manager.py", line 87, in get_bottle_path
Nov 23 23:18:36 blackbox com.usebottles.bottles.desktop[2466]:     if config.get("Environment") == "Steam":
Nov 23 23:18:36 blackbox com.usebottles.bottles.desktop[2466]: AttributeError: 'Result' object has no attribute 'get'
```

Once I attempted to execute the application after installing the dep, it fails miserably and locks me out. After a bit of messing around, I was able to get this.

```
Nov 23 23:21:22 blackbox kernel: audit: type=1130 audit(1669263682.790:148): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-hostnamed comm="systemd" exe="/usr/lib/syst
emd/systemd" hostname=? addr=? terminal=? res=success'                                                                                                                              
Nov 23 23:21:25 blackbox com.usebottles.bottles.desktop[2466]: 23:21:25 (INFO) Launching an executable…                                                                              
Nov 23 23:21:25 blackbox com.usebottles.bottles.desktop[6022]: wineserver: using server-side synchronization.                                                                        
Nov 23 23:21:25 blackbox com.usebottles.bottles.desktop[6022]: wine: RLIMIT_NICE is <= 20, unable to use setpriority safely                                                          
Nov 23 23:21:25 blackbox com.usebottles.bottles.desktop[6024]: 002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (2).             
Nov 23 23:21:29 blackbox com.usebottles.bottles.desktop[6020]: wine: Call from 00000001700324C0 to unimplemented function KERNEL32.dll.RaiseFailFastException, aborting              
Nov 23 23:21:29 blackbox com.usebottles.bottles.desktop[6020]: Fatal error. Internal CLR error. (0x80131506)                                                                         
Nov 23 23:21:29 blackbox com.usebottles.bottles.desktop[6020]: Repeat 2 times:                                                                                                       
Nov 23 23:21:29 blackbox com.usebottles.bottles.desktop[6020]: --------------------------------                                                                                      
Nov 23 23:21:29 blackbox com.usebottles.bottles.desktop[6020]:    at Microsoft.ClearScript.V8.SplitProxy.V8SplitProxyNative+Impl_Windows_X64.V8Isolate_Create(Ptr, Int32, Int32, Doub
le, UInt64, Microsoft.ClearScript.V8.V8RuntimeFlags, Int32)                                                                                                                         
Nov 23 23:21:29 blackbox com.usebottles.bottles.desktop[6020]: --------------------------------                                                                                      
Nov 23 23:21:29 blackbox com.usebottles.bottles.desktop[6020]:    at Microsoft.ClearScript.V8.SplitProxy.V8SplitProxyNative+Impl_Windows_X64.Microsoft.ClearScript.V8.SplitProxy.IV8S
plitProxyNative.V8Isolate_Create(System.String, Int32, Int32, Double, UInt64, Microsoft.ClearScript.V8.V8RuntimeFlags, Int32)                                                       
Nov 23 23:21:29 blackbox com.usebottles.bottles.desktop[6020]:    at Microsoft.ClearScript.V8.SplitProxy.V8IsolateProxyImpl+<>c__DisplayClass3_0.<.ctor>b__1(Microsoft.ClearScript.V8
.SplitProxy.IV8SplitProxyNative)                                                                                                                                                    
Nov 23 23:21:29 blackbox com.usebottles.bottles.desktop[6020]:    at Microsoft.ClearScript.V8.SplitProxy.V8SplitProxyNative.Invoke[[Microsoft.ClearScript.V8.SplitProxy.V8Isolate+Han
dle, ClearScript.V8, Version=7.3.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](System.Func`2<Microsoft.ClearScript.V8.SplitProxy.IV8SplitProxyNative,Handle>)             
Nov 23 23:21:29 blackbox com.usebottles.bottles.desktop[6020]:    at Microsoft.ClearScript.V8.SplitProxy.V8IsolateProxyImpl+<>c__DisplayClass3_0.<.ctor>b__0()                       
Nov 23 23:21:29 blackbox com.usebottles.bottles.desktop[6020]:    at Microsoft.ClearScript.V8.SplitProxy.V8EntityHolder..ctor(System.String, System.Func`1<Handle>)                  
Nov 23 23:21:29 blackbox com.usebottles.bottles.desktop[6020]:    at Microsoft.ClearScript.V8.SplitProxy.V8IsolateProxyImpl..ctor(System.String, Microsoft.ClearScript.V8.V8RuntimeCo
nstraints, Microsoft.ClearScript.V8.V8RuntimeFlags, Int32)                                                                                                                          
Nov 23 23:21:29 blackbox com.usebottles.bottles.desktop[6020]:    at Microsoft.ClearScript.V8.V8IsolateProxy.Create(System.String, Microsoft.ClearScript.V8.V8RuntimeConstraints, Mic
rosoft.ClearScript.V8.V8RuntimeFlags, Int32)                                                                                                                                        
Nov 23 23:21:29 blackbox com.usebottles.bottles.desktop[6020]:    at Microsoft.ClearScript.V8.V8Runtime..ctor(System.String, Microsoft.ClearScript.V8.V8RuntimeConstraints, Microsoft
.ClearScript.V8.V8RuntimeFlags, Int32)                                                                                                                                              
Nov 23 23:21:29 blackbox com.usebottles.bottles.desktop[6020]:    at Microsoft.ClearScript.V8.V8Runtime..ctor(System.String, Microsoft.ClearScript.V8.V8RuntimeConstraints, Microsoft
.ClearScript.V8.V8RuntimeFlags)                                                                                                                                                     
Nov 23 23:21:29 blackbox com.usebottles.bottles.desktop[6020]:    at Microsoft.ClearScript.V8.V8Runtime..ctor(System.String, Microsoft.ClearScript.V8.V8RuntimeConstraints)          
Nov 23 23:21:29 blackbox com.usebottles.bottles.desktop[6020]:    at Microsoft.ClearScript.V8.V8ScriptEngine..ctor(Microsoft.ClearScript.V8.V8Runtime, System.String, Microsoft.Clear
Script.V8.V8RuntimeConstraints, Microsoft.ClearScript.V8.V8ScriptEngineFlags, Int32)                                                                                                
Nov 23 23:21:29 blackbox com.usebottles.bottles.desktop[6020]:    at WolvenKit.Modkit.Scripting.ScriptService.GetScriptEngine(System.Collections.Generic.Dictionary`2<System.String,S
ystem.Object>, System.String)                                                                                                                                                       
Nov 23 23:21:29 blackbox com.usebottles.bottles.desktop[6020]:    at WolvenKit.Functionality.Services.ExtendedScriptService.GetUIScriptEngine(System.Collections.Generic.Dictionary`2
<System.String,System.Object>, System.String)                                                                                                                                       
Nov 23 23:21:29 blackbox com.usebottles.bottles.desktop[6020]:    at WolvenKit.Functionality.Services.ExtendedScriptService.RefreshUIScripts()                                       
Nov 23 23:21:29 blackbox com.usebottles.bottles.desktop[6020]:    at WolvenKit.Functionality.Services.ExtendedScriptService..ctor(WolvenKit.Core.Interfaces.ILoggerService)          
Nov 23 23:21:29 blackbox com.usebottles.bottles.desktop[6020]:    at WolvenKit.GenericHost+<>c.<CreateHostBuilder>b__0_2(Microsoft.Extensions.Hosting.HostBuilderContext, Microsoft.E
xtensions.DependencyInjection.IServiceCollection)                                                                                                                                   
Nov 23 23:21:29 blackbox com.usebottles.bottles.desktop[6020]:    at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()                                                
Nov 23 23:21:29 blackbox com.usebottles.bottles.desktop[6020]:    at Microsoft.Extensions.Hosting.HostBuilder.Build()                                                                
Nov 23 23:21:29 blackbox com.usebottles.bottles.desktop[6020]:    at WolvenKit.AppImpl.Init()                                                                                        
Nov 23 23:21:29 blackbox com.usebottles.bottles.desktop[6020]:    at WolvenKit.AppImpl..ctor()                                                                                       
Nov 23 23:21:29 blackbox com.usebottles.bottles.desktop[6020]:    at WolvenKit.AppImpl.Main()                                                                                        
Nov 23 23:21:29 blackbox com.usebottles.bottles.desktop[6020]: 0024:err:eventlog:ReportEventW L"Application: WolvenKit.exe\nCoreCLR Version: 6.0.1122.52304\n.NET Version: 6.0.11\nDe
scription: The process was terminated due to an internal error in the .NET Runtime at IP 00000000018D0FD8 (00000000016C0000) with exit code 80131506.\n"                            
Nov 23 23:21:29 blackbox com.usebottles.bottles.desktop[2466]: Traceback (most recent call last):                                                                                    
Nov 23 23:21:29 blackbox com.usebottles.bottles.desktop[2466]:   File "/usr/share/bottles/bottles/frontend/views/bottle_details.py", line 330, in update_programs                    
Nov 23 23:21:29 blackbox com.usebottles.bottles.desktop[2466]:     process_programs()                                                                                                
Nov 23 23:21:29 blackbox com.usebottles.bottles.desktop[2466]:   File "/usr/share/bottles/bottles/frontend/views/bottle_details.py", line 311, in process_programs
Nov 23 23:21:29 blackbox com.usebottles.bottles.desktop[2466]:     wineserver_status = WineServer(self.config).is_alive()                            
Nov 23 23:21:29 blackbox com.usebottles.bottles.desktop[2466]:   File "/usr/share/bottles/bottles/backend/utils/decorators.py", line 44, in wrapped_f
Nov 23 23:21:29 blackbox com.usebottles.bottles.desktop[2466]:     return f(*args, **kwargs)                                                       
Nov 23 23:21:29 blackbox com.usebottles.bottles.desktop[2466]:   File "/usr/share/bottles/bottles/backend/wine/wineserver.py", line 25, in is_alive
Nov 23 23:21:29 blackbox com.usebottles.bottles.desktop[2466]:     if not config.get("Runner"):                                               
Nov 23 23:21:29 blackbox com.usebottles.bottles.desktop[2466]: AttributeError: 'Result' object has no attribute 'get'  
```

**Comment by RichardFevrier** [comment]
I have also tried to install .Net 6 for another software and I have encountered the same problem (`soda-7.0-4` runner `windows 10`)
