### ISSUE TITLE
Vkbasalt-cli is not an optional depency.

### ISSUE THREAD

**Issue by QuantMint** [bottlesdevs/Bottles#2335]
The [wiki](https://github.com/bottlesdevs/Bottles/wiki/Packaging) says that vkbasalt-cli is an optional dependency, but when trying to build bottles without it(on nixos) this happens:
```
Traceback (most recent call last):
  File "/nix/store/fdshsi6z5gzj4k0y4dcg57r6lw8lq14q-bottles-unwrapped-2022.11.14/bin/.bottles-wrapped", line 44, in <module>
    from bottles.frontend import main
  File "/nix/store/fdshsi6z5gzj4k0y4dcg57r6lw8lq14q-bottles-unwrapped-2022.11.14/share/bottles/bottles/frontend/main.py", line 37, in <module>
    from bottles.frontend.windows.main_window import MainWindow
  File "/nix/store/fdshsi6z5gzj4k0y4dcg57r6lw8lq14q-bottles-unwrapped-2022.11.14/share/bottles/bottles/frontend/windows/main_window.py", line 38, in <module>
    from bottles.frontend.views.details import DetailsView
  File "/nix/store/fdshsi6z5gzj4k0y4dcg57r6lw8lq14q-bottles-unwrapped-2022.11.14/share/bottles/bottles/frontend/views/details.py", line 28, in <module>
    from bottles.frontend.views.bottle_preferences import PreferencesView
  File "/nix/store/fdshsi6z5gzj4k0y4dcg57r6lw8lq14q-bottles-unwrapped-2022.11.14/share/bottles/bottles/frontend/views/bottle_preferences.py", line 39, in <module>
    from bottles.frontend.windows.vkbasalt import VkBasaltDialog
  File "/nix/store/fdshsi6z5gzj4k0y4dcg57r6lw8lq14q-bottles-unwrapped-2022.11.14/share/bottles/bottles/frontend/windows/vkbasalt.py", line 30, in <module>
    from vkbasalt.lib import parse, ParseConfig
ModuleNotFoundError: No module named 'vkbasalt'
```

**Comment by mirkobrombin** [comment]
Wiki updated
