### ISSUE TITLE
add python-pycurl as a dependency

### ISSUE THREAD

**Issue by duarm** [bottlesdevs/Bottles#2367]
pycurl is not listed as a dependency for bottles in the packaging page https://github.com/bottlesdevs/Bottles/wiki/Packaging

running without it results in an error

```
Traceback (most recent call last):
  File "/usr/bin/bottles", line 43, in <module>
    from bottles.frontend import main
  File "/usr/share/bottles/bottles/frontend/main.py", line 37, in <module>
    from bottles.frontend.windows.main_window import MainWindow
  File "/usr/share/bottles/bottles/frontend/windows/main_window.py", line 30, in <module>
    from bottles.frontend.utils.connection import ConnectionUtils
  File "/usr/share/bottles/bottles/frontend/utils/connection.py", line 20, in <module>
    import pycurl
ModuleNotFoundError: No module named 'pycurl'
```

**Comment by mirkobrombin** [comment]
Thanks for reporting. Added
