### ISSUE TITLE
[Bug]: AttributeError: 'Result' object has no attribute 'get'

### ISSUE THREAD

**Issue by latin-1** [bottlesdevs/Bottles#2377]
### Describe the bug

After a wine program exited, this error occurs.

### To Reproduce

- Run any program from `Run executable...` then exit that program

### Package

Flatpak from Flathub

### Distribution

Arch Linux

### Troubleshooting Logs

```shell
Traceback (most recent call last):
  File "/app/share/bottles/bottles/frontend/views/bottle_details.py", line 330, in update_programs
    process_programs()
  File "/app/share/bottles/bottles/frontend/views/bottle_details.py", line 311, in process_programs
    wineserver_status = WineServer(self.config).is_alive()
  File "/app/share/bottles/bottles/backend/utils/decorators.py", line 44, in wrapped_f
    return f(*args, **kwargs)
  File "/app/share/bottles/bottles/backend/wine/wineserver.py", line 25, in is_alive
    if not config.get("Runner"):
AttributeError: 'Result' object has no attribute 'get'
```

### Display Protocol

Wayland

### Display Backend used by Bottles

I don't know

**Comment by latin-1** [comment]
I can still reproduce this bug in 2022.12.14.1

**Comment by GhislainViguier** [comment]
I have the same issue

**Comment by Bai-Chiang** [comment]
I also have this issue on Arch.

Version:
2022.12.14.1

Package:
flatpak

DE:
sway

```
Traceback (most recent call last):
  File "/app/share/bottles/bottles/frontend/views/bottle_details.py", line 330, in update_programs
    process_programs()
  File "/app/share/bottles/bottles/frontend/views/bottle_details.py", line 311, in process_programs
    wineserver_status = WineServer(self.config).is_alive()
  File "/app/share/bottles/bottles/backend/wine/wineserver.py", line 24, in is_alive
    if not config.get("Runner"):
AttributeError: 'Result' object has no attribute 'get'
```
Debug info:
```
Official Package: true
Version: 2022.12.14.1
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        nvidia: &amp;id002
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: ''
        amd: &amp;id001
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: *id001
        discrete: *id002
Kernel:
    Type: Linux
    Version: 6.1.1-arch1-1
Distro:
    Name: GNOME
    Version: '43'
Disk:
    Total: 8345387008
    Free: 8345243648
RAM:
    MemTotal: 15.5GiB
    MemAvailable: 7.0GiB
Bottles_envs: null
```

**Comment by glyh** [comment]
Have the same issue.

**Comment by azu0609** [comment]
I have same issue on pop!_os 22.04 + 2022.12.14.1

**Comment by Kinsteen** [comment]
Fixed in Bottles 50
