### ISSUE TITLE
[Bug]: Bottles stuck on "Starting up...", python AttributeError

### ISSUE THREAD

**Issue by cheezos** [bottlesdevs/Bottles#2379]
### Describe the bug

Stuck on "Starting up...", able to fetch 3 of 3 packages.
Worked fine yesterday.

```
flatpak run -v com.usebottles.bottles
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/colt/.local/share/flatpak
F: Opening user flatpak installation at path /home/colt/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/colt/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/43/c01cb33cf898efab6b025c9a64480c6dc201ced293de7f49cd126a93659d3d3f/files/lib32 does not exist
F: Cleaning up unused container id 301439643
F: Cleaning up per-app-ID state for com.usebottles.bottles
F: Allocated instance id 2914593252
F: Add defaults in dir /com/usebottles/bottles/
F: Add locks in dir /com/usebottles/bottles/
F: Allowing wayland access
F: Allowing x11 access
F: Allowing pulseaudio access
F: Pulseaudio user configuration file '/home/colt/.config/pulse/client.conf': Error opening file /home/colt/.config/pulse/client.conf: No such file or directory
F: Running 'bwrap --args 46 xdg-dbus-proxy --args=48'
F: Running 'bwrap --args 46 bottles'
06:49:29 (INFO) Bottles Started! 
06:49:33 (INFO) Catalog components loaded 
06:49:33 (INFO) Catalog installers loaded 
06:49:34 (INFO) Catalog dependencies loaded 
06:49:34 (INFO) Performing Bottles checks… 
06:49:34 (INFO) Dxvks found:
	 - dxvk-2.0
 
06:49:34 (INFO) Vkd3ds found:
	 - vkd3d-proton-2.7
 
06:49:34 (INFO) Nvapis found:
	 - dxvk-nvapi-v0.5.4
 
06:49:34 (INFO) Latencyflexs found:
	 - latencyflex-v0.1.1
 
06:49:34 (INFO) Runners found:
	 - sys-wine-7.0.1
	 - soda-7.0-7
	 - soda-7.0-8
	 - GE-Proton7-42
	 - wine-ge-proton7-34
	 - lutris-7.2-fshack
	 - caffe-7.20
	 - lutris-7.2-2
 
06:49:34 (INFO) Temp directory cleaned successfully! 
06:49:35 (INFO) Bottles found:
	 - Games
 

(bottles:2): Gtk-CRITICAL **: 06:49:35.601: gtk_widget_set_parent: assertion '_gtk_widget_get_parent (widget) == NULL' failed
06:49:36 (INFO) Library saved 
Traceback (most recent call last):
  File "/app/share/bottles/bottles/frontend/windows/main_window.py", line 155, in set_manager
    self.page_library = LibraryView(self)
  File "/app/share/bottles/bottles/frontend/views/library.py", line 43, in __init__
    self.update()
  File "/app/share/bottles/bottles/frontend/views/library.py", line 56, in update
    entry = LibraryEntry(self, u, e)
  File "/app/share/bottles/bottles/frontend/widgets/library.py", line 62, in __init__
    self.__remove_entry()
  File "/app/share/bottles/bottles/frontend/widgets/library.py", line 137, in __remove_entry
    self.library.remove_entry(self)
  File "/app/share/bottles/bottles/frontend/views/library.py", line 66, in remove_entry
    entry.hide()
  File "/app/share/bottles/bottles/frontend/widgets/library.py", line 169, in hide
    self.get_parent().set_visible(False)
AttributeError: 'NoneType' object has no attribute 'set_visible'

```

### To Reproduce

1. Open bottles
2. That's it

### Package

Flatpak from Flathub

### Distribution

Ubuntu 22.04.1 LTS

### Troubleshooting Logs

```shell
Can't access the logs.
```

### Display Protocol

Wayland

### Display Backend used by Bottles

I don't know

**Comment by kingpanguan** [comment]
i have the exact same issue, fetched 3 of 3 packages, frozen loading screen, did you ever find a fix?

**Comment by mrwan218** [comment]
I have a similar problem.

starting from terminal 

```
╭─mrwan@mrwan in ~ took 14m21s
╰─λ bottles
21:45:58 (ERROR) Data file not found. Creating new one.

(process:9820): Gtk-WARNING **: 21:45:58.762: Theme parser error: gtk-dark.css:5605:3-9: No property named "he
ight"

(process:9820): Adwaita-WARNING **: 21:45:58.784: Using GtkSettings:gtk-application-prefer-dark-theme with lib
adwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
21:45:58 (INFO) Bottles Started!
21:46:01 (INFO) Performing Bottles checks…
21:46:01 (INFO) Runners path doesn't exist, creating now.
21:46:01 (INFO) Runtimes path doesn't exist, creating now.
21:46:01 (INFO) WineBridge path doesn't exist, creating now.
21:46:01 (INFO) Bottles path doesn't exist, creating now.
21:46:01 (INFO) Dxvk path doesn't exist, creating now.
21:46:01 (INFO) Vkd3d path doesn't exist, creating now.
21:46:01 (INFO) Nvapi path doesn't exist, creating now.
21:46:01 (INFO) Templates path doesn't exist, creating now.
21:46:01 (INFO) Temp path doesn't exist, creating now.
21:46:01 (INFO) LatencyFleX path doesn't exist, creating now.
Traceback (most recent call last):
File "/usr/share/bottles/bottles/frontend/windows/main_window.py", line 149, in set_manager
self.page_details = DetailsView(self)
File "/usr/share/bottles/bottles/frontend/views/details.py", line 78, in __init__
self.view_bottle = BottleView(self, config)
File "/usr/share/bottles/bottles/frontend/views/bottle_details.py", line 163, in __init__
self.style_provider.load_from_data(b".dragndrop_overlay { background: rgba(41, 65, 94, 0.2);}")
TypeError: Gtk.CssProvider.load_from_data() takes exactly 3 arguments (2 given)
21:46:02 (INFO) Catalog installers loaded
21:46:02 (INFO) Catalog dependencies loaded
21:46:02 (INFO) Catalog components loaded
21:46:05 (INFO) Performing Bottles checks…
21:46:05 (WARNING) No dxvk found.
21:46:06 (INFO) Installing component: [dxvk-2.1-1-d14dcf5].
Traceback (most recent call last):
File "/usr/share/bottles/bottles/frontend/operation.py", line 81, in new_task
self.__tasks[task_id] = self.__new_widget(title, cancellable)
File "/usr/share/bottles/bottles/frontend/operation.py", line 77, in __new_widget
self.window.page_details.list_tasks.append(task_entry)
AttributeError: 'MainWindow' object has no attribute 'page_details'
dxvk-2.1-1-d14dcf5.tar.gz (100%) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (7.9 MB/7.9 MB - 249.5 kB)

21:46:38 (INFO) Renaming [dxvk-2.1-1-d14dcf5.tar.gz] to [dxvk-2.1-1-d14dcf5.tar.gz].
Traceback (most recent call last):
File "/usr/share/bottles/bottles/frontend/operation.py", line 96, in remove_task
self.window.page_details.btn_operations.set_visible(False)
AttributeError: 'MainWindow' object has no attribute 'page_details'
21:46:38 (INFO) Dxvks found:
- dxvk-2.1-1-d14dcf5

21:46:38 (INFO) Component installed: dxvk dxvk-2.1-1-d14dcf5
21:46:38 (WARNING) No vkd3d found.
21:46:39 (INFO) Installing component: [vkd3d-proton-2.8-1-b7fb41b].
Traceback (most recent call last):
File "/usr/share/bottles/bottles/frontend/operation.py", line 81, in new_task
self.__tasks[task_id] = self.__new_widget(title, cancellable)
File "/usr/share/bottles/bottles/frontend/operation.py", line 77, in __new_widget
self.window.page_details.list_tasks.append(task_entry)
AttributeError: 'MainWindow' object has no attribute 'page_details'
vkd3d-proton-2.8-1-b7fb41b.tar.gz (100%) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (2.4 MB/2.4 MB - 561.2 kB)

21:46:45 (INFO) Renaming [vkd3d-proton-2.8-1-b7fb41b.tar.gz] to [vkd3d-proton-2.8-1-b7fb41b.tar.gz].
Traceback (most recent call last):
File "/usr/share/bottles/bottles/frontend/operation.py", line 96, in remove_task
self.window.page_details.btn_operations.set_visible(False)
AttributeError: 'MainWindow' object has no attribute 'page_details'
21:46:45 (INFO) Vkd3ds found:
- vkd3d-proton-2.8-1-b7fb41b

21:46:45 (INFO) Component installed: vkd3d vkd3d-proton-2.8-1-b7fb41b
21:46:45 (WARNING) No nvapi found.
21:46:46 (INFO) Installing component: [dxvk-nvapi-v0.6.2].
Traceback (most recent call last):
File "/usr/share/bottles/bottles/frontend/operation.py", line 81, in new_task
self.__tasks[task_id] = self.__new_widget(title, cancellable)
File "/usr/share/bottles/bottles/frontend/operation.py", line 77, in __new_widget
self.window.page_details.list_tasks.append(task_entry)
AttributeError: 'MainWindow' object has no attribute 'page_details'
dxvk-nvapi-v0.6.2.tar.gz (100%) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (2.5 MB/2.5 MB - 445.5 kB)

21:46:52 (INFO) Renaming [dxvk-nvapi-v0.6.2.tar.gz] to [dxvk-nvapi-v0.6.2.tar.gz].
Traceback (most recent call last):
File "/usr/share/bottles/bottles/frontend/operation.py", line 96, in remove_task
self.window.page_details.btn_operations.set_visible(False)
AttributeError: 'MainWindow' object has no attribute 'page_details'
21:46:52 (INFO) Nvapis found:
- dxvk-nvapi-v0.6.2

21:46:52 (INFO) Component installed: nvapi dxvk-nvapi-v0.6.2
21:46:52 (WARNING) No latencyflex found.
21:46:53 (INFO) Installing component: [latencyflex-v0.1.1].
Traceback (most recent call last):
File "/usr/share/bottles/bottles/frontend/operation.py", line 81, in new_task
self.__tasks[task_id] = self.__new_widget(title, cancellable)
File "/usr/share/bottles/bottles/frontend/operation.py", line 77, in __new_widget
self.window.page_details.list_tasks.append(task_entry)
AttributeError: 'MainWindow' object has no attribute 'page_details'
latencyflex-v0.1.1.tar.xz (100%) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (380.9 kB/380.9 kB - 350.7 kB)

21:46:55 (INFO) Renaming [latencyflex-v0.1.1.tar.xz] to [latencyflex-v0.1.1.tar.xz].
Traceback (most recent call last):
File "/usr/share/bottles/bottles/frontend/operation.py", line 96, in remove_task
self.window.page_details.btn_operations.set_visible(False)
AttributeError: 'MainWindow' object has no attribute 'page_details'
21:46:55 (INFO) Component installed: latencyflex latencyflex-v0.1.1
21:46:56 (WARNING) No runtime found.
21:46:56 (INFO) Installing component: [runtime-0.6].
Traceback (most recent call last):
File "/usr/share/bottles/bottles/frontend/operation.py", line 81, in new_task
self.__tasks[task_id] = self.__new_widget(title, cancellable)
File "/usr/share/bottles/bottles/frontend/operation.py", line 77, in __new_widget
self.window.page_details.list_tasks.append(task_entry)
AttributeError: 'MainWindow' object has no attribute 'page_details'
runtime.tar.gz (100%) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (17.0 MB/17.0 MB - 436.4 kB)

21:47:36 (INFO) Renaming [runtime.tar.gz] to [runtime.tar.gz].
Traceback (most recent call last):
File "/usr/share/bottles/bottles/frontend/operation.py", line 96, in remove_task
self.window.page_details.btn_operations.set_visible(False)
AttributeError: 'MainWindow' object has no attribute 'page_details'
21:47:37 (INFO) Component installed: runtime runtime-0.6
21:47:37 (WARNING) No WineBridge found.
21:47:38 (INFO) Installing component: [winebridge-1.1.0].
Traceback (most recent call last):
File "/usr/share/bottles/bottles/frontend/operation.py", line 81, in new_task
self.__tasks[task_id] = self.__new_widget(title, cancellable)
File "/usr/share/bottles/bottles/frontend/operation.py", line 77, in __new_widget
self.window.page_details.list_tasks.append(task_entry)
AttributeError: 'MainWindow' object has no attribute 'page_details'
WineBridge-eb78a75.tar.xz (100%) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (3.4 MB/3.4 MB - 353.3 kB)

21:47:48 (INFO) Renaming [WineBridge-eb78a75.tar.xz] to [WineBridge-eb78a75.tar.xz].
Traceback (most recent call last):
File "/usr/share/bottles/bottles/frontend/operation.py", line 96, in remove_task
self.window.page_details.btn_operations.set_visible(False)
AttributeError: 'MainWindow' object has no attribute 'page_details'
21:47:49 (INFO) Component installed: winebridge winebridge-1.1.0
21:47:49 (WARNING) No managed runners found.
21:47:50 (INFO) Installing component: [soda-7.0-9].
Traceback (most recent call last):
File "/usr/share/bottles/bottles/frontend/operation.py", line 81, in new_task
self.__tasks[task_id] = self.__new_widget(title, cancellable)
File "/usr/share/bottles/bottles/frontend/operation.py", line 77, in __new_widget
self.window.page_details.list_tasks.append(task_entry)
AttributeError: 'MainWindow' object has no attribute 'page_details'
soda-7.0-9-x86_64.tar.xz (100%) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (64.4 MB/64.4 MB - 601.0 kB)

21:49:38 (INFO) Renaming [soda-7.0-9-x86_64.tar.xz] to [soda-7.0-9-x86_64.tar.xz].
Traceback (most recent call last):
File "/usr/share/bottles/bottles/frontend/operation.py", line 96, in remove_task
self.window.page_details.btn_operations.set_visible(False)
AttributeError: 'MainWindow' object has no attribute 'page_details'
21:49:49 (INFO) Runners found:
- soda-7.0-9

21:49:49 (INFO) Component installed: runner soda-7.0-9
```

**Comment by jannuary** [comment]
That's not a similar problem at all - you're getting it because of a problem in PyGobject having a breaking change on new GTK (while we still use the current GTK version in the only maintained package, which is Flatpak.)
