### ISSUE TITLE
[Bug]: running any executables that isnt programs menu causes this error[the executables work in wine]

### ISSUE THREAD

**Issue by dr-nemesis-96** [bottlesdevs/Bottles#2446]
### Describe the bug

yep any executables ran from 
![image](https://user-images.githubusercontent.com/103036804/209608872-e07e8dac-1789-4987-bdbc-ef876e4487d8.png)
doesnt launch
for example i use cheat engine for getting unlimited stuff in offline games 
https://www.cheatengine.org/downloads.php
(note it works with wine/proton when run from terminal)

### To Reproduce

1. open bottles
2. browse files, and place a executable in c folder
3. then run that executable(for example cheatengine installer)
4. the executable doesnt launch, the terminal gets the error logs

### Package

Flatpak from Flathub

### Distribution

Arch linux, Void linux , Pop os

### Troubleshooting Logs

```shell
Traceback (most recent call last):
  File "/app/share/bottles/bottles/frontend/views/bottle_details.py", line 330, in update_programs
    process_programs()
  File "/app/share/bottles/bottles/frontend/views/bottle_details.py", line 311, in process_programs
    wineserver_status = WineServer(self.config).is_alive()
  File "/app/share/bottles/bottles/backend/wine/wineserver.py", line 24, in is_alive
    if not config.get("Runner"):
AttributeError: 'Result' object has no attribute 'get'
```

**Comment by dr-nemesis-96** [comment]
![image](https://user-images.githubusercontent.com/103036804/209609558-6041dd4c-6529-45a6-bef4-6abc5f48efee.png)
works
when i run like this
WINEPREFIX=/$HOME/.var/app/com.usebottles.bottles/data/bottles/bottles/gamingx/ wine '/home/desync/.var/app/com.usebottles.bottles/data/bottles/bottles/gamingx/drive_c/CheatEngine74.exe'

**Comment by dr-nemesis-96** [comment]
oh it seems the issue is fixed in the beta version.........

**Comment by dr-nemesis-96** [comment]
oh not fixed, it gets another error
TypeError: BottleView.do_update_programs() takes from 1 to 2 positional arguments but 3 were given
lol

**Comment by Kinsteen** [comment]
Are you using the latest version from Flatpak? All the other versions are not official and we can't really help you if you don't

**Comment by dr-nemesis-96** [comment]
@Kinsteen i am using it from flatpak

**Comment by Kinsteen** [comment]
@dr-nemesis-96 Can you send the full log of your latest error please?

**Comment by dr-nemesis-96** [comment]
![image](https://user-images.githubusercontent.com/103036804/209661483-8e3978ac-9c75-45e2-a94c-289a1e3a0b7e.png)
![image](https://user-images.githubusercontent.com/103036804/209661558-24211507-36c4-4160-8af6-e75bc2d89b16.png)
https://pastebin.com/t9HujTnu

here @Kinsteen

**Comment by dr-nemesis-96** [comment]
https://pastebin.com/t9HujTnu
@Kinsteen 
![image](https://user-images.githubusercontent.com/103036804/209662017-4d56d78e-2447-4db5-bd16-52ba9dbdbd46.png)
![image](https://user-images.githubusercontent.com/103036804/209662060-4d0e084f-b93e-422e-9c0d-247211331f44.png)

**Comment by Kinsteen** [comment]
The error you're getting is not related to the program not running. I tested on my machine and it works properly. Can you try to disable Gamemode?

**Comment by dr-nemesis-96** [comment]
![image](https://user-images.githubusercontent.com/103036804/209662247-58651e2b-f64e-4298-b202-dfcd34e620e6.png)
@Kinsteen 
well, i tested in multiple os's too, and cheat engine installer runs in wine/wine-ge, i think it should work in bottles too

**Comment by dr-nemesis-96** [comment]
@Kinsteen https://www.cheatengine.org/
lets see if it is related to cheat engine installer
please check if it works or throws same error in your pc

**Comment by Kinsteen** [comment]
Okay so: the error you're getting is a bug, it just makes the bottle temporarily broken when exiting a program. To fix it, just close and re-open the bottle.

The error you sent me right now is happening because you ran a program, it crashed and you tried to reopen another program which will not work either way.

I agree that it should work in Bottles too.

Please restart Bottles each time you test something please.


> please check if it works or throws same error in your pc

It works on my pc

**Comment by dr-nemesis-96** [comment]
https://pastebin.com/UvZLvC6f
ok the last run i had not run anything but the installer
just to be sure i ran it again
same issue

for what it is worth i had the exact same issue before moving to void linux,
same in arch linux and other distros i tried

you also have the flatpak version too? or the development version?

**Comment by Kinsteen** [comment]
Which version of Wine and DXVK are you using? I'm on dev version but it shouldn't have any impact

**Comment by dr-nemesis-96** [comment]
![image](https://user-images.githubusercontent.com/103036804/209664196-73c69cf6-b277-4024-b3f9-1170c430f438.png)


i use proton cuz i need it for games
the issue isnt proton specific
i tried with soda with the same result

**Comment by Kinsteen** [comment]
Try using dxvk-2.0, and disabling FSR, post-processing effects and "monitor performance" please

**Comment by dr-nemesis-96** [comment]
@Kinsteen 
![image](https://user-images.githubusercontent.com/103036804/209664297-a5a6749a-de7e-48b0-8c26-88d305e95538.png)
![image](https://user-images.githubusercontent.com/103036804/209664353-e27caf2c-d259-48ef-97f7-2c3f39510528.png)

there is a chance it may be related to this

**Comment by Kinsteen** [comment]
Okay create a new clean bottle with the gaming environment and try again, you seem to have modified a lot of settings that could break stuff

**Comment by dr-nemesis-96** [comment]
![image](https://user-images.githubusercontent.com/103036804/209664808-f3854524-3a85-4dbc-9c74-1341a946b70c.png)
![image](https://user-images.githubusercontent.com/103036804/209664856-31bbadf5-4f14-4911-a37a-e23f60bdebbe.png)

 damn it i keep getting same error

**Comment by Kinsteen** [comment]
Can you create an env variable in the bottle name `WINEDEBUG`, with the value `warn+all` and launch the program, and use pastebin to send the logs please

**Comment by dr-nemesis-96** [comment]
https://pastebin.com/iiMWXaTV
@Kinsteen

**Comment by Kinsteen** [comment]
I don't think this is applied correctly, you should use the Bottles way:
![Screenshot_20221227_132043](https://user-images.githubusercontent.com/5410562/209665958-2f408dd5-2799-422d-80c4-f264f36d24dd.png)

**Comment by dr-nemesis-96** [comment]
![image](https://user-images.githubusercontent.com/103036804/209666251-98eb685e-4085-49c7-a2f0-4c179e4001ee.png)
![image](https://user-images.githubusercontent.com/103036804/209666523-d0de732e-5c5f-4568-bc93-7413cbd7c196.png)

https://pastebin.com/XhN5jrwE

note it was ran with all the default settings and wine server was soda7.0-8

**Comment by Kinsteen** [comment]
Everything seems normal, I'm not sure what's wrong. There's no error of logs related to a program crash or anything, so I don't think I can help you here, sorry

**Comment by dr-nemesis-96** [comment]
@Kinsteen 
![image](https://user-images.githubusercontent.com/103036804/209674993-eeed3b3c-ae0d-41b7-81cf-e35294b93404.png)
i even made a vm to test out, same error man...........
perhaps you need to try it out in a vm?
or i can give you the hard disk in the vm i used

the vm was of endavour os

**Comment by dr-nemesis-96** [comment]
is it possible you are using different version?
![image](https://user-images.githubusercontent.com/103036804/209675506-8a10cadd-8dd4-457b-8faa-53b18f07f5d5.png)

it was the lattest from flatpak

**Comment by Kinsteen** [comment]
I am using this version, and it works with every parameter I throw at it. Yours doesn't work only on Bottles, but it seems such an edge case that I don't think it's worth to look into, plus the fact that there is literally no logs about the crash or why it doesn't work, sorry

**Comment by adworacz** [comment]
I just started receiving this error as well, after running a flatpack update to get the latest version. 

My logs:
```
(bottles:2): Gtk-CRITICAL **: 14:07:54.295: gtk_widget_set_parent: assertion '_gtk_widget_get_parent (widget) == NULL' failed
14:07:54 (INFO) Library saved

(bottles:2): Gtk-CRITICAL **: 14:08:01.849: gtk_box_append: assertion 'gtk_widget_get_parent (child) == NULL' failed
14:08:04 (INFO) Launching an executable…
14:08:04 (INFO) Using EasyAntiCheat runtime
14:08:04 (INFO) Using BattlEye runtime
Traceback (most recent call last):
  File "/app/share/bottles/bottles/frontend/views/bottle_details.py", line 330, in update_programs
    process_programs()
  File "/app/share/bottles/bottles/frontend/views/bottle_details.py", line 311, in process_programs
    wineserver_status = WineServer(self.config).is_alive()
  File "/app/share/bottles/bottles/backend/wine/wineserver.py", line 24, in is_alive
    if not config.get("Runner"):
AttributeError: 'Result' object has no attribute 'get'
```

This is with version `2022.12.14.1`.

My existing bottles seem to be working fine. But when I created a new bottle, and tried run an exe setup/installer, this error occurs and the installer never seems to run.

This is with `vaniglia-7.18`, all running in Flatpak.

**Comment by Kinsteen** [comment]
This error is not very important, as it doesn't break anything. It will be fixed in the next release, but for now, exiting and re-opening the bottle fixes temporarily the problem

**Comment by adworacz** [comment]
Hmm, I've tried exiting and reopening both the bottle and Bottles several times with no changes.

I'm trying to run an installer for iZotope RX.

**Comment by Kinsteen** [comment]
This error has nothing to do with the program not running I'm afraid. It happens when the program stops, cleanly or not.

I'll have a look at your program later!

**Comment by adworacz** [comment]
Gotcha. I'll continue to investigate my program's running issues then. I figured this was the cause as it was the obvious error.

Thanks for your help. I'll post back if I continue to have issues (or at least have more logs).

**Comment by dr-nemesis-96** [comment]
@adworacz is it with all executables?
or just with this one?
some apps work just fine
perhaps try running cheatengine installer ??
it works fine with wine

**Comment by mirkobrombin** [comment]
I fixed the exception related to Bottles.
