### ISSUE TITLE
[Bug]: Launch With Terminal Error

### ISSUE THREAD

**Issue by har-nick** [bottlesdevs/Bottles#2452]
### Describe the bug

Tested with XCOM: Enemy Unknown.

Running the "Launch With Terminal" option does not launch the game.

### To Reproduce

Unsure how to reproduce. Have only found it to work with XCOM: Enemy Unknown.

### Package

Flatpak from Flathub

### Distribution

Arch Linux

### Troubleshooting Logs

```shell
Official Package: true
Version: 2022.12.14.1
Display:
    X.org: true
    X.org (port): :1
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.0.12-artix1-1
Distro:
    Name: GNOME
    Version: '43'
Disk:
    Total: 8337489920
    Free: 8337346560
RAM:
    MemTotal: 15.5GiB
    MemAvailable: 10.5GiB
Bottles_envs: null
```

### Additional context

<details>
<summary>
Outputted error:
</summary>

```
Traceback (most recent call last):
  File "/app/bin/easyterm.py", line 272, in do_command_line
    command = shlex.split(options.lookup_value("command").get_string())
  File "/usr/lib/python3.10/shlex.py", line 315, in split
    return list(lex)
  File "/usr/lib/python3.10/shlex.py", line 300, in __next__
    token = self.get_token()
  File "/usr/lib/python3.10/shlex.py", line 109, in get_token
    raw = self.read_token()
  File "/usr/lib/python3.10/shlex.py", line 191, in read_token
    raise ValueError("No closing quotation")
ValueError: No closing quotation
```

</details>

<details>
<summary>
Configuration File:
</summary>

```
Arch: win64
Creation_Date: '2022-12-22 02:14:55.709362'
Custom_Path: false
DLL_Overrides: {}
DXVK: dxvk-2.0-1-12901b5
Environment: Gaming
Environment_Variables: {}
External_Programs:
    83cbcb53-9b3b-4991-b66c-289ac2035d84:
        arguments: ''
        auto_discovered: true
        dxvk: true
        dxvk_nvapi: false
        executable: XCOMLauncher.exe
        folder: /games/XCOM---Enemy-Unknown/drive_c/GOG Games/XCOM Enemy Unknown/XEW/Binaries/Win32
        fsr: false
        icon: com.usebottles.bottles-program
        id: 83cbcb53-9b3b-4991-b66c-289ac2035d84
        name: XCOMLauncher
        path: C:\GOG Games\XCOM Enemy Unknown\XEW\Binaries\Win32\XCOMLauncher.exe
        pulseaudio_latency: false
        removed: true
        script: ''
        virtual_desktop: false
        vkd3d: false
    e2566457-1ce8-437e-a8fa-97f9021eac8c:
        arguments: ''
        dxvk: true
        dxvk_nvapi: false
        executable: XComGame.exe
        folder: /games/XCOM---Enemy-Unknown/drive_c/GOG Games/XCOM Enemy Unknown/Binaries/Win32
        fsr: false
        icon: com.usebottles.bottles-program
        id: e2566457-1ce8-437e-a8fa-97f9021eac8c
        name: XCom
        path: /games/XCOM---Enemy-Unknown/drive_c/GOG Games/XCOM Enemy Unknown/Binaries/Win32/XComGame.exe
        pulseaudio_latency: false
        removed: null
        script: null
        virtual_desktop: false
        vkd3d: false
Installed_Dependencies:
- d3dx9
- msls31
- arial32
- times32
- courie32
- d3dcompiler_43
- d3dcompiler_47
- mono
- vcredist2019
- vcredist2005
- vcredist2008
- vcredist2010
- vcredist2012
Language: sys
LatencyFleX: latencyflex-v0.1.1
NVAPI: dxvk-nvapi-v0.6
Name: XCOM - Enemy Unknown
Parameters:
    custom_dpi: 96
    decorated: true
    discrete_gpu: true
    dxvk: true
    dxvk_nvapi: false
    fixme_logs: false
    fsr: false
    fullscreen_capture: false
    gamemode: true
    gamescope: false
    gamescope_borderless: false
    gamescope_fps: 0
    gamescope_fps_no_focus: 0
    gamescope_fullscreen: true
    gamescope_game_height: 0
    gamescope_game_width: 0
    gamescope_scaling: false
    gamescope_window_height: 0
    gamescope_window_width: 0
    latencyflex: false
    mangohud: false
    mouse_warp: true
    obsvkc: false
    pulseaudio_latency: false
    renderer: gl
    sandbox: false
    sync: fsync
    take_focus: false
    use_be_runtime: true
    use_eac_runtime: true
    use_runtime: false
    use_steam_runtime: false
    versioning_automatic: false
    versioning_compression: true
    versioning_exclusion_patterns: false
    virtual_desktop: false
    virtual_desktop_res: 1280x720
    vkbasalt: false
    vkd3d: false
    vmtouch: true
    vmtouch_cache_cwd: false
Path: XCOM---Enemy-Unknown
Runner: soda-7.0-8
Sandbox:
    share_net: true
    share_sound: true
State: 0
Uninstallers: {}
Update_Date: '2022-12-28 02:09:08.325749'
VKD3D: vkd3d-proton-2.8
Versioning: false
Versioning_Exclusion_Patterns: []
Windows: win10
WorkingDir: ''
run_in_terminal: false
session_arguments: ''
```

</details>

**Comment by har-nick** [comment]
Issue is related to Preload File setting. My mistake.
