### ISSUE TITLE
[Bug]: Missing pathvalidate from Dependencies wiki

### ISSUE THREAD

**Issue by duarm** [bottlesdevs/Bottles#2572]
### Describe the bug

missing pathvalidate dependency from wiki, running without it results in 

```
Traceback (most recent call last):
  File "/usr/bin/bottles", line 43, in <module>
    from bottles.frontend import main
  File "/usr/share/bottles/bottles/frontend/main.py", line 37, in <module>
    from bottles.frontend.windows.main_window import MainWindow
  File "/usr/share/bottles/bottles/frontend/windows/main_window.py", line 34, in <module>
    from bottles.backend.managers.manager import Manager
  File "/usr/share/bottles/bottles/backend/managers/manager.py", line 33, in <module>
    import pathvalidate
ModuleNotFoundError: No module named 'pathvalidate'
```

**Comment by Kinsteen** [comment]
I'm guessing this is for the AUR. It has been added!

**Comment by duarm** [comment]
that was fast, thanks

**Comment by Yaksinikos** [comment]
Same issue again :')

**Comment by Kinsteen** [comment]
The wiki is up to date, the problem is from Bottles AUR so you can comment there if you have a problem
