### ISSUE TITLE
[Bug]: Unable to finish setup after reinstalling Bottles

### ISSUE THREAD

**Issue by k-l-o-n-d-i-k-e** [bottlesdevs/Bottles#2601]
### Describe the bug

I recently reinstalled Bottles. When i go through the setup process Bottles can't advance any further because it gets stuck. I tried the solution suggested in [this post](https://github.com/bottlesdevs/Bottles/issues/1902) but it didn't work. I also tried launching bottles from the cli but i cannot complete the setup either. 

### To Reproduce

Pre-requisites: Uninstall Bottles and delete the folder "com.usebottles.bottles" located on `/home/user/.var/app/`

1. Open Bottles
2. Go through the setup process and click on "Continue". The "Almost done" screen will never finish. 
3. Close Bottles
4. Open Bottles again
5. A crash report pop up will appear.

### Package

Flatpak from Flathub

### Distribution

Fedora 37 (KDE)

### Debugging Information

```shell
Unable to get debugging information because when the setup screen appears the hamburguer menu is grayed out.
```

### Troubleshooting Logs

```shell
(process:2): Gtk-WARNING **: 10:12:35.519: Locale not supported by C library.
        Using the fallback 'C' locale.

(process:2): Gtk-WARNING **: 10:12:45.297: Theme directory 64/devices of theme Gruvbox has no size field

10:12:45 (INFO) Bottles Started! 

(bottles:2): Gtk-WARNING **: 10:12:45.604: Theme directory 64/devices of theme Gruvbox has no size field

10:12:52 (INFO) Performing Bottles checks\u2026 
10:12:52 (INFO) Runners found:
         - sys-wine-7.0.1
 

(bottles:2): Gtk-CRITICAL **: 10:12:52.771: gtk_widget_set_parent: assertion '_gtk_widget_get_parent (widget) == NULL' failed
10:12:52 (INFO) Library saved 
10:12:53 (INFO) Catalog installers loaded 
10:12:53 (INFO) Catalog dependencies loaded 
10:12:53 (INFO) Catalog components loaded 
10:13:06 (INFO) Performing Bottles checks\u2026 
10:13:06 (WARNING) No dxvk found. 
10:13:07 (INFO) Installing component: [dxvk-2.0-1-d020f44]. 
10:13:07 (WARNING) File [dxvk-2.0-1-d020f44.tar.gz] already exists in temp, skipping. 
10:13:07 (ERROR) Downloaded file [dxvk-2.0-1-d020f44.tar.gz] looks corrupted. 
10:13:07 (ERROR) Source cksum: [d2f640c5a3239e8d374c15ea59a5eb92] downloaded: [cc60293acafe688487b14790647946ed] 
10:13:07 (ERROR) Removing corrupted file [dxvk-2.0-1-d020f44.tar.gz]. 
10:13:07 (WARNING) No vkd3d found. 
10:13:09 (INFO) Installing component: [vkd3d-proton-2.8-1-f09e31a]. 
vkd3d-proton-2.8-1-f09e31a.tar.gz (1%)  (47.1�kB/2.4�MB - 74.9�kB)10:13:10 (ERROR) Error while running async job: <bound method Manager.checks of <bottles.backend.managers.manager.Manager object at 0x7fae004437c0>>
        Exception: 'latin-1' codec can't encode character '\u2501' in position 49: ordinal not in range(256)
 
  File "/app/share/bottles/bottles/frontend/utils/threading.py", line 61, in __target
    result = self.task_func(*args, **kwargs)
  File "/app/share/bottles/bottles/backend/managers/manager.py", line 163, in checks
    self.check_vkd3d(install_latest) or rv.set_status(False)
  File "/app/share/bottles/bottles/backend/managers/manager.py", line 471, in check_vkd3d
    res = self.__check_component("vkd3d", install_latest)
  File "/app/share/bottles/bottles/backend/managers/manager.py", line 537, in __check_component
    self.component_manager.install(component_type, component_version)
  File "/app/share/bottles/bottles/backend/utils/decorators.py", line 74, in wrapper
    rv = func(*args, **kwargs)
  File "/app/share/bottles/bottles/backend/managers/component.py", line 345, in install
    res = self.download(
  File "/app/share/bottles/bottles/backend/managers/component.py", line 222, in download
    ).download()
  File "/app/share/bottles/bottles/backend/downloader.py", line 75, in download
    self.__progress(count, block_size, total_size)
  File "/app/share/bottles/bottles/backend/downloader.py", line 113, in __progress
    print(
Traceback (most recent call last):
  File "/app/share/bottles/bottles/frontend/windows/onboard.py", line 116, in set_completed
    if result.status:
AttributeError: 'NoneType' object has no attribute 'status'
```

### Additional context

- I installed the latest version of Bottles 50.2

**Comment by Kinsteen** [comment]
Hey, what locale are you using on your system? It seems like you have a problem right at the start of it: `Locale not supported by C library.`

**Comment by k-l-o-n-d-i-k-e** [comment]
The locale on my system is set to british english. 
This is the output of  localectl status:
` System Locale: LANG=en_GB.UTF-8`

**Comment by Kinsteen** [comment]
It seems like your locales are not properly generated, and is a problem on your side unfortunately
