### ISSUE TITLE
[Bug]: Not functional on GNOME 44.beta

### ISSUE THREAD

**Issue by emansom** [bottlesdevs/Bottles#2699]
### Describe the bug

Opening up Bottles on GNOME 44.beta errors out.

### To Reproduce

1. Install GNOME 44.beta using [FCGU](https://codeberg.org/fabiscafe/fcgu)
2. Open up Bottles
3. Observe it crashing

### Package

Flatpak from Flathub

### Distribution

AUR -git package, Arch Linux

### Debugging Information

```shell
Can't access it.
```

### Troubleshooting Logs

```shell
Traceback (most recent call last):
  File "/usr/share/bottles/bottles/frontend/windows/main_window.py", line 149, in set_manager
    self.page_details = DetailsView(self)
  File "/usr/share/bottles/bottles/frontend/views/details.py", line 78, in __init__
    self.view_bottle = BottleView(self, config)
  File "/usr/share/bottles/bottles/frontend/views/bottle_details.py", line 163, in __init__
    self.style_provider.load_from_data(b".dragndrop_overlay { background: rgba(41, 65, 94, 0.2);}")
TypeError: Gtk.CssProvider.load_from_data() takes exactly 3 arguments (2 given)
```
```


### Additional context

_No response_

**Comment by TheEvilSkeleton** [comment]
Can you try the flatpak from Flathub?

**Comment by jannuary** [comment]
Eventually we will have to fix this, but for now — we cannot offer support for a package not maintained by us on pre-release software.

**Comment by darkblaze69** [comment]
I have the same error with GNOME 44rc from arch/fcgu repo and bottles from AUR, i.e.

```
Traceback (most recent call last):
  File "/usr/share/bottles/bottles/frontend/windows/main_window.py", line 149, in set_manager
    self.page_details = DetailsView(self)
  File "/usr/share/bottles/bottles/frontend/views/details.py", line 78, in __init__
    self.view_bottle = BottleView(self, config)
  File "/usr/share/bottles/bottles/frontend/views/bottle_details.py", line 163, in __init__
    self.style_provider.load_from_data(b".dragndrop_overlay { background: rgba(41, 65, 94, 0.2);}")
TypeError: Gtk.CssProvider.load_from_data() takes exactly 3 arguments (2 given)
```

My problem gone when I commented out that line 163:

`self.style_provider.load_from_data(b".dragndrop_overlay { background: rgba(41, 65, 94, 0.2);}")`

No issues since that. Hope this helps.
