### ISSUE TITLE
[Bug]: Error while adding Steam shortcut 

### ISSUE THREAD

**Issue by kryotek777** [bottlesdevs/Bottles#2706]
### Describe the bug

Adding a Steam shortcut for a bottle program has no effect, shows an error message after restarting bottles.

`SteamManager.add_shortcut() missing 1 required positional argument: 'program_path'`

### To Reproduce

1. Open a bottle
2. Add a Steam shortcut for a program
3. Restart bottles

### Package

Flatpak from Flathub

### Distribution

Arch Linux

### Debugging Information

```shell
Official Package: true
Version: '51.0'
DE/WM: plasma
Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.1.12-zen1-1-zen
Disk:
    Total: 16788185088
    Free: 16788037632
RAM:
    MemTotal: 31.3GiB
    MemAvailable: 26.6GiB
Bottles_envs: null
```

### Troubleshooting Logs

```shell
23:09:48 (INFO) Bottles Started! 
23:10:02 (INFO) Performing Bottles checks… 
23:10:02 (INFO) Dxvks found:
         - dxvk-1.10.3
         - dxvk-2.0-1-12901b5
 
23:10:02 (INFO) Vkd3ds found:
         - vkd3d-proton-2.6-1-5b73139
         - vkd3d-proton-2.8
 
23:10:02 (INFO) Nvapis found:
         - dxvk-nvapi-v0.5.4
 
23:10:02 (INFO) Latencyflexs found:
         - latencyflex-v0.1.0
         - latencyflex-v0.1.1
 
23:10:02 (INFO) Runners found:
         - soda-7.0-8
         - soda-7.0-3
         - caffe-7.20
         - vaniglia-7.18
         - lutris-GE-Proton7-35
         - lutris-7.2-2
         - wine-ge-proton7-35
         - wine-ge-7-28
         - GE-Proton7-33
         - sys-wine-8.0
 
23:10:02 (INFO) Bottles found:
         - Lego Star Wars II
 
23:10:02 (INFO) Catalog installers loaded 
23:10:03 (INFO) Catalog dependencies loaded 
23:10:09 (INFO) Setting Key use_steam_runtime=True for bottle Lego Star Wars II… 
23:10:09 (INFO) Setting Key sync=esync for bottle Lego Star Wars II… 
23:10:09 (INFO) There is no running wineserver. 
23:10:11 (ERROR) Error while running async job: <bound method SteamManager.add_shortcut of <bottles.backend.managers.steam.SteamManager object at 0x7f285d517f70>>
        Exception: SteamManager.add_shortcut() missing 1 required positional argument: 'program_path'
 
  File "/app/share/bottles/bottles/frontend/utils/threading.py", line 61, in __target
    result = self.task_func(*args, **kwargs)
Traceback (most recent call last):
  File "/app/share/bottles/bottles/frontend/widgets/program.py", line 326, in update
    if result.status:
AttributeError: 'NoneType' object has no attribute 'status'
23:10:12 (INFO) Catalog components loaded
```

**Comment by TheEvilSkeleton** [comment]
I can reproduce it on my end.

**Comment by BrianTM798** [comment]
Same problem.... issue....

**Comment by gel-mashup** [comment]
I thought this was gonna be fixed on the next release. they said it weeks ago.. new release up 4hours ago and the bug is still there.

**Comment by kryotek777** [comment]
> I thought this was gonna be fixed on the next release. they said it weeks ago.. new release up 4hours ago and the bug is still there.

Actually it seems to be a different issue, in the previous release the error message was "binary mode doesn't take an errors argument" IIRC

**Comment by kryotek777** [comment]
@cchrkk 

You replied to an already closed issue, please open a new issue and follow all the reporting instructions.
