### ISSUE TITLE
[Bug]: Patool broken path with double directory name while installing d3dx9 dependency

### ISSUE THREAD

**Issue by otuva** [bottlesdevs/Bottles#2719]
### Describe the bug

Whilst installing the dependency 'd3dx9' directory path is used twice and unable to install.

### To Reproduce

1. Go to dependencies
2. Try installing d3dx9

### Package

Flatpak from Flathub

### Distribution

Arch Linux

### Debugging Information

```shell
Official Package: true
Version: '51.0'
DE/WM: gnome
Display:
    X.org: true
    X.org (port): :1
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
            nvngx_path: /usr/lib/x86_64-linux-gnu/GL/nvidia-525-89-02/extra/nvidia/wine
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.1.12-arch1-1
Disk:
    Total: 8339464192
    Free: 8339300352
RAM:
    MemTotal: 15.5GiB
    MemAvailable: 8.0GiB
Bottles_envs: null
```

### Troubleshooting Logs

```shell
16:17:19 (INFO) Catalog dependencies loaded 
16:17:19 (INFO) Catalog installers loaded 
16:17:19 (INFO) Catalog components loaded 
16:17:20 (INFO) Setting Key sync=esync for bottle Gaming… 
16:17:20 (INFO) There is no running wineserver. 
16:17:29 (INFO) Installing dependency [d3dx9] in bottle [Gaming]. 
16:17:29 (WARNING) File [d3dx9.tar.xz] already exists in temp, skipping. 
patool: Extracting /home/tfp/.var/app/com.usebottles.bottles/data/bottles/temp/d3dx9.tar.xz ...
patool: running /usr/bin/tar --extract --use-compress-program xz --file /home/tfp/.var/app/com.usebottles.bottles/data/bottles/temp/d3dx9.tar.xz --directory /home/tfp/.var/app/com.usebottles.bottles/data/bottles/temp/d3dx9.tar
patool: ... /home/tfp/.var/app/com.usebottles.bottles/data/bottles/temp/d3dx9.tar.xz extracted to `/home/tfp/.var/app/com.usebottles.bottles/data/bottles/temp/d3dx9.tar'.
16:17:31 (ERROR) Something wrong happened during extraction. 
16:17:31 (ERROR) file `/home/tfp/.var/app/com.usebottles.bottles/data/bottles/temp/d3dx9.tar/d3dx9.tar' was not found 
16:17:31 (ERROR) Traceback (most recent call last):
	  File "/app/share/bottles/bottles/backend/managers/dependency.py", line 514, in __step_archive_extract
	    patoolib.extract_archive(tar_path, outdir=archive_path)
	  File "/app/lib/python3.10/site-packages/patoolib/__init__.py", line 681, in extract_archive
	    util.check_existing_filename(archive)
	  File "/app/lib/python3.10/site-packages/patoolib/util.py", line 398, in check_existing_filename
	    raise PatoolError("file `%s' was not found" % filename)
	patoolib.util.PatoolError: file `/home/tfp/.var/app/com.usebottles.bottles/data/bottles/temp/d3dx9.tar/d3dx9.tar' was not found
```

### Additional context

#2591

**Comment by keenanweaver** [comment]
Same issue here for directplay, devenum, dmband, dmcompos, dmime, dmloader, dmscript, dmstyle, dsdmo, dsound, dswave, & l3codecx: https://github.com/bottlesdevs/dependencies/issues/155#issuecomment-1440619225

**Comment by Kinsteen** [comment]
@keenanweaver , can you try this build? https://github.com/bottlesdevs/Bottles/pull/2723
