### ISSUE TITLE
[Bug]: error installing d3dcompiler_43 and other dependencies...

### ISSUE THREAD

**Issue by Heus-Sueh** [bottlesdevs/Bottles#2727]
### Describe the bug

![Captura de tela de 2023-02-23 19 25 29](https://user-images.githubusercontent.com/98482469/221044630-18daf40a-4acb-4c09-90ee-60566e2d5728.png)
![Captura de tela de 2023-02-23 19 26 32](https://user-images.githubusercontent.com/98482469/221044788-7210feb0-29c2-42c6-9a24-b0693bd1fd39.png)

### To Reproduce

create a bottle from scratch custom and enable dxvk, vkd3d, gamemode and discrete graphics 

### Package

Flatpak from Flathub

### Distribution

Fedora Silveblue (Sodalite)

### Debugging Information

```shell
Official Package: true
Version: '51.0'
DE/WM: pantheon
Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
            nvngx_path: /usr/lib/x86_64-linux-gnu/GL/nvidia-525-89-02/extra/nvidia/wine
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.1.12-200.fc37.x86_64
Disk:
    Total: 8348078080
    Free: 8347918336
RAM:
    MemTotal: 15.5GiB
    MemAvailable: 11.1GiB
Bottles_envs: null
```

### Troubleshooting Logs

```shell
❯ flatpak run com.usebottles.bottles
19:10:05 (INFO) Bottles Started! 
19:10:08 (INFO) Performing Bottles checks… 
19:10:08 (INFO) Dxvks found:
	 - dxvk-2.1-1-0811813
 
19:10:08 (INFO) Vkd3ds found:
	 - vkd3d-proton-2.8-1-08909d9
 
19:10:08 (INFO) Nvapis found:
	 - dxvk-nvapi-v0.6.1-1-0c54f06
 
19:10:08 (INFO) Latencyflexs found:
	 - latencyflex-v0.1.1
 
19:10:08 (INFO) Runners found:
	 - soda-7.0-9
	 - lutris-7.2-2
	 - wine-ge-proton7-37
	 - sys-wine-8.0
 
19:10:08 (INFO) Bottles found:
	 - Games
 
19:10:09 (INFO) Catalog dependencies loaded 
19:10:09 (INFO) Catalog installers loaded 
19:10:09 (INFO) Catalog components loaded 
19:16:56 (INFO) Setting Key sync=futex2 for bottle Games… 
19:16:56 (INFO) There is no running wineserver. 
19:17:04 (INFO) Installing dependency [d3dcompiler_43] in bottle [Games]. 
19:17:04 (WARNING) File [d3dx9.tar.xz] already exists in temp, skipping. 
patool: Extracting /var/home/heus/.var/app/com.usebottles.bottles/data/bottles/temp/d3dx9.tar.xz ...
patool: running /usr/bin/tar --extract --use-compress-program xz --file /var/home/heus/.var/app/com.usebottles.bottles/data/bottles/temp/d3dx9.tar.xz --directory /var/home/heus/.var/app/com.usebottles.bottles/data/bottles/temp/d3dx9.tar
patool: ... /var/home/heus/.var/app/com.usebottles.bottles/data/bottles/temp/d3dx9.tar.xz extracted to `/var/home/heus/.var/app/com.usebottles.bottles/data/bottles/temp/d3dx9.tar'.
19:17:06 (ERROR) Something wrong happened during extraction. 
19:17:06 (ERROR) file `/var/home/heus/.var/app/com.usebottles.bottles/data/bottles/temp/d3dx9.tar/d3dx9.tar' was not found 
19:17:06 (ERROR) Traceback (most recent call last):
	  File "/app/share/bottles/bottles/backend/managers/dependency.py", line 514, in __step_archive_extract
	    patoolib.extract_archive(tar_path, outdir=archive_path)
	  File "/app/lib/python3.10/site-packages/patoolib/__init__.py", line 681, in extract_archive
	    util.check_existing_filename(archive)
	  File "/app/lib/python3.10/site-packages/patoolib/util.py", line 398, in check_existing_filename
	    raise PatoolError("file `%s' was not found" % filename)
	patoolib.util.PatoolError: file `/var/home/heus/.var/app/com.usebottles.bottles/data/bottles/temp/d3dx9.tar/d3dx9.tar' was not found
	
 
19:17:11 (INFO) Installing dependency [d3dcompiler_47] in bottle [Games]. 
19:17:12 (WARNING) File [d3dx9.tar.xz] already exists in temp, skipping. 
patool: Extracting /var/home/heus/.var/app/com.usebottles.bottles/data/bottles/temp/d3dx9.tar.xz ...
patool: running /usr/bin/tar --extract --use-compress-program xz --file /var/home/heus/.var/app/com.usebottles.bottles/data/bottles/temp/d3dx9.tar.xz --directory /var/home/heus/.var/app/com.usebottles.bottles/data/bottles/temp/d3dx9.tar
patool: ... /var/home/heus/.var/app/com.usebottles.bottles/data/bottles/temp/d3dx9.tar.xz extracted to `/var/home/heus/.var/app/com.usebottles.bottles/data/bottles/temp/d3dx9.tar'.
19:17:13 (ERROR) Something wrong happened during extraction. 
19:17:13 (ERROR) file `/var/home/heus/.var/app/com.usebottles.bottles/data/bottles/temp/d3dx9.tar/d3dx9.tar' was not found 
19:17:13 (ERROR) Traceback (most recent call last):
	  File "/app/share/bottles/bottles/backend/managers/dependency.py", line 514, in __step_archive_extract
	    patoolib.extract_archive(tar_path, outdir=archive_path)
	  File "/app/lib/python3.10/site-packages/patoolib/__init__.py", line 681, in extract_archive
	    util.check_existing_filename(archive)
	  File "/app/lib/python3.10/site-packages/patoolib/util.py", line 398, in check_existing_filename
	    raise PatoolError("file `%s' was not found" % filename)
	patoolib.util.PatoolError: file `/var/home/heus/.var/app/com.usebottles.bottles/data/bottles/temp/d3dx9.tar/d3dx9.tar' was not found
	
 
19:17:18 (INFO) Installing dependency [d3dx11] in bottle [Games]. 
19:17:19 (WARNING) File [d3dx11.tar.xz] already exists in temp, skipping. 
patool: Extracting /var/home/heus/.var/app/com.usebottles.bottles/data/bottles/temp/d3dx11.tar.xz ...
patool: running /usr/bin/tar --extract --use-compress-program xz --file /var/home/heus/.var/app/com.usebottles.bottles/data/bottles/temp/d3dx11.tar.xz --directory /var/home/heus/.var/app/com.usebottles.bottles/data/bottles/temp/d3dx11.tar
patool: ... /var/home/heus/.var/app/com.usebottles.bottles/data/bottles/temp/d3dx11.tar.xz extracted to `/var/home/heus/.var/app/com.usebottles.bottles/data/bottles/temp/d3dx11.tar'.
19:17:19 (ERROR) Something wrong happened during extraction. 
19:17:19 (ERROR) file `/var/home/heus/.var/app/com.usebottles.bottles/data/bottles/temp/d3dx11.tar/d3dx11.tar' was not found 
19:17:19 (ERROR) Traceback (most recent call last):
	  File "/app/share/bottles/bottles/backend/managers/dependency.py", line 514, in __step_archive_extract
	    patoolib.extract_archive(tar_path, outdir=archive_path)
	  File "/app/lib/python3.10/site-packages/patoolib/__init__.py", line 681, in extract_archive
	    util.check_existing_filename(archive)
	  File "/app/lib/python3.10/site-packages/patoolib/util.py", line 398, in check_existing_filename
	    raise PatoolError("file `%s' was not found" % filename)
	patoolib.util.PatoolError: file `/var/home/heus/.var/app/com.usebottles.bottles/data/bottles/temp/d3dx11.tar/d3dx11.tar' was not found
```

### Additional context

in the snapshots it says it installed but I doubt it
![Captura de tela de 2023-02-23 19 32 52](https://user-images.githubusercontent.com/98482469/221045769-084dcb57-d28f-4e8d-afa4-10a40f9a6edd.png)

**Comment by Kinsteen** [comment]
Please update to 51.3, it will fix the problem!

**Comment by Heus-Sueh** [comment]
> Please update to 51.3, it will fix the problem!

sorry man I thought mine had already updated automatically :+1:
