### ISSUE TITLE
[Bug]: Not "startingish"

### ISSUE THREAD

**Issue by nPHYN1T3** [bottlesdevs/Bottles#2788]
### Describe the bug

Open Bottles UI loads in for far as the normal "Starting Up" message and the "always 3 files" thing it does but then that's it. So it starts...but doesn't.

```
bottles
15:22:33 (INFO) Bottles Started! 

(bottles:1523093): Gtk-CRITICAL **: 15:22:33.927: Unable to register the application: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
15:22:35 (INFO) Performing Bottles checks… 
15:22:35 (INFO) Dxvks found:
	 - dxvk-1.10.3
	 - dxvk-2.1
	 - dxvk-2.0-1-12901b5
 
15:22:35 (INFO) Vkd3ds found:
	 - vkd3d-proton-2.8
	 - vkd3d-proton-2.7
	 - vkd3d-proton-2.6
 
15:22:35 (INFO) Nvapis found:
	 - dxvk-nvapi-v0.5.4
	 - dxvk-nvapi-v0.5.3
	 - dxvk-nvapi-v0.6-1-0827efb
 
15:22:35 (INFO) Latencyflexs found:
	 - latencyflex-v0.1.1
	 - latencyflex-v0.1.0
 
15:22:35 (INFO) Runners found:
	 - caffe-7.20
	 - caffe-7.18
	 - caffe-7.10-1
	 - sys-wine-8.3
 
15:22:35 (WARNING) Migrating config key 'fsr_level' to 'fsr_sharpening_strength' 
15:22:35 (WARNING) Migrating config key 'fsr_level' to 'fsr_sharpening_strength' 
15:22:35 (WARNING) Migrating config key 'fsr_level' to 'fsr_sharpening_strength' 
15:22:35 (WARNING) Skipping unexpected config 'Latest_Executables' in BottleConfig 
15:22:35 (WARNING) Skipping unexpected config 'dxvk_hud' in BottleParams 
15:22:35 (INFO) Bottles found:
	 - bla
	 - bla
	 - bla
	 - bla
 
Traceback (most recent call last):
  File "/usr/share/bottles/bottles/frontend/windows/main_window.py", line 149, in set_manager
    self.page_details = DetailsView(self)
  File "/usr/share/bottles/bottles/frontend/views/details.py", line 78, in __init__
    self.view_bottle = BottleView(self, config)
  File "/usr/share/bottles/bottles/frontend/views/bottle_details.py", line 163, in __init__
    self.style_provider.load_from_data(b".dragndrop_overlay { background: rgba(41, 65, 94, 0.2);}")
TypeError: Gtk.CssProvider.load_from_data() takes exactly 3 arguments (2 given)
15:22:36 (INFO) Catalog dependencies loaded 
15:22:36 (INFO) Catalog components loaded 
15:22:36 (INFO) Catalog installers loaded 
```

### To Reproduce

Open Bottles
watch it open and never progress past the starting up

### Package

Flatpak from Flathub

### Distribution

Garuda Arch

### Debugging Information

```shell
Official Package: false
Version: '51.5'
DE/WM: null
Display:
    X.org: true
    X.org (port): :0.1
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/share/vulkan/icd.d/nvidia_icd.json
            nvngx_path: /usr/lib/nvidia/wine
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.2.2-arch1-1
Disk:
    Total: 249521000448
    Free: 232399101952
RAM:
    MemTotal: 62.7GiB
    MemAvailable: 48.2GiB
Bottles_envs: null
Tools and Libraries:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.37'
    icoextract: true
    pefile: true
    orjson: true
    markdown: true
    ImageMagick: true
    FVS: true
    xdpyinfo: true
```

**Comment by Kinsteen** [comment]
This is a problem with the AUR package which we don't support, check the AUR package comments to have a solution, or use the official package on Flathub

**Comment by nPHYN1T3** [comment]
Well if flathub is the only "official" method to use bottles I guess I'll find another solution. Thanks.

**Comment by Arrow-x** [comment]
Bottles doesn't support the latest gtk4 update yet so:
for now you can either downgrade gtk4 to 4.10
or change `/usr/share/bottles/bottles/frontend/views/bottle_details.py`
```python
self.style_provider.load_from_data(b".dragndrop_overlay { background: rgba(41, 65, 94, 0.2);}")
```
to 
```python
self.style_provider.load_from_data(".dragndrop_overlay { background: rgba(41, 65, 94, 0.2);}", -1)
```
credit to `gravechapa`  and `flxrbr` on the AUR site

**Comment by nPHYN1T3** [comment]
Thanks for the heads up. As for downgrading I wish gtk stopped at 2. ;) That line in the py did the trick so thanks again. I've been so laser focused on other things I didn't even think to check the AUR earlier.

**Comment by Arrow-x** [comment]
you are most welcome
