### ISSUE TITLE
[Bug]: Recipe does not apply to bottle creation ?

### ISSUE THREAD

**Issue by Hipokamp** [bottlesdevs/Bottles#2864]
### Describe the bug

Hello,

This small message to inform you of a bug that we seem to be and that we discuss on the Bottles forum.

When we want to create a new bottle with a recipe, nothing of the parameters of the recipe is taken into account for the creation of the new bottle. Neither the runner, nor the Windows version, nor the language... etc.

Also when we read the recipe script we don't see anywhere lines about the parameters of this wincfg for linking the desktop folders or the theme... etc. It seems to us that this could make a nice feature offering to include for future recipes. 

Thanks to you for your work. 
Here is the link to the forum discussion: https://forum.usebottles.com/t/recipes-not-working/969/6

### To Reproduce

1 - Save a recipe
2 - Recreate a bottle with it

### Package

Flatpak from Flathub

### Distribution

Linux Mint 21.1

### Debugging Information

```shell
~$ flatpak run --command=bottles-cli com.usebottles.bottles info health-check

Official Package: true
Version: '51.5'
DE/WM: cinnamon
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        intel:
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.i686.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.19.0-38-generic
Disk:
    Total: 1993158656
    Free: 1993011200
RAM:
    MemTotal: 3.7GiB
    MemAvailable: 2.2GiB
Bottles_envs: null
```

### Troubleshooting Logs

```shell
~$ flatpak run com.usebottles.bottles

15:47:25 (INFO) Bottles Started! 
15:47:25 (WARNING) Connection status: offline … 
15:47:25 (WARNING) Connection status: offline … 
15:47:25 (ERROR) Could not get index for dependencies repository: (6, 'Could not resolve host: proxy.usebottles.com') 
15:47:25 (ERROR) Could not get index for installers repository: (6, 'Could not resolve host: proxy.usebottles.com') 
15:47:25 (ERROR) Could not get index for components repository: (6, 'Could not resolve host: proxy.usebottles.com') 
15:47:25 (ERROR) Could not get index for dependencies repository 
15:47:25 (ERROR) Could not get index for components repository 
15:47:25 (ERROR) Could not get index for installers repository 
15:47:25 (INFO) Performing Bottles checks… 
15:47:25 (INFO) Dxvks found:
	 - dxvk-2.1
 
15:47:25 (INFO) Vkd3ds found:
	 - vkd3d-proton-2.8-1-08909d9
 
15:47:25 (INFO) Nvapis found:
	 - dxvk-nvapi-v0.6.1-1-0c54f06
 
15:47:25 (INFO) Latencyflexs found:
	 - latencyflex-v0.1.1
 
15:47:25 (INFO) Runners found:
	 - soda-7.0-9
	 - wine-7.0-4-proton-amd64
	 - sys-wine-8.0
 
15:47:25 (INFO) Temp directory cleaned successfully! 
15:47:25 (ERROR) Config file not exists 
Traceback (most recent call last):
  File "/app/share/bottles/bottles/backend/models/config.py", line 183, in load
    raise FileNotFoundError("Config file not exists")
FileNotFoundError: Config file not exists
15:47:25 (ERROR) Config file not exists 
Traceback (most recent call last):
  File "/app/share/bottles/bottles/backend/models/config.py", line 183, in load
    raise FileNotFoundError("Config file not exists")
FileNotFoundError: Config file not exists
15:47:25 (ERROR) Config file not exists 
Traceback (most recent call last):
  File "/app/share/bottles/bottles/backend/models/config.py", line 183, in load
    raise FileNotFoundError("Config file not exists")
FileNotFoundError: Config file not exists
15:47:25 (INFO) Bottles found:
	 - RADIOSURE
	 - PNOTES
 
15:47:25 (WARNING) Connection status: offline … 
15:47:25 (WARNING) Connection status: offline … 
15:47:25 (WARNING) Connection status: offline … 
15:47:25 (INFO) No installers found! 
15:47:25 (INFO) No components found. 
15:47:25 (INFO) No dependencies found!
```

**Comment by frlof** [comment]
Related #2793
