### ISSUE TITLE
stuck 

### ISSUE THREAD

**Issue by ALEX5402** [bottlesdevs/Bottles#2888]
### Describe the bug

when i try to open bottles it says this error

Traceback (most recent call last):
File "/usr/bin/bottles", line 40, in <module>
from bottles.frontend import main
File "/usr/share/bottles/bottles/frontend/main.py", line 37, in <module>
from bottles.frontend.windows.main_window import MainWindow
File "/usr/share/bottles/bottles/frontend/windows/main_window.py", line 42, in <module>
from bottles.frontend.views.details import DetailsView
File "/usr/share/bottles/bottles/frontend/views/details.py", line 32, in <module>
from bottles.frontend.views.bottle_preferences import PreferencesView
File "/usr/share/bottles/bottles/frontend/views/bottle_preferences.py", line 42, in <module>
from bottles.frontend.windows.vkbasalt import VkBasaltDialog
File "/usr/share/bottles/bottles/frontend/windows/vkbasalt.py", line 30, in <module>
from vkbasalt.lib import parse, ParseConfig
ModuleNotFoundError: No module named 'vkbasalt

### To Reproduce

1. launch bottles with terminal
2. then when it opening then close it from task manager forcefully 
3. after that it behave like this 
4. on arch based distro garuda linux 

### Package

Flatpak from Flathub

### Distribution

garuda linux

### Debugging Information

```shell
Traceback (most recent call last):
File "/usr/bin/bottles", line 40, in <module>
from bottles.frontend import main
File "/usr/share/bottles/bottles/frontend/main.py", line 37, in <module>
from bottles.frontend.windows.main_window import MainWindow
File "/usr/share/bottles/bottles/frontend/windows/main_window.py", line 42, in <module>
from bottles.frontend.views.details import DetailsView
File "/usr/share/bottles/bottles/frontend/views/details.py", line 32, in <module>
from bottles.frontend.views.bottle_preferences import PreferencesView
File "/usr/share/bottles/bottles/frontend/views/bottle_preferences.py", line 42, in <module>
from bottles.frontend.windows.vkbasalt import VkBasaltDialog
File "/usr/share/bottles/bottles/frontend/windows/vkbasalt.py", line 30, in <module>
from vkbasalt.lib import parse, ParseConfig
ModuleNotFoundError: No module named 'vkbasalt
```

### Additional context

it doesnot opening i am using zen kernel  with x11

**Comment by Kinsteen** [comment]
We do not support the AUR package, only the Flatpak. Report the issue on the AUR package
