### ISSUE TITLE
[Bug]: Regression: can't launch shortcut after "Change Launch Options"

### ISSUE THREAD

**Issue by SuperSamus** [bottlesdevs/Bottles#2897]
### Describe the bug

The "Change Launch Options" for shortcuts is bugged since Bottles 51.6: after saving (even if you didn't change anything), launching that shortcut will make it not launch.
This can be "solved" by returning to Bottle's main menu. The settings are now functional.

### To Reproduce

1. Have a Bottle and a shortcut in it
2. On the shortcut, "Change Launch Options...", and save
3. Try to launch that shortcut. Or to stop it. Or to "Change Launch Options..." again.

### Package

Flatpak from Flathub

### Distribution

NixOS 23.05 Unstable

### Debugging Information

```shell
Official Package: false
Version: '51.6'
DE/WM: /nix/store/dvi8avclq5fwz0lcn48ag787i5k2cbv5-desktops/share/wayland-sessions/plasmawayland
Display:
    X.org: true
    X.org (port): :1
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /run/opengl-driver/share/vulkan/icd.d/radeon_icd.x86_64.json:/run/opengl-driver-32/share/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.2.12-xanmod1
Disk:
    Total: 8016359424
    Free: 8016310272
RAM:
    MemTotal: 14.9GiB
    MemAvailable: 5.2GiB
Bottles_envs: null
Tools and Libraries:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.37'
    icoextract: true
    pefile: true
    orjson: true
    markdown: true
    ImageMagick: true
    FVS: true
    xdpyinfo: true
```

### Troubleshooting Logs

```shell
When attempting to save the launch options:

  File ".../bottles/frontend/widgets/program.py", line 202, in update_programs
    self.view_bottle.update_programs(config=self.config)
  File ".../bottles/frontend/views/bottle_details.py", line 287, in update_programs
    raise TypeError("config param need BottleConfig type, but it was %s" % type(config))
TypeError: config param need BottleConfig type, but it was <class 'str'>
```

When launching something after saving the launch options:
```
22:53:25 (ERROR) Error while running async job: <function ProgramEntry.run_executable.<locals>._run at 0x7fa834230670>
        Exception: 'str' object has no attribute 'Parameters'
 
  File ".../bottles/backend/utils/threading.py", line 59, in __target
    result = self.task_func(*args, **kwargs)
  File ".../bottles/frontend/widgets/program.py", line 180, in _run
    WineExecutor.run_program(self.config, self.program, with_terminal)
  File ".../bottles/backend/wine/executor.py", line 95, in run_program
    dxvk = config.Parameters.dxvk
Traceback (most recent call last):
  File ".../bottles/frontend/widgets/program.py", line 148, in __reset_buttons
    raise NotImplementedError("Invalid data type, expect bool or Result, but it was %s" % type(result))
NotImplementedError: Invalid data type, expect bool or Result, but it was <class 'NoneType'>
```

When trying to stop said shortcut:
```
Traceback (most recent call last):
  File ".../bottles/frontend/widgets/program.py", line 195, in stop_process
    winedbg = WineDbg(self.config)
  File ".../bottles/backend/wine/wineprogram.py", line 22, in __init__
    raise TypeError("config should be BottleConfig type, but it was %s" % type(config))
TypeError: config should be BottleConfig type, but it was <class 'str'>
```

When trying to open "Change Launch Options" again:
```
Traceback (most recent call last):
  File ".../bottles/frontend/widgets/program.py", line 134, in show_launch_options_view
    dialog = LaunchOptionsDialog(self, self.config, self.program)
  File ".../bottles/frontend/windows/launchoptions.py", line 85, in __init__
    config.Parameters.dxvk,
AttributeError: 'str' object has no attribute 'Parameters'
```
```


### Additional context

_No response_

**Comment by raaffaaeell** [comment]
Having this as well

**Comment by xioren** [comment]
Probably related to #2885
