### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by horu** [bottlesdevs/Bottles#2934]
### Describe the bug

error:

```
(process:2): Gtk-WARNING **: 09:58:46.574: Locale not supported by C library.
	Using the fallback 'C' locale.
09:58:46 (INFO) Bottles Started! 
09:58:48 (INFO) Performing Bottles checks… 
09:58:48 (INFO) Dxvks found:
	 - dxvk-1.10.3
	 - dxvk-async-2.0
	 - dxvk-2.1
	 - dxvk-2.2
	 - dxvk-2.2-1-8b6cbda
	 - dxvk-2.0
	 - dxvk-2.0-1-196fefe
 
09:58:48 (INFO) Vkd3ds found:
	 - vkd3d-proton-2.9
	 - vkd3d-proton-2.8-1-f09e31a
 
09:58:48 (INFO) Nvapis found:
	 - dxvk-nvapi-v0.6.3-1-cb61c3f
	 - dxvk-nvapi-v0.6
 
09:58:48 (INFO) Latencyflexs found:
	 - latencyflex-v0.1.1
 
09:58:48 (INFO) Runners found:
	 - soda-7.0-9
	 - caffe-7.20
	 - vaniglia-7.18
	 - lutris-ge-lol-8.7-1
	 - wine-ge-proton8-8
	 - w3c-6.19
	 - kron4ek-wine-8.9-staging-amd64
	 - GE-Proton8-4
	 - GE-Proton8-3
	 - GE-Proton7-50
	 - sys-wine-8.0
 
09:58:48 (WARNING) Illegal bottle folder or mismatch between config "Path" and folder name 
09:58:48 (INFO) Setting Key Path=nfs for bottle winXP… 
09:58:48 (WARNING) Illegal bottle folder or mismatch between config "Path" and folder name 
09:58:48 (INFO) Setting Key Path=win10 for bottle win10… 
09:58:48 (WARNING) Illegal bottle folder or mismatch between config "Path" and folder name 
09:58:48 (INFO) Setting Key Path=regular for bottle win10… 
09:58:48 (WARNING) Illegal bottle folder or mismatch between config "Path" and folder name 
09:58:48 (INFO) Setting Key Path=winXP for bottle winXP… 
09:58:48 (INFO) Bottles found:
	 - winXP
	 - win7
	 - win10
 
09:58:49 (INFO) Catalog dependencies loaded 
09:58:49 (INFO) Catalog installers loaded 
09:58:49 (INFO) Catalog components loaded 
09:58:50 (INFO) Setting Key sync=esync for bottle win10… 
09:58:50 (INFO) There is no running wineserver. 
09:59:07 (INFO) Setting Key 227aa259-b0bc-4a35-97c7-f1e070efe96b={'executable': 'steam.exe', 'arguments': '%command% -autoconfig', 'name': 'steam', 'path': 'C:\\Program Files (x86)\\Steam\\steam.exe', 'folder': '/home/anslyshik/.var/app/com.usebottles.bottles/data/bottles/bottles/regular/drive_c/Program Files (x86)/Steam', 'icon': 'com.usebottles.bottles-program', 'script': '', 'dxvk': True, 'vkd3d': True, 'dxvk_nvapi': False, 'fsr': False, 'pulseaudio_latency': False, 'virtual_desktop': False, 'removed': None, 'id': '227aa259-b0bc-4a35-97c7-f1e070efe96b'} for bottle win10… 
Traceback (most recent call last):
  File "/app/share/bottles/bottles/frontend/widgets/program.py", line 202, in update_programs
    self.view_bottle.update_programs(config=self.config)
  File "/app/share/bottles/bottles/frontend/views/bottle_details.py", line 287, in update_programs
    raise TypeError("config param need BottleConfig type, but it was %s" % type(config))
TypeError: config param need BottleConfig type, but it was <class 'str'>
```

### To Reproduce

1. Go to bottle
2. Tap to three dots of any program
3. Go to Change Launch Options
4. Change "Command Arguments" line
5. Save
Result: You can not run program and con not open program options.

### Package

Flatpak from Flathub

### Distribution

ubuntu 22

### Debugging Information

```shell
s
```

**Comment by mirkobrombin** [comment]
Closing all issues with no proper title.
