### ISSUE TITLE
[Bug]: Can't run .exe in bottles from the right-click menu

### ISSUE THREAD

**Issue by kacperpaczos** [bottlesdevs/Bottles#2946]
### Describe the bug

Can't run .exe in Bottles using the right-click menu.
![image](https://github.com/bottlesdevs/Bottles/assets/23406555/b9014a5e-eba2-4823-ace8-7e4355f09fc6)

I use LM 21.1, and i have an app notepad++ for example. I downloaded exe file, and want to run it in bottles using option from my right click menu in option.

When i click "run with bottles" nothing is do. 

### To Reproduce

1) Install and configure bottles.
2) Try to use the context menu to run the app in the bottle.

### Package

Flatpak from Flathub

### Distribution

Ubuntu 22.04/LM21.1

### Debugging Information

```shell
Official Package: true
Version: '51.6'
DE/WM: cinnamon
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        intel:
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.x86_64.json:/usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.i686.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.19.0-45-generic
Disk:
    Total: 8319107072
    Free: 8318947328
RAM:
    MemTotal: 15.5GiB
    MemAvailable: 1.4GiB
Bottles_envs: null
```

### Troubleshooting Logs

```shell
flatpak run com.usebottles.bottles npp.8.5.4.Installer.x64.exe
Invalid URI (syntax: bottles:run/<bottle>/<program>)
```

**Comment by mirkobrombin** [comment]
![image](https://github.com/bottlesdevs/Bottles/assets/9479903/fc4f36b7-3299-4699-801d-634743ffd107)
I am not able to replicate.

**Comment by diegoortizmatajira** [comment]
The issue occurs when the selected bottle name has spaces in it.

**Comment by sour-source** [comment]
still an issue with latest bottles and i finaly found the culprit.
Steps to reproduce:
Create new bottle then change its name to something different, ex. from 'games' to 'game2' opening from right click failed, but if change it back to 'games' it works again without issues!
So, for anyone wondering while this issue is solved by developer just create a new bottle and don't touch it's name, or rename it back to whatever it was before.

**Comment by KBD20** [comment]
This happened to me too but the Bottle name was unchanged and had no spaces - I tried doing it via terminal `bottles program.exe` and got:
```
Traceback (most recent call last):
  File "/usr/bin/bottles-cli", line 758, in <module>
    cli = CLI()
  File "/usr/bin/bottles-cli", line 236, in __init__
    self.__process_args()
    ~~~~~~~~~~~~~~~~~~~^^
  File "/usr/bin/bottles-cli", line 285, in __process_args
    self.run_program()
    ~~~~~~~~~~~~~~~~^^
  File "/usr/bin/bottles-cli", line 699, in run_program
    WineExecutor.run_program(bottle, program)
                                     ^^^^^^^
UnboundLocalError: cannot access local variable 'program' where it is not associated with a value
```

I remember a similar issue with an incorrect variable (I think rubyripper) and the fix was to edit the variable to be the new correct variable name (plural to singular)

**Comment by sour-source** [comment]
that is an entirely different problem that is already solved, wait for the new release https://github.com/bottlesdevs/Bottles/issues/3599
