### ISSUE TITLE
[Bug]: Programs not starting with `use_steam_runtime=true`

### ISSUE THREAD

**Issue by Mimea005** [bottlesdevs/Bottles#3051]
### Describe the bug

Trying to run any executable with a bottle that has `use_steam_runtime=true` fails.

### To Reproduce

1. Create a new bottle (i used the application preset when i tried to isolate the problem)
2. Go to Settings for the bottle and enable Steam Runtime
3. Try to start any windows executable with the bottle (The programs under the Tools section also fails)

### Package

Flatpak from Flathub

### Distribution

VanillaOS 22.10

### Debugging Information

```shell
Official Package: true
Version: '51.8'
DE/WM: gnome-wayland
Display:
    X.org: true
    X.org (port): :1
    Wayland: true
Graphics:
    vendors:
        nvidia: &amp;id002
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
            nvngx_path: /usr/lib/x86_64-linux-gnu/GL/nvidia-535-54-03/extra/nvidia/wine
        intel: &amp;id001
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.i686.json
    prime:
        integrated: *id001
        discrete: *id002
Kernel:
    Type: Linux
    Version: 5.19.0-46-generic
Disk:
    Total: 8289837056
    Free: 8289656832
RAM:
    MemTotal: 15.4GiB
    MemAvailable: 11.0GiB
Bottles_envs: null
```

### Troubleshooting Logs

```shell
❯ flatpak run com.usebottles.bottles
16:03:07 (INFO) Bottles Started! 
16:03:08 (INFO) Performing Bottles checks… 
16:03:08 (INFO) Dxvks found:
	 - dxvk-2.2
 
16:03:08 (INFO) Vkd3ds found:
	 - vkd3d-proton-2.9
 
16:03:08 (INFO) Nvapis found:
	 - dxvk-nvapi-v0.6.3
 
16:03:08 (INFO) Latencyflexs found:
	 - latencyflex-v0.1.1
 
16:03:08 (INFO) Runners found:
	 - soda-7.0-9
	 - sys-wine-8.0.2
 
16:03:08 (INFO) Bottles found:
	 - Vapor
 
16:03:08 (WARNING) A Steam prefix was found, but it is a Proton one: 1493710, skipping… 
16:03:08 (WARNING) A Steam prefix was found, but it is a Proton one: 2348590, skipping… 
16:03:08 (WARNING) A Steam prefix was found, but it is a Proton one: 2180100, skipping… 
16:03:08 (WARNING) A Steam prefix was found, but it is a Proton one: 1493710, skipping… 
16:03:08 (WARNING) A Steam prefix was found, but it is a Proton one: 2348590, skipping… 
16:03:08 (WARNING) A Steam prefix was found, but it is a Proton one: 2180100, skipping… 
Exception in thread Thread-11 (__target):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/app/share/bottles/bottles/backend/utils/threading.py", line 70, in __target
    self.callback(result, error)
  File "/app/share/bottles/bottles/frontend/views/bottle_taskmanager.py", line 110, in update_processes
    if len(processes) > 0:
TypeError: object of type 'NoneType' has no len()
16:03:08 (INFO) Catalog installers loaded 
16:03:08 (INFO) Catalog components loaded 
16:03:08 (INFO) Catalog dependencies loaded 
16:03:17 (INFO) Setting Key use_steam_runtime=True for bottle Vapor… 
16:03:21 (INFO) Launching an executable… 
16:03:21 (ERROR) Error while running async job: <function ProgramEntry.run_executable.<locals>._run at 0x7fcd6e06e200>
	Exception: argument of type 'NoneType' is not iterable
 
  File "/app/share/bottles/bottles/backend/utils/threading.py", line 59, in __target
    result = self.task_func(*args, **kwargs)
  File "/app/share/bottles/bottles/frontend/widgets/program.py", line 180, in _run
    WineExecutor.run_program(self.config, self.program, with_terminal)
  File "/app/share/bottles/bottles/backend/wine/executor.py", line 123, in run_program
    ).run()
  File "/app/share/bottles/bottles/backend/wine/executor.py", line 213, in run
    return self.__launch_with_bridge()
  File "/app/share/bottles/bottles/backend/wine/executor.py", line 244, in __launch_with_bridge
    return self.__launch_exe()
  File "/app/share/bottles/bottles/backend/wine/executor.py", line 265, in __launch_exe
    winecmd = WineCommand(
  File "/app/share/bottles/bottles/backend/wine/winecommand.py", line 103, in __init__
    self.command = self.get_cmd(command, post_script)
  File "/app/share/bottles/bottles/backend/wine/winecommand.py", line 509, in get_cmd
    if "sniper" in _rs.keys() and "sniper" in self.runner_runtime:
Traceback (most recent call last):
  File "/app/share/bottles/bottles/frontend/widgets/program.py", line 148, in __reset_buttons
    raise NotImplementedError("Invalid data type, expect bool or Result, but it was %s" % type(result))
NotImplementedError: Invalid data type, expect bool or Result, but it was <class 'NoneType'>
```

**Comment by koplo199** [comment]
#3049 Should fix the issue, thanks for the report.
