### ISSUE TITLE
[Bug]: NameError: name 'check_executable' is not defined

### ISSUE THREAD

**Issue by emansom** [bottlesdevs/Bottles#3108]
### Describe the bug

When launching Bottles from the CLI the following error pops up:

```shell
Traceback (most recent call last):
  File "/usr/share/bottles/bottles/frontend/main.py", line 187, in do_command_line
    self.do_activate()
  File "/usr/share/bottles/bottles/frontend/main.py", line 230, in do_activate
    win = MainWindow(
          ^^^^^^^^^^^
  File "/usr/share/bottles/bottles/frontend/windows/main_window.py", line 121, in __init__
    self.__on_start()
  File "/usr/share/bottles/bottles/frontend/windows/main_window.py", line 234, in __on_start
    self.check_core_deps()
  File "/usr/share/bottles/bottles/frontend/windows/main_window.py", line 349, in check_core_deps
    if "FLATPAK_ID" not in os.environ and not HealthChecker().has_core_deps():
                                              ^^^^^^^^^^^^^^^
  File "/usr/share/bottles/bottles/backend/health.py", line 72, in __init__
    self.cabextract = self.check_cabextract()
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/bottles/bottles/backend/health.py", line 112, in check_cabextract
    return check_executable("cabextract")
           ^^^^^^^^^^^^^^^^
NameError: name 'check_executable' is not defined
```

### To Reproduce

1. Build latest Bottles from git
2. Launch Bottles from CLI
3. Observe output

### Package

AUR bottles-git

### Distribution

Arch Linux

### Debugging Information

```shell
Can't. Crashes before health check output is shown.
```

### Troubleshooting Logs

```shell
Traceback (most recent call last):
  File "/usr/bin/bottles-cli", line 659, in <module>
    cli = CLI()
          ^^^^^
  File "/usr/bin/bottles-cli", line 150, in __init__
    self.__process_args()
  File "/usr/bin/bottles-cli", line 161, in __process_args
    self.show_info()
  File "/usr/bin/bottles-cli", line 220, in show_info
    hc = HealthChecker()
         ^^^^^^^^^^^^^^^
  File "/usr/share/bottles/bottles/backend/health.py", line 72, in __init__
    self.cabextract = self.check_cabextract()
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/bottles/bottles/backend/health.py", line 112, in check_cabextract
    return check_executable("cabextract")
           ^^^^^^^^^^^^^^^^
NameError: name 'check_executable' is not defined
```

**Comment by emansom** [comment]
I presume it was caused by commit 38cad2d98d4bf528679a05b61322ec7f8954dcae, seeing as the `check_executable` method the stacktrace is complaining about was changed in that commit. @koplo199 @TheEvilSkeleton @orowith2os

**Comment by koplo199** [comment]
Good catch, I presume:
```Python
return check_executable("NAME")
```
calls should be instead:
```Python
return self.check_executable("NAME")
```

**Comment by koplo199** [comment]
#3109 Should fix the issue
