### ISSUE TITLE
[Bug]: it is not possible to use Environment Variables

### ISSUE THREAD

**Issue by Heus-Sueh** [bottlesdevs/Bottles#3128]
### Describe the bug

I'm trying to run a game using an env var, but I'm not succeeding
```
❯ flatpak run com.usebottles.bottles
13:28:56 (INFO) Bottles Started! 
13:29:00 (INFO) Performing Bottles checks… 
13:29:00 (INFO) Dxvks found:
	 - dxvk-2.3
 
13:29:00 (INFO) Vkd3ds found:
	 - vkd3d-proton-2.10
 
13:29:00 (INFO) Nvapis found:
	 - dxvk-nvapi-v0.6.3
 
13:29:00 (INFO) Latencyflexs found:
	 - latencyflex-v0.1.1
 
13:29:00 (INFO) Runners found:
	 - wine-ge-proton8-18
	 - kron4ek-wine-8.17-staging-tkg-amd64
	 - ge-proton8-17
	 - sys-wine-8.0.2
 
13:29:00 (INFO) Temp directory cleaned successfully! 
13:29:00 (INFO) Bottles found:
	 - Apps
	 - Assetto Corsa
	 - Gaming
	 - NFS Most Wanted
	 - test1
 
13:29:00 (INFO) Catalog dependencies loaded 
13:29:00 (INFO) Catalog installers loaded 
13:29:01 (INFO) Setting Key use_steam_runtime=True for bottle test1… 
13:29:01 (INFO) Setting Key sync=fsync for bottle test1… 
13:29:01 (INFO) There is no running wineserver. 
13:29:01 (INFO) Catalog components loaded 
13:29:02 (INFO) Launching an executable… 
13:29:02 (INFO) Using Steam runtime scout 
13:29:03 (INFO) Using EasyAntiCheat runtime 
13:29:03 (INFO) Using BattlEye runtime 
13:29:03 (ERROR) Error while running async job: <function ProgramEntry.run_executable.<locals>._run at 0x7f458d2b5ea0>
	Exception: illegal environment variable name
 
  File "/app/share/bottles/bottles/backend/utils/threading.py", line 59, in __target
    result = self.task_func(*args, **kwargs)
  File "/app/share/bottles/bottles/frontend/widgets/program.py", line 180, in _run
    WineExecutor.run_program(self.config, self.program, with_terminal)
  File "/app/share/bottles/bottles/backend/wine/executor.py", line 123, in run_program
    ).run()
  File "/app/share/bottles/bottles/backend/wine/executor.py", line 213, in run
    return self.__launch_with_bridge()
  File "/app/share/bottles/bottles/backend/wine/executor.py", line 244, in __launch_with_bridge
    return self.__launch_exe()
  File "/app/share/bottles/bottles/backend/wine/executor.py", line 275, in __launch_exe
    res = winecmd.run()
  File "/app/share/bottles/bottles/backend/wine/winecommand.py", line 662, in run
    proc = subprocess.Popen(
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1782, in _execute_child
    raise ValueError("illegal environment variable name")
Traceback (most recent call last):
  File "/app/share/bottles/bottles/frontend/widgets/program.py", line 148, in __reset_buttons
    raise NotImplementedError("Invalid data type, expect bool or Result, but it was %s" % type(result))
NotImplementedError: Invalid data type, expect bool or Result, but it was <class 'NoneType'>
```

### To Reproduce

try running a game/program using an env var
`VKD3D_SHADER_MODEL=6_6`

### Package

Flatpak from Flathub

### Distribution

Fedora Silverblue

### Debugging Information

```shell
Official Package: true
Version: '51.9'
DE/WM: gnome
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
            nvngx_path: /usr/lib/x86_64-linux-gnu/GL/nvidia-535-113-01/extra/nvidia/wine
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.5.6-200.fc38.x86_64
Disk:
    Total: 8339402752
    Free: 8339238912
RAM:
    MemTotal: 15.5GiB
    MemAvailable: 8.9GiB
Bottles_envs: null
```

### Troubleshooting Logs

```shell
13:29:03 (ERROR) Error while running async job: <function ProgramEntry.run_executable.<locals>._run at 0x7f458d2b5ea0>
	Exception: illegal environment variable name
 
  File "/app/share/bottles/bottles/backend/utils/threading.py", line 59, in __target
    result = self.task_func(*args, **kwargs)
  File "/app/share/bottles/bottles/frontend/widgets/program.py", line 180, in _run
    WineExecutor.run_program(self.config, self.program, with_terminal)
  File "/app/share/bottles/bottles/backend/wine/executor.py", line 123, in run_program
    ).run()
  File "/app/share/bottles/bottles/backend/wine/executor.py", line 213, in run
    return self.__launch_with_bridge()
  File "/app/share/bottles/bottles/backend/wine/executor.py", line 244, in __launch_with_bridge
    return self.__launch_exe()
  File "/app/share/bottles/bottles/backend/wine/executor.py", line 275, in __launch_exe
    res = winecmd.run()
  File "/app/share/bottles/bottles/backend/wine/winecommand.py", line 662, in run
    proc = subprocess.Popen(
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1782, in _execute_child
    raise ValueError("illegal environment variable name")
Traceback (most recent call last):
  File "/app/share/bottles/bottles/frontend/widgets/program.py", line 148, in __reset_buttons
    raise NotImplementedError("Invalid data type, expect bool or Result, but it was %s" % type(result))
NotImplementedError: Invalid data type, expect bool or Result, but it was <class 'NoneType'>
```
```


### Additional context

This has been happening for a while, I even tried searching for issues in the repo and found nothing about it.

**Comment by Heus-Sueh** [comment]
Sorry, my mistake, but the design here isn't the best, for me it doesn't make sense for the "value" to be below the "key", or perhaps it would be better for the value to be after the "=" sign like this: `VKD3D_SHADER_MODEL=6_6`

Bottles:
![image](https://github.com/bottlesdevs/Bottles/assets/98482469/19ef5aaf-1ad7-40fc-a111-201ce9b36498)
Lutris:
![image](https://github.com/bottlesdevs/Bottles/assets/98482469/c53ccba8-b492-4ef5-a3ff-2d1bdfb67366)
