### ISSUE TITLE
[Bug]: Bottles crashes with "Error flushing display: Broken pipe"

### ISSUE THREAD

**Issue by CrazyLinuxNerd** [bottlesdevs/Bottles#3162]
### Describe the bug

Opening Menu > Preferences - > Runners a second time causes a crash.

If I open this menu / section the first time it works just fine. However, proceeding to close that menu, and then open it again causes a crash with the following output:

Gdk-Message: 17:12:57.495: Error flushing display: Broken pipe

### To Reproduce

1. Open Menu -> Preferences -> Runners
2. Expand entries within the menu (All items should show correctly)
3. Close the Window
4. Repeat above steps
5. Observe crash with error "Error flushing display: Broken pipe"

### Package

Flatpak from Flathub

### Distribution

Gentoo

### Debugging Information

```shell
F: Not sharing "/usr/share/icons" with sandbox: Path "/usr" is reserved by Flatpak

(process:2): GLib-GIO-WARNING **: 17:08:40.331: Can't find module 'dconf' specified in GSETTINGS_BACKEND
Official Package: true
Version: '51.9'
DE/WM: plasmawayland
Display:
    X.org: true
    X.org (port): :1
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.5.11-gentoo
Disk:
    Total: 16778559488
    Free: 16778399744
RAM:
    MemTotal: 31.3GiB
    MemAvailable: 23.4GiB
Bottles_envs: null
```

### Troubleshooting Logs

```shell
~ % flatpak run com.usebottles.bottles
F: Not sharing "/usr/share/icons" with sandbox: Path "/usr" is reserved by Flatpak

(process:2): GLib-GIO-WARNING **: 17:12:26.225: Can't find module 'dconf' specified in GSETTINGS_BACKEND
17:12:26 (INFO) Bottles Started! 
17:12:27 (INFO) Performing Bottles checks… 
17:12:27 (INFO) Dxvks found:
         - dxvk-2.1
         - dxvk-2.1-1-0811813
         - dxvk-1.10
 
17:12:27 (INFO) Vkd3ds found:
         - vkd3d-proton-2.8-1-7be64c2
         - vkd3d-proton-2.8
         - vkd3d-proton-2.6
 
17:12:27 (INFO) Nvapis found:
         - dxvk-nvapi-v0.5.3
 
17:12:27 (INFO) Latencyflexs found:
         - latencyflex-v0.1.0
 
17:12:27 (INFO) Runners found:
         - soda-7.0-9
         - soda-7.0-7
         - caffe-7.18
         - caffe-7.2
         - vaniglia-7.18
         - lutris-7.2-2
         - lutris-7.1-fshack
         - wine-ge-proton8-12
         - wine-ge-proton8-7
         - wine-ge-proton8-4
         - wine-ge-proton7-37
         - wine-ge-proton7-34
         - sys-wine-8.0.2
 
17:12:27 (ERROR) Config file not exists 
Traceback (most recent call last):
  File "/app/share/bottles/bottles/backend/models/config.py", line 183, in load
    raise FileNotFoundError("Config file not exists")
FileNotFoundError: Config file not exists
17:12:27 (WARNING) Migrating config key 'fsr_level' to 'fsr_sharpening_strength' 
17:12:27 (WARNING) Skipping unexpected config 'Latest_Executables' in BottleConfig 
17:12:27 (ERROR) Config file not exists 
Traceback (most recent call last):
  File "/app/share/bottles/bottles/backend/models/config.py", line 183, in load
    raise FileNotFoundError("Config file not exists")
FileNotFoundError: Config file not exists
17:12:27 (ERROR) Config file not exists 
Traceback (most recent call last):
  File "/app/share/bottles/bottles/backend/models/config.py", line 183, in load
    raise FileNotFoundError("Config file not exists")
FileNotFoundError: Config file not exists
17:12:27 (WARNING) Migrating config key 'fsr_level' to 'fsr_sharpening_strength' 
17:12:27 (WARNING) Skipping unexpected config 'Latest_Executables' in BottleConfig 
17:12:27 (WARNING) Skipping unexpected config 'aco_compiler' in BottleParams 
17:12:27 (WARNING) Skipping unexpected config 'dxvk_hud' in BottleParams 
17:12:27 (WARNING) Migrating config key 'fsr_level' to 'fsr_sharpening_strength' 
17:12:27 (WARNING) Skipping unexpected config 'Latest_Executables' in BottleConfig 
17:12:27 (INFO) Bottles found:
         - DART
         - EAC
         - Wolvenkit
 
17:12:28 (INFO) Catalog dependencies loaded 
17:12:28 (INFO) Catalog installers loaded 
17:12:28 (INFO) Catalog components loaded 
Gdk-Message: 17:12:57.495: Error flushing display: Broken pipe
~ %
```

**Comment by CrazyLinuxNerd** [comment]
Good news!

As of version 51.10 this crash no longer occurs for me. I've tried to trigger it again in numerous ways which would trigger it previously. But avast me hearties, it just won't crash!

This should be considered fixed going forward :-).

**Comment by leonewton253** [comment]
Im still having this problem on KDE. It happens when starting the program and sometimes when adding games to the library.  Is there anyway to make the program refresh the window to prevent the compositor from closing it?

https://github.com/nicotine-plus/nicotine-plus/issues/2839#issuecomment-1945176741
