### ISSUE TITLE
[Bug]: Bottles 51.10 broke launching programs from CLI or Desktop Entry

### ISSUE THREAD

**Issue by Perkolator** [bottlesdevs/Bottles#3210]
### Describe the bug

After updating to 51.10 I noticed that I was unable to start a game from a Desktop Entry. Trying to launch the game from the terminal with the same command as in the Desktop Entry, the following error happens:

```
$ flatpak run --command=bottles-cli com.usebottles.bottles run -p 'Dusk HD' -b 'Dusk' -- %u

17:38:08 (INFO) Forcing offline mode 
Traceback (most recent call last):
  File "/app/bin/bottles-cli", line 652, in <module>
    cli = CLI()
          ^^^^^
  File "/app/bin/bottles-cli", line 150, in __init__
    self.__process_args()
  File "/app/bin/bottles-cli", line 199, in __process_args
    self.run_program()
  File "/app/bin/bottles-cli", line 574, in run_program
    _args = program.get("arguments", "") + " " + _args
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

I removed the Desktop Entry from `~/.local/share/applications` and created it again from the bottle, but the same problem persists.

### To Reproduce

1. Create a Desktop Entry for a program in a bottle, or try starting it straight from the terminal

= error

### Package

Flatpak from Flathub

### Distribution

Mint 20.3 Cinnamon

### Debugging Information

```shell
Official Package: true
Version: '51.10'
DE/WM: cinnamon
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
            nvngx_path: /usr/lib/x86_64-linux-gnu/GL/nvidia-535-129-03/extra/nvidia/wine
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.4.0-167-generic
Disk:
    Total: 8339161088
    Free: 8338980864
RAM:
    MemTotal: 15.5GiB
    MemAvailable: 5.2GiB
Bottles_envs: null
```

**Comment by mrceperka** [comment]
Got same problem. 51.10 as well. Fedora 38 Workstation.

**Comment by koplo199** [comment]
Nice catch, could affected users check if #3211 indeed fix the issue? Build artifacts should soon be available [here](https://github.com/bottlesdevs/Bottles/actions/runs/7316025981?pr=3211).

**Comment by Perkolator** [comment]
@koplo199 both tested, both work. Nice quick fix. :)

**Comment by koplo199** [comment]
And thanks for the confirmation ;)

**Comment by isitLoVe** [comment]
Also fixed the launch from Steam on Steam Deck for me

**Comment by Kagukara** [comment]
Just ran into this issue on the Steam Deck and this comment suggesting to add "`--args-replace` after the second `run`" fixed it.

> Edit: Adding ` --args-replace` after the second `run` in the above command line should theoretically serve the same purpose, without the need to install any artifact.
Comment: https://github.com/bottlesdevs/Bottles/issues/3210#issuecomment-1868565791

When will a fix get released so this doesn't keep happening? My current bottles flatpak is on `Version: '51.10'`.

**Comment by Stephenm64** [comment]
I encountered this bug by happenstance with my first attempt at trying out bottles. it was really frustrating, releasing an update with the fixes asap would be highly appreciated.
