### ISSUE TITLE
[Bug]: Launching game through xdg-open causes bottles to crash

### ISSUE THREAD

**Issue by axtloss** [bottlesdevs/Bottles#3225]
### Describe the bug

Trying to launch bottles using xdg open causes it to crash with a python TypeError

### To Reproduce

1. open console
2. `xdg-open bottles:run/"<bottle name>"/"<app/game>"
3. observe as python yields a TypeError about adding NoneType and str

### Package

Flatpak from Flathub

### Distribution

Arch Linux

### Debugging Information

```shell
Official Package: true
Version: '51.10'
DE/WM: gnome
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        nvidia: &amp;id002
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
            nvngx_path: /usr/lib/x86_64-linux-gnu/GL/nvidia-535-43-15/extra/nvidia/wine
        intel: &amp;id001
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.x86_64.json:/usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.i686.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json
    prime:
        integrated: *id001
        discrete: *id002
Kernel:
    Type: Linux
    Version: 6.6.7-arch1-1
Disk:
    Total: 8297713664
    Free: 8297525248
RAM:
    MemTotal: 15.5GiB
    MemAvailable: 6.7GiB
Bottles_envs: null
```

### Troubleshooting Logs

```shell
xen@orchid ~> xdg-open bottles:run/"botltu"/"Muse Dash"
xen@orchid ~> TypeError: Must be number, not NoneType
22:53:14 (INFO) Forcing offline mode 
Traceback (most recent call last):
  File "/app/bin/bottles-cli", line 652, in <module>
    cli = CLI()
          ^^^^^
  File "/app/bin/bottles-cli", line 150, in __init__
    self.__process_args()
  File "/app/bin/bottles-cli", line 199, in __process_args
    self.run_program()
  File "/app/bin/bottles-cli", line 574, in run_program
    _args = program.get("arguments", "") + " " + _args
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by koplo199** [comment]
Duplicate, see #3210
