### ISSUE TITLE
[Bug]: Unable to open shortcut launch preferences

### ISSUE THREAD

**Issue by axtloss** [bottlesdevs/Bottles#3226]
### Describe the bug

When trying to change the launch options of a game, the window containing the options does not pop up.

### To Reproduce

1. Open a bottle
2. Click on the three dots on a shortcut
3. Click "Change launch options"
4. Window does not open

### Package

Flatpak from Flathub

### Distribution

Arch Linux

### Debugging Information

```shell
Official Package: true
Version: '51.10'
DE/WM: gnome
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        nvidia: &amp;id002
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
            nvngx_path: /usr/lib/x86_64-linux-gnu/GL/nvidia-535-43-15/extra/nvidia/wine
        intel: &amp;id001
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.x86_64.json:/usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.i686.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json
    prime:
        integrated: *id001
        discrete: *id002
Kernel:
    Type: Linux
    Version: 6.6.7-arch1-1
Disk:
    Total: 8297713664
    Free: 8297525248
RAM:
    MemTotal: 15.5GiB
    MemAvailable: 7.5GiB
Bottles_envs: null
```

### Troubleshooting Logs

```shell
Traceback (most recent call last):
  File "/app/share/bottles/bottles/frontend/widgets/program.py", line 134, in show_launch_options_view
    dialog = LaunchOptionsDialog(self, self.config, self.program)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/bottles/bottles/frontend/windows/launchoptions.py", line 82, in __init__
    self.entry_arguments.set_text(program.get("arguments", ""))
TypeError: Argument 1 does not allow None as a value
```

### Additional context

This does not seem to happen on every shortcut, only two of the shortcuts I have do this, the one thing they have in common is that I manually added them from a local exe and changed their name

**Comment by koplo199** [comment]
Until the fix at #3211 is shipped, it is possible to manually resolve the issue by editing the `bottle.yml` at: 
```
~/.var/app/com.usebottles.bottles/data/bottles/bottles/YOUR_BOTTLE_NAME/bottle.yml
```
Searching for `arguments:` values and replacing any `None` or `null` by `''` will fix the error once for all too.

**Comment by lipancs** [comment]
> Until the fix at #3211 is shipped, it is possible to manually resolve the issue by editing the `bottle.yml` at:
> 
> ```
> ~/.var/app/com.usebottles.bottles/data/bottles/bottles/YOUR_BOTTLE_NAME/bottle.yml
> ```
> 
> Searching for `arguments:` values and replacing any `None` or `null` by `''` will fix the error once for all too.

it is works!
