### ISSUE TITLE
[Bug]: Can't launch one specific game through the desktop entry generated by Bottles

### ISSUE THREAD

**Issue by jemsombra** [bottlesdevs/Bottles#3228]
### Describe the bug

Yesterday I installed HoloCure with Bottles, but later realized that I can only launch it through the program itself, not the desktop fle that it generated. Running the command added to the file returns an error too.

The command:
`flatpak run --command=bottles-cli com.usebottles.bottles run -p HoloCure -b 'wine-ge' -- %u`

### To Reproduce

1. Open a bottle
2. Generate a desktop entry through the options in the three-dots menu

### Package

Flatpak from Flathub

### Distribution

Debian 12

### Debugging Information

```shell
Official Package: true
Version: '51.10'
DE/WM: lightdm-xsession
Display:
    X.org: true
    X.org (port): :0.0
    Wayland: false
Graphics:
    vendors:
        intel:
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.i686.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.1.0-16-amd64
Disk:
    Total: 5127819264
    Free: 5127651328
RAM:
    MemTotal: 9.6GiB
    MemAvailable: 7.0GiB
Bottles_envs: null
```

### Troubleshooting Logs

```shell
hat@lb490:~$ flatpak run --command=bottles-cli com.usebottles.bottles run -p HoloCure -b 'wine-ge' -- %u
22:50:14 (INFO) Forcing offline mode 
Traceback (most recent call last):
  File "/app/bin/bottles-cli", line 652, in <module>
    cli = CLI()
          ^^^^^
  File "/app/bin/bottles-cli", line 150, in __init__
    self.__process_args()
  File "/app/bin/bottles-cli", line 199, in __process_args
    self.run_program()
  File "/app/bin/bottles-cli", line 574, in run_program
    _args = program.get("arguments", "") + " " + _args
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
hat@lb490:~$
```

**Comment by koplo199** [comment]
Same as #3210
