### ISSUE TITLE
[Bug]: SQLite DLL not found.

### ISSUE THREAD

**Issue by kjacksonri** [bottlesdevs/Bottles#3235]
### Describe the bug

I am attempting to run (it's a portable Windows app) the "City of Heroes CityModder", downloadable from [here](https://mods.cityofheroes.dev/).

When I attempt to run it, it fails with an error indicating that it cannot find SQLite (please see below.)

### To Reproduce

1. Go to [https://mods.cityofheroes.dev/](https://mods.cityofheroes.dev/) and click on the "Download the Mod Installer »" button link and unzip it.
2. Create a new "Gaming" Bottle.
3. From the new bottle, click on "Run Executable".
4. Try to run `CoHModdingTool.exe`.
5. Get the following error:

```
0:39:23 (INFO) Launching an executable… 
10:39:23 (ERROR) Unable to load libGLX_nvidia.so.0 
10:39:23 (WARNING) Unable to locate libGLX_nvidia 
10:39:23 (WARNING) Nouveau driver detected, this may cause issues 
10:39:24 (INFO) Using EasyAntiCheat runtime 
10:39:24 (INFO) Using BattlEye runtime 
sync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
00e0:err:ole:CoGetContextToken apartment not initialised
00d8:err:eventlog:ReportEventW L"Application: CoHModdingTool.exe\nFramework Version: v4.0.30319\nDescription: The process was terminated due to an unhandled exception.\nException Info: System.DllNotFoundException\n   at System.Data.SQLite.UnsafeNativeMethods.sqlite3_config_none(System.Data.SQLite.SQLiteConfigOpsEnum)\n  "...

Unhandled Exception: System.InvalidOperationException: An error occurred creating the form. See Exception.InnerEx
ception for details.  The error is: Unable to load DLL 'SQLite.Interop.dll': Module not found. (Exception from HR
ESULT: 0x8007007E) ---> System.DllNotFoundException: Unable to load DLL 'SQLite.Interop.dll': Module not found. (
Exception from HRESULT: 0x8007007E)
   at System.Data.SQLite.UnsafeNativeMethods.sqlite3_config_none(SQLiteConfigOpsEnum op)
   at System.Data.SQLite.SQLite3.StaticIsInitialized()
   at System.Data.SQLite.SQLiteLog.PrivateInitialize(String className)
   at System.Data.SQLite.SQLiteLog.Initialize(String className)
   at System.Data.SQLite.SQLiteConnection..ctor(String connectionString, Boolean parseViaFramework)
   at System.Data.SQLite.SQLiteConnection..ctor()
   at CoHModdingTool.CoHModderMainForm..ctor()
   --- End of inner exception stack trace ---
   at CoHModdingTool.My.MyProject.MyForms.Create__Instance__[T](T Instance)
   at CoHModdingTool.My.MyApplication.OnCreateMainForm()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Run(String[] commandLine)
   at CoHModdingTool.My.MyApplication.Main(String[] Args)
wine: Unhandled exception 0xe0434352 in thread d8 at address 7B0127E6 (thread 00d8), starting debugger...
Unhandled exception: 0xe0434352 in 32-bit code (0x7b0127e6).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:7b0127e6 ESP:0086f204 EBP:0086f278 EFLAGS:00000246(   - --  I  Z- -P- )
 EAX:0086f210 EBX:00000000 ECX:00000010 EDX:0086f2f0
 ESI:e0434352 EDI:00000001
Stack dump:
0x0086f204:  101c053b 5f188960 016c6880 e0434352
0x0086f214:  00000001 00000000 7b0127e6 00000005
0x0086f224:  80131509 00000000 00000000 00000000
0x0086f234:  10000000 016c6880 101c05c1 5f1889c4
0x0086f244:  00000001 016c6880 00000005 00000000
0x0086f254:  00000000 00ea7128 0086f344 00000001
Backtrace:
=>0 0x7b0127e6 in kernelbase (+0x127e6) (0x0086f278)
  1 0x101b70f1 in clr (+0x1b70f1) (0x0086f324)
  2 0x10122964 in clr (+0x122964) (0x0086f3ac)
  3 0x5e567676 in microsoft.visualbasic.ni (+0x137676) (0x0086f49c)
  4 0x5e56657b in microsoft.visualbasic.ni (+0x13657b) (0x0086f4e8)
  5 0x04120ca1 (0x0086f4f8)
  6 0x1000f016 in clr (+0xf016) (0x0086f504)
  7 0x100122ba in clr (+0x122ba) (0x0086f558)
  8 0x1001850b in clr (+0x1850b) (0x0086f5c4)
  9 0x101b1d0b in clr (+0x1b1d0b) (0x0086f6e8)
  10 0x101b23ea in clr (+0x1b23ea) (0x0086f954)
  11 0x101b2317 in clr (+0x1b2317) (0x0086fe38)
  12 0x101b2498 in clr (+0x1b2498) (0x0086fe90)
  13 0x101b25be in clr (+0x1b25be) (0x0086fed0)
  14 0x101adef5 in clr (+0x1adef5) (0x0086ff0c)
  15 0x603b55ab in mscoreei (+0x55ab) (0x0086ff18)
  16 0x79007f16 in mscoree (+0x7f16) (0x0086ff28)
  17 0x79004de3 in mscoree (+0x4de3) (0x0086ff48)
  18 0x7bc5f5a7 in ntdll (+0x5f5a7) (0x0086ff5c)
  19 0x7bc5fed0 in ntdll (+0x5fed0) (0x0086ffec)
0x7b0127e6 kernelbase+0x127e6: subl     $4,%esp
Modules:
Module  Address                 Debug info      Name (95 modules)
PE      00400000-00670000       Deferred        cohmoddingtool
PE      01180000-01194000       Deferred        vcruntime140_clr0400
PE      011a0000-0124b000       Deferred        ucrtbase_clr0400
PE      04130000-041b9000       Deferred        clrjit
PE      04610000-05062000       Deferred        system.ni
PE      05070000-05213000       Deferred        system.drawing.ni
PE      05220000-06085000       Deferred        system.windows.forms.ni
PE      06090000-06195000       Deferred        system.configuration.ni
PE      061a0000-06914000       Deferred        system.xml.ni
PE      06d00000-0751a000       Deferred        system.data.ni
PE      07530000-07884000       Deferred        system.data
PE      078a0000-07958000       Deferred        system.transactions.ni
PE      07960000-079ac000       Deferred        system.transactions
PE      10000000-107af000       Export          clr
PE      5e430000-5e612000       Export          microsoft.visualbasic.ni
PE      603b0000-60416000       Export          mscoreei
PE      61a00000-62218000       Deferred        system.core.ni
PE      622c0000-622f4000       Deferred        rsaenh
PE      641c0000-641cb000       Deferred        amsi
PE      643c0000-643e9000       Deferred        ws2_32
PE      64a80000-64abc000       Deferred        win32u
PE      64c20000-64cf0000       Deferred        system.runtime.remoting.ni
PE      65340000-653d2000       Deferred        oleaut32
PE      65480000-65514000       Deferred        rpcrt4
PE      66080000-660dd000       Deferred        shlwapi
PE      66380000-664bf000       Deferred        ole32
PE      66640000-6664d000       Deferred        version
PE      667c0000-667da000       Deferred        shcore
PE      67500000-6751f000       Deferred        imm32
PE      67bc0000-67d29000       Deferred        comctl32
PE      684c0000-68523000       Deferred        combase
PE      68880000-68a3e000       Deferred        user32
PE      68cc0000-68d98000       Deferred        crypt32
PE      69840000-69885000       Deferred        advapi32
PE      6aac0000-6ab9d000       Deferred        ucrtbase
PE      6bb40000-6bb6a000       Deferred        winex11
PE      6bbc0000-6bbee000       Deferred        sechost
PE      6da80000-6db0a000       Deferred        gdi32
PE      6e200000-6e218000       Deferred        bcrypt
PE      70d80000-70db7000       Deferred        uxtheme
PE      71400000-71d43000       Deferred        shell32
PE      78000000-78044000       Deferred        msvcrt
PE      79000000-7904a000       Export          mscoree
PE      79720000-7ab1c000       Deferred        mscorlib.ni
PE      7b000000-7b2ae000       Dwarf           kernelbase
PE      7b600000-7b664000       Deferred        kernel32
PE      7bc00000-7bcaf000       Dwarf           ntdll
ELF     7d000000-7d005000       Deferred        <wine-loader>
ELF     7ee1f000-7efa8000       Dwarf           libwine.so.1
ELF     f6168000-f6194000       Deferred        libgpg-error.so.0
ELF     f6194000-f62a1000       Deferred        libgcrypt.so.20
ELF     f62a1000-f6453000       Deferred        libunistring.so.5
ELF     f6453000-f6600000       Deferred        libp11-kit.so.0
ELF     f6600000-f683a000       Deferred        libgnutls.so.30
ELF     f683e000-f684e000       Deferred        libffi.so.8
ELF     f684e000-f68cb000       Deferred        libgmp.so.10
ELF     f68cb000-f6917000       Deferred        libhogweed.so.6
ELF     f6917000-f696e000       Deferred        libnettle.so.8
ELF     f696e000-f6985000       Deferred        libtasn1.so.6
ELF     f6985000-f69dd000       Deferred        libidn2.so.0
ELF     f6a1b000-f6aa7000       Deferred        libvulkan.so.1
ELF     f6aa7000-f6c00000       Deferred        libx11.so.6
ELF     f7138000-f713f000       Deferred        ws2_32.so
ELF     f713f000-f7146000       Deferred        crypt32.so
ELF     f7185000-f7192000       Deferred        libxcursor.so.1
ELF     f7192000-f71a7000       Deferred        libxi.so.6
ELF     f71a7000-f71ac000       Deferred        libxcomposite.so.1
ELF     f71ac000-f71b5000       Deferred        libxfixes.so.3
ELF     f71b5000-f71c3000       Deferred        libxrandr.so.2
ELF     f71c3000-f71d1000       Deferred        libxrender.so.1
ELF     f71d1000-f71d8000       Deferred        libxxf86vm.so.1
ELF     f71d8000-f71dd000       Deferred        libxinerama.so.1
ELF     f71dd000-f71e3000       Deferred        libxau.so.6
ELF     f71e3000-f7213000       Deferred        libxcb.so.1
ELF     f7213000-f722a000       Deferred        libxext.so.6
ELF     f722e000-f723e000       Deferred        bcrypt.so
ELF     f7240000-f72e4000       Deferred        winex11.so
ELF     f745a000-f7486000       Deferred        libexpat.so.1
ELF     f7486000-f74db000       Deferred        libfontconfig.so.1
ELF     f74db000-f7578000       Deferred        libpcre2-8.so.0
ELF     f7578000-f759b000       Deferred        libbrotlicommon.so.1
ELF     f759b000-f75bf000       Deferred        libgraphite2.so.3
ELF     f75bf000-f772f000       Deferred        libglib-2.0.so.0
ELF     f772f000-f7758000       Deferred        libgcc_s.so.1
ELF     f7758000-f78a6000       Deferred        libharfbuzz.so.0
ELF     f78a6000-f78e8000       Deferred        libpng16.so.16
ELF     f78e8000-f79a9000       Deferred        libfreetype.so.6
ELF     f79a9000-f7a82000       Deferred        libm.so.6
ELF     f7a82000-f7c00000       Deferred        win32u.so
ELF     f7c00000-f7e32000       Deferred        libc.so.6
ELF     f7e4f000-f7e5d000       Deferred        libbrotlidec.so.1
ELF     f7e5d000-f7e70000       Deferred        libbz2.so.1
ELF     f7e70000-f7e8a000       Deferred        libz.so.1
ELF     f7eaa000-f7fa5000       Deferred        ntdll.so
ELF     f7fa7000-f7fdc000       Deferred        ld-linux.so.2
Threads:
process  tid      prio    name (all IDs are in hex)
00000020 start.exe
        00000024    0     
00000030 services.exe
        00000034    0     
        00000038    0     wine_rpcrt4_server
        00000044    0     wine_rpcrt4_io
        00000048    0     wine_threadpool_worker
        0000005c    0     wine_rpcrt4_io
        0000007c    0     wine_rpcrt4_io
        00000088    0     wine_rpcrt4_io
        000000ac    0     wine_rpcrt4_io
        000000c4    0     wine_threadpool_timerqueue
        000000c8    0     
        00000100    0     wine_rpcrt4_io
        00000104    0     wine_threadpool_worker
0000003c svchost.exe
        00000040    0     
        0000004c    0     
        00000050    0     wine_sechost_service
00000054 winedevice.exe
        00000058    0     
        00000060    0     
        00000064    0     wine_sechost_service
        00000068    0     
        0000006c    0     
        00000070    0     
        000000bc    0     
        000000c0    0     
00000074 winedevice.exe
        00000078    0     
        00000080    0     
        00000084    0     wine_sechost_service
        0000008c    0     
        00000090    0     
        00000094    0     
        0000009c    0     
        000000a0    0     
000000a4 plugplay.exe
        000000a8    0     
        000000b0    0     
        000000b4    0     wine_sechost_service
        000000b8    0     wine_rpcrt4_server
000000cc conhost.exe
        000000d0    0     
000000d4 (D) Z:\run\user\1000\doc\34f07482\CoHModdingTool.exe
        000000d8    0 <== 
        000000dc    0     
        000000e0    2     
        00000140    0     
        00000154    0     
000000e4 explorer.exe
        000000e8    0     
        000000ec    0     
        000000f0    0     wine_rpcrt4_server
000000f8 rpcss.exe
        000000fc    0     
        00000108    0     
        0000010c    0     wine_sechost_service
        00000110    0     wine_rpcrt4_server
        00000114    0     wine_rpcrt4_server
        00000118    0     wine_rpcrt4_io
        0000011c    0     wine_threadpool_worker
00000120 tabtip.exe
        00000124    0     
        0000012c    0     wine_rpcrt4_server
        00000130    0     
        00000134    0     
        0000013c    0     
0000014c conhost.exe
        00000150    0     
System information:
    Wine build: wine-experimental.wine.8.0.20231114c.r0.g0ebbd573f30 ( TkG Plain )
    Platform: i386 (WOW64)
    Version: Windows 10
    Host system: Linux
    Host version: 6.1.0-17-amd64

```

### Package

Flatpak from Flathub

### Distribution

Debian 12

### Debugging Information

```shell
Official Package: true
Version: '51.10'
DE/WM: plasmawayland
Display:
    X.org: true
    X.org (port): :1
    Wayland: true
Graphics:
    vendors:
        nvidia: &amp;id002
            vendor: nvidia
            envs:
                DRI_PRIME: '1'
            icd: ''
            nvngx_path: null
        intel: &amp;id001
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.i686.json
    prime:
        integrated: *id001
        discrete: *id002
Kernel:
    Type: Linux
    Version: 6.1.0-17-amd64
Disk:
    Total: 8192892928
    Free: 8192724992
RAM:
    MemTotal: 15.3GiB
    MemAvailable: 8.9GiB
Bottles_envs: null
```

### Troubleshooting Logs

```shell
10:54:32 (ERROR) Unable to load libGLX_nvidia.so.0 
10:54:33 (WARNING) Unable to locate libGLX_nvidia 
10:54:33 (INFO) Bottles Started! 

(bottles:2): Gtk-WARNING **: 10:54:33.981: AdwViewSwitcher 0x55674488f0e0 (viewswitcher) reported min height -6, but sizes must be >= 0
10:54:38 (INFO) Performing Bottles checks… 
10:54:38 (INFO) Dxvks found:
         - dxvk-2.3
 
10:54:38 (INFO) Vkd3ds found:
         - vkd3d-proton-2.11
 
10:54:38 (INFO) Nvapis found:
         - dxvk-nvapi-v0.6.4
 
10:54:38 (INFO) Latencyflexs found:
         - latencyflex-v0.1.1
 
10:54:38 (INFO) Runners found:
         - soda-8.0-2
         - sys-wine-8.0.2
 
10:54:38 (INFO) Bottles found:
         - DrivethruRPG Downloader
         - City of Heroes
 
10:54:39 (INFO) Catalog installers loaded 
10:54:39 (INFO) Catalog dependencies loaded 
10:54:39 (INFO) Catalog components loaded 
10:54:41 (INFO) Setting Key sync=fsync for bottle City of Heroes… 
10:54:41 (INFO) There is no running wineserver. 
10:54:47 (INFO) Launching an executable… 
10:54:47 (ERROR) Unable to load libGLX_nvidia.so.0 
10:54:47 (WARNING) Unable to locate libGLX_nvidia 
10:54:48 (WARNING) Nouveau driver detected, this may cause issues 
10:54:48 (INFO) Using EasyAntiCheat runtime 
10:54:48 (INFO) Using BattlEye runtime 
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
00e4:err:ole:CoGetContextToken apartment not initialised
00dc:err:eventlog:ReportEventW L"Application: CoHModdingTool.exe\nFramework Version: v4.0.30319\nDescription: The process was terminated due to an unhandled exception.\nException Info: System.DllNotFoundException\n   at System.Data.SQLite.UnsafeNativeMethods.sqlite3_config_none(System.Data.SQLite.SQLiteConfigOpsEnum)\n  "...

Unhandled Exception: System.InvalidOperationException: An error occurred creating the form. See Exception.InnerEx
ception for details.  The error is: Unable to load DLL 'SQLite.Interop.dll': Module not found. (Exception from HR
ESULT: 0x8007007E) ---> System.DllNotFoundException: Unable to load DLL 'SQLite.Interop.dll': Module not found. (
Exception from HRESULT: 0x8007007E)
   at System.Data.SQLite.UnsafeNativeMethods.sqlite3_config_none(SQLiteConfigOpsEnum op)
   at System.Data.SQLite.SQLite3.StaticIsInitialized()
   at System.Data.SQLite.SQLiteLog.PrivateInitialize(String className)
   at System.Data.SQLite.SQLiteLog.Initialize(String className)
   at System.Data.SQLite.SQLiteConnection..ctor(String connectionString, Boolean parseViaFramework)
   at System.Data.SQLite.SQLiteConnection..ctor()
   at CoHModdingTool.CoHModderMainForm..ctor()
   --- End of inner exception stack trace ---
   at CoHModdingTool.My.MyProject.MyForms.Create__Instance__[T](T Instance)
   at CoHModdingTool.My.MyApplication.OnCreateMainForm()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Run(String[] commandLine)
   at CoHModdingTool.My.MyApplication.Main(String[] Args)
wine: Unhandled exception 0xe0434352 in thread dc at address 7B0127E6 (thread 00dc), starting debugger...
Unhandled exception: 0xe0434352 in 32-bit code (0x7b0127e6).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:7b0127e6 ESP:0086f204 EBP:0086f278 EFLAGS:00000246(   - --  I  Z- -P- )
 EAX:0086f210 EBX:00000000 ECX:00000010 EDX:0086f2f0
 ESI:e0434352 EDI:00000001
Stack dump:
0x0086f204:  101c053b 5cb1221a 016c6880 e0434352
0x0086f214:  00000001 00000000 7b0127e6 00000005
0x0086f224:  80131509 00000000 00000000 00000000
0x0086f234:  10000000 016c6880 101c05c1 5cb122be
0x0086f244:  00000001 016c6880 00000005 00000000
0x0086f254:  00000000 0098a428 0086f344 00000001
Backtrace:
=>0 0x7b0127e6 in kernelbase (+0x127e6) (0x0086f278)
  1 0x101b70f1 in clr (+0x1b70f1) (0x0086f324)
  2 0x10122964 in clr (+0x122964) (0x0086f3ac)
  3 0x5e567676 in microsoft.visualbasic.ni (+0x137676) (0x0086f49c)
  4 0x5e56657b in microsoft.visualbasic.ni (+0x13657b) (0x0086f4e8)
  5 0x04120ca1 (0x0086f4f8)
  6 0x1000f016 in clr (+0xf016) (0x0086f504)
  7 0x100122ba in clr (+0x122ba) (0x0086f558)
  8 0x1001850b in clr (+0x1850b) (0x0086f5c4)
  9 0x101b1d0b in clr (+0x1b1d0b) (0x0086f6e8)
  10 0x101b23ea in clr (+0x1b23ea) (0x0086f954)
  11 0x101b2317 in clr (+0x1b2317) (0x0086fe38)
  12 0x101b2498 in clr (+0x1b2498) (0x0086fe90)
  13 0x101b25be in clr (+0x1b25be) (0x0086fed0)
  14 0x101adef5 in clr (+0x1adef5) (0x0086ff0c)
  15 0x603b55ab in mscoreei (+0x55ab) (0x0086ff18)
  16 0x79007f16 in mscoree (+0x7f16) (0x0086ff28)
  17 0x79004de3 in mscoree (+0x4de3) (0x0086ff48)
  18 0x7bc5f5a7 in ntdll (+0x5f5a7) (0x0086ff5c)
  19 0x7bc5fed0 in ntdll (+0x5fed0) (0x0086ffec)
0x7b0127e6 kernelbase+0x127e6: subl     $4,%esp
Modules:
Module  Address                 Debug info      Name (95 modules)
PE      00400000-00670000       Deferred        cohmoddingtool
PE      01180000-01194000       Deferred        vcruntime140_clr0400
PE      011a0000-0124b000       Deferred        ucrtbase_clr0400
PE      04130000-041b9000       Deferred        clrjit
PE      04610000-05062000       Deferred        system.ni
PE      05070000-05213000       Deferred        system.drawing.ni
PE      05220000-06085000       Deferred        system.windows.forms.ni
PE      06090000-06195000       Deferred        system.configuration.ni
PE      061a0000-06914000       Deferred        system.xml.ni
PE      06d00000-0751a000       Deferred        system.data.ni
PE      07530000-07884000       Deferred        system.data
PE      078a0000-07958000       Deferred        system.transactions.ni
PE      07960000-079ac000       Deferred        system.transactions
PE      10000000-107af000       Export          clr
PE      5e430000-5e612000       Export          microsoft.visualbasic.ni
PE      603b0000-60416000       Export          mscoreei
PE      61a00000-62218000       Deferred        system.core.ni
PE      622c0000-622f4000       Deferred        rsaenh
PE      641c0000-641cb000       Deferred        amsi
PE      643c0000-643e9000       Deferred        ws2_32
PE      64a80000-64abc000       Deferred        win32u
PE      64c20000-64cf0000       Deferred        system.runtime.remoting.ni
PE      65340000-653d2000       Deferred        oleaut32
PE      65480000-65514000       Deferred        rpcrt4
PE      66080000-660dd000       Deferred        shlwapi
PE      66380000-664bf000       Deferred        ole32
PE      66640000-6664d000       Deferred        version
PE      667c0000-667da000       Deferred        shcore
PE      67500000-6751f000       Deferred        imm32
PE      67bc0000-67d29000       Deferred        comctl32
PE      684c0000-68523000       Deferred        combase
PE      68880000-68a3e000       Deferred        user32
PE      68cc0000-68d98000       Deferred        crypt32
PE      69840000-69885000       Deferred        advapi32
PE      6aac0000-6ab9d000       Deferred        ucrtbase
PE      6bb40000-6bb6a000       Deferred        winex11
PE      6bbc0000-6bbee000       Deferred        sechost
PE      6da80000-6db0a000       Deferred        gdi32
PE      6e200000-6e218000       Deferred        bcrypt
PE      70d80000-70db7000       Deferred        uxtheme
PE      71400000-71d43000       Deferred        shell32
PE      78000000-78044000       Deferred        msvcrt
PE      79000000-7904a000       Export          mscoree
PE      79720000-7ab1c000       Deferred        mscorlib.ni
PE      7b000000-7b2ae000       Dwarf           kernelbase
PE      7b600000-7b664000       Deferred        kernel32
PE      7bc00000-7bcaf000       Dwarf           ntdll
ELF     7d000000-7d005000       Deferred        <wine-loader>
ELF     7ea77000-7ec00000       Dwarf           libwine.so.1
ELF     f60cb000-f61d8000       Deferred        libgcrypt.so.20
ELF     f61d8000-f6255000       Deferred        libgmp.so.10
ELF     f6255000-f62a1000       Deferred        libhogweed.so.6
ELF     f62a1000-f6453000       Deferred        libunistring.so.5
ELF     f6453000-f6600000       Deferred        libp11-kit.so.0
ELF     f6600000-f683a000       Deferred        libgnutls.so.30
ELF     f683a000-f6866000       Deferred        libgpg-error.so.0
ELF     f6866000-f6876000       Deferred        libffi.so.8
ELF     f6876000-f68cd000       Deferred        libnettle.so.8
ELF     f68cd000-f68e4000       Deferred        libtasn1.so.6
ELF     f68e4000-f693c000       Deferred        libidn2.so.0
ELF     f6944000-f694b000       Deferred        ws2_32.so
ELF     f694b000-f6952000       Deferred        crypt32.so
ELF     f69cf000-f69dc000       Deferred        libxcursor.so.1
ELF     f69dc000-f6a68000       Deferred        libvulkan.so.1
ELF     f6a68000-f6a7d000       Deferred        libxi.so.6
ELF     f6a7d000-f6a82000       Deferred        libxcomposite.so.1
ELF     f6a82000-f6a8b000       Deferred        libxfixes.so.3
ELF     f6a8b000-f6a99000       Deferred        libxrandr.so.2
ELF     f6a99000-f6aa7000       Deferred        libxrender.so.1
ELF     f6aa7000-f6c00000       Deferred        libx11.so.6
ELF     f7124000-f712b000       Deferred        libxxf86vm.so.1
ELF     f712b000-f7130000       Deferred        libxinerama.so.1
ELF     f7130000-f7136000       Deferred        libxau.so.6
ELF     f7136000-f7166000       Deferred        libxcb.so.1
ELF     f7166000-f717d000       Deferred        libxext.so.6
ELF     f7181000-f7191000       Deferred        bcrypt.so
ELF     f7193000-f7237000       Deferred        winex11.so
ELF     f73a1000-f73cd000       Deferred        libexpat.so.1
ELF     f73cd000-f7422000       Deferred        libfontconfig.so.1
ELF     f7422000-f74bf000       Deferred        libpcre2-8.so.0
ELF     f74bf000-f74e2000       Deferred        libbrotlicommon.so.1
ELF     f74e2000-f7506000       Deferred        libgraphite2.so.3
ELF     f7506000-f7676000       Deferred        libglib-2.0.so.0
ELF     f7676000-f769f000       Deferred        libgcc_s.so.1
ELF     f769f000-f77ed000       Deferred        libharfbuzz.so.0
ELF     f77ed000-f78ae000       Deferred        libfreetype.so.6
ELF     f78ae000-f7987000       Deferred        libm.so.6
ELF     f7987000-f7b05000       Deferred        win32u.so
ELF     f7b05000-f7c00000       Deferred        ntdll.so
ELF     f7c00000-f7e32000       Deferred        libc.so.6
ELF     f7e5d000-f7e6b000       Deferred        libbrotlidec.so.1
ELF     f7e6b000-f7ead000       Deferred        libpng16.so.16
ELF     f7ead000-f7ec0000       Deferred        libbz2.so.1
ELF     f7ec0000-f7eda000       Deferred        libz.so.1
ELF     f7ef9000-f7f2e000       Deferred        ld-linux.so.2
Threads:
process  tid      prio    name (all IDs are in hex)
00000020 start.exe
        00000024    0     
00000030 services.exe
        00000034    0     
        00000038    0     wine_rpcrt4_server
        00000044    0     wine_rpcrt4_io
        00000048    0     wine_threadpool_worker
        0000005c    0     wine_rpcrt4_io
        00000068    0     wine_rpcrt4_io
        00000080    0     wine_rpcrt4_io
        0000008c    0     wine_rpcrt4_io
        000000b0    0     wine_rpcrt4_io
        000000c8    0     wine_threadpool_timerqueue
        000000cc    0     
        00000104    0     wine_rpcrt4_io
        00000108    0     wine_threadpool_worker
0000003c svchost.exe
        00000040    0     
        0000004c    0     
        00000050    0     wine_sechost_service
00000054 winedevice.exe
        00000058    0     
        00000060    0     
        00000064    0     wine_sechost_service
        0000006c    0     
        00000070    0     
        00000074    0     
        000000c0    0     
        000000c4    0     
00000078 winedevice.exe
        0000007c    0     
        00000084    0     
        00000088    0     wine_sechost_service
        00000090    0     
        00000094    0     
        00000098    0     
        000000a0    0     
        000000a4    0     
000000a8 plugplay.exe
        000000ac    0     
        000000b4    0     
        000000b8    0     wine_sechost_service
        000000bc    0     wine_rpcrt4_server
000000d0 conhost.exe
        000000d4    0     
000000d8 (D) Z:\run\user\1000\doc\34f07482\CoHModdingTool.exe
        000000dc    0 <== 
        000000e0    0     
        000000e4    2     
        00000144    0     
        00000158    0     
000000e8 explorer.exe
        000000ec    0     
        000000f0    0     
        000000f4    0     wine_rpcrt4_server
000000fc rpcss.exe
        00000100    0     
        0000010c    0     
        00000110    0     wine_sechost_service
        00000114    0     wine_rpcrt4_server
        00000118    0     wine_rpcrt4_server
        0000011c    0     wine_rpcrt4_io
        00000120    0     wine_threadpool_worker
00000124 tabtip.exe
        00000128    0     
        00000130    0     wine_rpcrt4_server
        00000134    0     
        00000138    0     
        00000140    0     
00000150 conhost.exe
        00000154    0     
System information:
    Wine build: wine-experimental.wine.8.0.20231114c.r0.g0ebbd573f30 ( TkG Plain )
    Platform: i386 (WOW64)
    Version: Windows 10
    Host system: Linux
    Host version: 6.1.0-17-amd64
wine client error:dc:
```

**Comment by mirkobrombin** [comment]
Wrong repo, use the programs repo.
