### ISSUE TITLE
[Bug]: cant create "game" bottle

### ISSUE THREAD

**Issue by xyloforce** [bottlesdevs/Bottles#3285]
### Describe the bug

Can't create a "game" bottle using flatpak bottles 

### To Reproduce

- started bottles
- tried to create a "Game" bottle (preset)
- "impossible to create your bottle"

### Package

Flatpak from Flathub

### Distribution

Zorin OS 17

### Debugging Information

```shell
Official Package: true
Version: '51.10'
DE/WM: zorin
Display:
    X.org: true
    X.org (port): :1
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
            nvngx_path: /usr/lib/x86_64-linux-gnu/GL/nvidia-535-154-05/extra/nvidia/wine
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.5.0-18-generic
Disk:
    Total: 8355897344
    Free: 8355708928
RAM:
    MemTotal: 15.6GiB
    MemAvailable: 11.6GiB
Bottles_envs: null
```

### Troubleshooting Logs

```shell
fabien@MS-7752:~$ flatpak run com.usebottles.bottles 
13:57:39 (INFO) Performing Bottles checks… 
13:57:39 (INFO) Dxvks found:
	 - dxvk-2.3
 
13:57:39 (INFO) Vkd3ds found:
	 - vkd3d-proton-2.11.1
 
13:57:39 (INFO) Nvapis found:
	 - dxvk-nvapi-v0.6.4
 
13:57:39 (INFO) Latencyflexs found:
	 - latencyflex-v0.1.1
 
13:57:39 (INFO) Runners found:
	 - soda-8.0-2
	 - sys-wine-8.0.2
 
13:57:39 (ERROR) Config file not exists 
Traceback (most recent call last):
  File "/app/share/bottles/bottles/backend/models/config.py", line 183, in load
    raise FileNotFoundError("Config file not exists")
FileNotFoundError: Config file not exists
13:57:39 (ERROR) Config file not exists 
Traceback (most recent call last):
  File "/app/share/bottles/bottles/backend/models/config.py", line 183, in load
    raise FileNotFoundError("Config file not exists")
FileNotFoundError: Config file not exists
13:57:39 (INFO) Bottles Started! 
13:57:40 (INFO) Catalog installers loaded 
13:57:40 (INFO) Catalog dependencies loaded 
13:57:40 (INFO) Catalog components loaded 

Also opened a window with this trace :
[Errno 2] Aucun fichier ou dossier de ce type: '/usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json'  File "/app/share/bottles/bottles/backend/utils/threading.py", line 59, in __target
    result = self.task_func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 1249, in create_bottle
    wineboot.init()

  File "/app/share/bottles/bottles/backend/wine/wineboot.py", line 61, in init
    return self.send_status(4)
           ^^^^^^^^^^^^^^^^^^^

  File "/app/share/bottles/bottles/backend/wine/wineboot.py", line 30, in send_status
    self.launch(

  File "/app/share/bottles/bottles/backend/wine/wineprogram.py", line 61, in launch
    res = WineCommand(
          ^^^^^^^^^^^^

  File "/app/share/bottles/bottles/backend/wine/winecommand.py", line 107, in __init__
    self.env = self.get_env(_environment)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/share/bottles/bottles/backend/wine/winecommand.py", line 172, in get_env
    gpu = GPUUtils().get_gpu()
          ^^^^^^^^^^

  File "/app/share/bottles/bottles/backend/utils/gpu.py", line 44, in __init__
    self.vk = VulkanUtils()
              ^^^^^^^^^^^^^

  File "/app/share/bottles/bottles/backend/utils/vulkan.py", line 39, in __init__
    self.loaders = self.__get_vk_icd_loaders()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/share/bottles/bottles/backend/utils/vulkan.py", line 56, in __get_vk_icd_loaders
    if filecmp.cmp(nvidia_loader, file):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/filecmp.py", line 53, in cmp
    s1 = _sig(os.stat(f1))
              ^^^^^^^^^^^
```

**Comment by xyloforce** [comment]
Now its working, so I'm closing my issue :) Thanks a lot for your fabulous software by the way, its making my life so much easier 💖
