### ISSUE TITLE
[Bug]: Dependency vcredist*.exe looks corrupted

### ISSUE THREAD

**Issue by Cyb10101** [bottlesdevs/Bottles#3288]
### Describe the bug

Install a wine dependency (vcredist2022) in a existing bottle.
Maybe crashed because a import not finished or stopped because different checksum.

* Downloaded file [VC_redist.x64.exe] looks corrupted.
* Source cksum: [101b0b9f74cdc6cdbd2570bfe92e302c] downloaded: [a8a68bcc74b5022467f12587baf1ef93]
* (ERROR) Error while running async job: <function BackupManager.import_backup at 0x7fe88aa71620>
* Exception: 'list' object has no attribute 'get'

### To Reproduce

Installing Dependency "vcredist2022". But i can't see logs again?!

### Package

Flatpak from Flathub

### Distribution

Ubuntu 22.04

### Debugging Information

```shell
Official Package: true
Version: '51.11'
DE/WM: ubuntu
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.5.0-18-generic
Disk:
    Total: 16778854400
    Free: 16778690560
RAM:
    MemTotal: 31.3GiB
    MemAvailable: 18.4GiB
Bottles_envs: null
```

### Troubleshooting Logs

```shell
21:34:31 (INFO) Installing dependency [vcredist2022] in bottle [Games-Restore__165]. 
VC_redist.x86.exe (100%) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (13.2MiB/13.2MiB - 30.2MiB)

21:34:32 (INFO) Renaming [VC_redist.x86.exe] to [vcredist2022_x86.exe]. 
21:34:32 (INFO) Launching an executable… 
21:34:32 (INFO) Using EasyAntiCheat runtime 
21:34:32 (INFO) Using BattlEye runtime 
esync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely

##### START: About 20 lines of mesa_shader  #####
Failed to create /home/cyb10101/.var/app/com.usebottles.bottles/data/bottles/bottles/Games__165/cache/mesa_shader for shader cache (Datei oder Verzeichnis nicht gefunden)---disabling.
##### END: About 20 lines of mesa_shader  #####
VC_redist.x64.exe (100%) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (24.2MiB/24.2MiB - 40.7MiB)

21:34:36 (INFO) Renaming [VC_redist.x64.exe] to [vcredist2022_x64.exe]. 
21:34:36 (ERROR) Downloaded file [VC_redist.x64.exe] looks corrupted. 
21:34:36 (ERROR) Source cksum: [101b0b9f74cdc6cdbd2570bfe92e302c] downloaded: [a8a68bcc74b5022467f12587baf1ef93] 
21:34:36 (ERROR) Removing corrupted file [VC_redist.x64.exe]. 
21:34:36 (ERROR) Error while running async job: <function BackupManager.import_backup at 0x7fe88aa71620>
	Exception: 'list' object has no attribute 'get'
 
  File "/app/share/bottles/bottles/backend/utils/threading.py", line 62, in __target
    result = self.task_func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/bottles/bottles/backend/managers/backup.py", line 133, in import_backup
    return BackupManager._import_config_backup(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/bottles/bottles/backend/managers/backup.py", line 142, in _import_config_backup
    if config_load.status and manager.create_bottle_from_config(config_load.data):
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/bottles/bottles/backend/managers/manager.py", line 1110, in create_bottle_from_config
    % dep.get("Description", "n/a"),
      ^^^^^^^
Traceback (most recent call last):
  File "/app/share/bottles/bottles/frontend/views/importer.py", line 88, in __finish
    if result.ok:
       ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'ok'
```

**Comment by WasteOfO2** [comment]
Hey, I am facing this exact same issue and I have verified that my downloaded checksum always remains the same, implying that the checksum employed within bottles is either incorrect or out of date

Not sure what can be done to override this

**Comment by mirkobrombin** [comment]
fixed by https://github.com/bottlesdevs/dependencies/pull/219
