### ISSUE TITLE
[Bug]: "Launch with terminal" button gives a different result

### ISSUE THREAD

**Issue by Qronikarz** [bottlesdevs/Bottles#3309]
### Describe the bug

I have one program that I unfortunately can't share so it may not be reproduced consistently as I didn't discover any other that has the same problem.
I have it added to programs list and when clicking the play button it shortly changes into stop button and it closes on it's own without any feedback. It works when you use "launch with terminal" button.

I tried to troubleshoot it on my own, but the only difference I noticed are the runtimes and errors when you launch Bottles with terminal. (posted later)

So the difference at least in the terminal is that the normal play button in programs list shows ```Using EasyAntiCheat runtime and BattlEye runtime```. However when you use "launch with terminal" button it doesn't list those runtimes in the terminal, but the program works with some errors.

Is there any difference when it comes to how Bottles is handling those buttons? 

### To Reproduce

1.Launch bottles with terminal
2. Add some executable to program list manually
3. Launch it with play button and see the terminal
4. Launch it with "launch with terminal" button and see the terminal

### Package

Flatpak from Flathub

### Distribution

Linux Mint 21.3

### Debugging Information

```shell
Official Package: true
Version: '51.11'
DE/WM: cinnamon
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.5.0-25-generic
Disk:
    Total: 8347889664
    Free: 8347725824
RAM:
    MemTotal: 15.5GiB
    MemAvailable: 10.7GiB
Bottles_envs: null
```

### Troubleshooting Logs

```shell
15:33:45 (INFO) Launching an executable… 
15:33:45 (INFO) Using EasyAntiCheat runtime 
15:33:45 (INFO) Using BattlEye runtime 
fsync: up and running.
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (2).
15:33:51 (INFO) Launching an executable… 
15:33:51 (INFO) Command: easyterm.py -d -p "#00ffff #2b2d2e" -c 'bash -c '"'"'/home/johndayo/.var/app/com.usebottles.bottles/data/bottles/runners/caffe-8.21/bin/wine64 '"'"'"'"'"'"'"'"'/home/userhere/.var/app/com.usebottles.bottles/data/bottles/bottles/gamtst/drive_c/program pr & graph 1.01 English/ppg.exe'"'"'"'"'"'"'"'"''"'"'' 
Gtk-Message: 15:33:51.569: Failed to load module "xapp-gtk3-module"

(easyterm.py:1514): VTE-WARNING **: 15:33:51.657: (../src/vtepty.cc:810):void vte_pty_spawn_with_fds_async(VtePty*, const char*, const char* const*, const char* const*, const int*, int, const int*, int, GSpawnFlags, GSpawnChildSetupFunc, gpointer, GDestroyNotify, int, GCancellable*, GAsyncReadyCallback, gpointer): runtime check failed: ((spawn_flags & ignored_spawn_flags()) == 0)

(bottles:2): Gtk-WARNING **: 15:35:25.701: Failed to set text 'program pr & graph!' from markup due to error parsing markup: Error on line 1: Entity did not end with a semicolon; most likely you used an ampersand character without intending to start an entity — escape ampersand as &amp;
```

**Comment by Qronikarz** [comment]
I have more context for this issue and can share some stuff now after investigation.

The program was using an ancient chromium with ancient node.js
It's not quite exactly the same error since that program had (EINVAL errno -4071), but it's close enough and hopefully it can be reproduced by others.

https://nodejs.org/en/download
![node](https://github.com/user-attachments/assets/327bc928-1909-460d-93f0-cdfc14d2c062)
I chose the zip version so it must also be added to the program list manually just in case.

Also another point to add is that I found a way to disable `EasyAntiCheat runtime and BattlEye runtime` in bottle.yml, but it didn't change anything other than those two runtimes being disabled.

### To Reproduce

1. Download node-v6.17.1-win-x64.zip
2. Extract Node folder to a bottle of your choosing
3. Run Bottles using terminal
4. Add the node.exe to your bottle's program list
5. Launch node entry from program list and observe the errors in terminal and the program closing itself automatically
6. Launch node entry from program list using the "launch with terminal" button and observe no errors in the terminal

### Package

Flatpak from Flathub

### Distribution

Linux Mint 22.1

### Debugging Information

```shell
Official Package: true
Version: '51.18'
DE/WM: cinnamon
Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.8.0-51-generic
Disk:
    Total: 4130897920
    Free: 4130725888
RAM:
    MemTotal: 7.7GiB
    MemAvailable: 4.9GiB
Bottles_envs: null

```


### Troubleshooting Logs

```shell
20:50:15 (INFO) Launching with URI: None 
20:50:15 (INFO) [Activate] request received. 
20:50:15 (INFO) Bottles Started! 
20:50:15 (WARNING) Connection status: offline … 
20:50:15 (WARNING) Connection status: offline … 
20:50:15 (INFO) Performing Bottles checks… 
20:50:15 (INFO) Dxvks found:
	 - dxvk-2.5.2
 
20:50:15 (INFO) Vkd3ds found:
	 - vkd3d-proton-2.14
 
20:50:15 (INFO) Nvapis found:
	 - dxvk-nvapi-v0.8.0
	 - dxvk-nvapi-v0.7.1
 
20:50:15 (INFO) Latencyflexs found:
	 - latencyflex-v0.1.1
 
20:50:15 (INFO) Runners found:
	 - soda-9.0-1
	 - kron4ek-wine-10.0-rc2-staging-tkg-amd64
	 - sys-wine-9.0
 
20:50:15 (WARNING) Connection status: offline … 
20:50:15 (WARNING) Connection status: offline … 
20:50:15 (WARNING) Connection status: offline … 
20:50:15 (INFO) No dependencies found! 
20:50:15 (INFO) Bottles found:
	 - tts
	 - uninst
 
20:50:15 (INFO) No components found. 
20:50:15 (INFO) No installers found! 
20:50:24 (INFO) Setting Key sync=fsync for bottle uninst… 
20:50:24 (INFO) There is no running wineserver. 
20:50:27 (INFO) Launching an executable… 
20:50:27 (WARNING) Bottles runtime was requested but not found 
fsync: up and running.
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (2).
00d8:err:winebth:bluez_dbus_loop Error getting object list from BlueZ: 'org.freedesktop.DBus.Error.ServiceUnknown': 'org.freedesktop.DBus.Error.ServiceUnknown'
net.js:145
    this._handle.open(options.fd);
                 ^

Error: EINVAL: invalid argument, uv_pipe_open
    at Error (native)
    at new Socket (net.js:145:18)
    at createWritableStdioStream (internal/process/stdio.js:156:16)
    at process.getStdout [as stdout] (internal/process/stdio.js:10:14)
    at console.js:139:37
    at NativeModule.compile (bootstrap_node.js:495:7)
    at NativeModule.require (bootstrap_node.js:438:18)
    at repl.js:34:35
    at NativeModule.compile (bootstrap_node.js:495:7)
    at NativeModule.require (bootstrap_node.js:438:18)
0x5b2ea973c090:1: Hook table
0x5b2ea9773b20:1: Thread id=0128 unix pid=73 unix tid=143 state=1
0x5b2ea97655a0:1: Clipboard open_thread=(nil) open_win=00000000 owner=00000000 viewer=00000000 seq=11
0x5b2ea975b4e0:1: window 0x5b2ea975b4e0 handle 10028
0x5b2ea973c630:1: window 0x5b2ea973c630 handle 10020
0x5b2ea953f560:1: Desktop flags=0 winstation=0x5b2ea9757df0 top_win=0x5b2ea973c630 hooks=0x5b2ea973c090
0x5b2ea9757df0:1: [\\Sessions\\1\\Windows\\WindowStations\\WinSta0] Winstation flags=1 clipboard=0x5b2ea97655a0 atoms=(nil)
0x5b2ea94e9be0:1: Token id=0.1001 primary=1 impersonation level=-1
0x5b2ea94e99a0:1: Process id=0020 handles=(nil)
0x5b2ea8a5e840:1: [\\Sessions\\1\\Windows\\WindowStations] Directory
0x5b2ea8a5e710:1: [\\Sessions\\1\\Windows] Directory
0x5b2ea8a5e1b0:1: [\\Sessions\\1] Directory
0x5b2ea8a5d600:1: [\\Sessions] Directory
0x5b2ea8a5c8a0:1: Directory
20:50:42 (INFO) Launching an executable… 
20:50:42 (INFO) Command: easyterm.py -d -p "#00ffff #2b2d2e" -c 'bash -c '"'"'/home/usernamehere/.var/app/com.usebottles.bottles/data/bottles/runners/kron4ek-wine-10.0-rc2-staging-tkg-amd64/bin/wine64 /home/usernamehere/.var/app/com.usebottles.bottles/data/bottles/bottles/uninst/drive_c/node-v6.17.1-win-x64/node.exe'"'"'' 
Gtk-Message: 20:50:43.051: Failed to load module "xapp-gtk3-module"

(easyterm.py:170): VTE-WARNING **: 20:50:43.147: (../src/vtepty.cc:810):void vte_pty_spawn_with_fds_async(VtePty*, const char*, const char* const*, const char* const*, const int*, int, const int*, int, GSpawnFlags, GSpawnChildSetupFunc, gpointer, GDestroyNotify, int, GCancellable*, GAsyncReadyCallback, gpointer): runtime check failed: ((spawn_flags & ignored_spawn_flags()) == 0)

```

**Comment by Qronikarz** [comment]
v60 update.
Decided to recheck my issue, because I saw in the changelog that it uses WineBridge to make running programs more compatible or whatever and something did change (but for worse)

If you enable WineBridge the program doesn't work in both methods:

```
14:55:24 (INFO) Launching an executable… 
14:55:24 (WARNING) Playtime tracking disabled; start_session is a no-op 
14:55:24 (INFO) Wine Bridge is available. 
14:55:24 (INFO) Using Wine Bridge -- run_exe 
14:55:24 (INFO) Executing command: /home/usernamehere/.var/app/com.usebottles.bottles/data/bottles/runners/kron4ek-wine-10.19-staging-tkg-amd64/bin/wine /home/usernamehere/.var/app/com.usebottles.bottles/data/bottles/winebridge/WineBridge.exe runExe "C:\pr\node-v6.17.1-win-x64\node.exe" 
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (2).
00c0:err:hid:udev_bus_init UDEV monitor creation failed
net.js:145
    this._handle.open(options.fd);
                 ^

Error: EINVAL: invalid argument, uv_pipe_open
    at Error (native)
    at new Socket (net.js:145:18)
    at createWritableStdioStream (internal/process/stdio.js:156:16)
    at process.getStdout [as stdout] (internal/process/stdio.js:10:14)
    at console.js:139:37
    at NativeModule.compile (bootstrap_node.js:495:7)
    at NativeModule.require (bootstrap_node.js:438:18)
    at repl.js:34:35
    at NativeModule.compile (bootstrap_node.js:495:7)
    at NativeModule.require (bootstrap_node.js:438:18)
14:55:33 (INFO) Launching an executable… 
14:55:33 (WARNING) Playtime tracking disabled; start_session is a no-op 
14:55:33 (INFO) Wine Bridge is available. 
14:55:33 (INFO) Using Wine Bridge -- run_exe 
14:55:33 (INFO) Executing command: /home/usernamehere/.var/app/com.usebottles.bottles/data/bottles/runners/kron4ek-wine-10.19-staging-tkg-amd64/bin/wine /home/usernamehere/.var/app/com.usebottles.bottles/data/bottles/winebridge/WineBridge.exe runExe "C:\pr\node-v6.17.1-win-x64\node.exe" 
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (2).
00c0:err:hid:udev_bus_init UDEV monitor creation failed
net.js:145
    this._handle.open(options.fd);
                 ^

Error: EINVAL: invalid argument, uv_pipe_open
    at Error (native)
    at new Socket (net.js:145:18)
    at createWritableStdioStream (internal/process/stdio.js:156:16)
    at process.getStdout [as stdout] (internal/process/stdio.js:10:14)
    at console.js:139:37
    at NativeModule.compile (bootstrap_node.js:495:7)
    at NativeModule.require (bootstrap_node.js:438:18)
    at repl.js:34:35
    at NativeModule.compile (bootstrap_node.js:495:7)
    at NativeModule.require (bootstrap_node.js:438:18)
```

First is the normal play button and second is launch in terminal.

**Comment by DDzwiedziu** [comment]
I can confirm at least that running from a terminal, that has network access results in Bottles running inn offline mode.

**Comment by Qronikarz** [comment]
I feel like this commit doesn't warrant closing this issue since the main post is not about WineBridge, but I'll wait for a new Bottles update to test this issue and just repost this topic if the main problem is not solved.
