### ISSUE TITLE
[Bug]: refuses to launch

### ISSUE THREAD

**Issue by scarf005** [bottlesdevs/Bottles#3356]
### Describe the bug

When running on flatpak, it will fail to run. same as #3216 but it was closed without fixes.

### To Reproduce

1. install bottles on flathub
2. launch bottles

### Package

Flatpak from Flathub

### Distribution

Ubuntu 23.10

### Debugging Information

```shell
flatpak run --command=bottles-cli com.usebottles.bottles info health-check
Traceback (most recent call last):
  File "/app/bin/bottles-cli", line 46, in <module>
    from bottles.backend.managers.manager import Manager
  File "/app/share/bottles/bottles/backend/managers/manager.py", line 39, in <module>
    from bottles.backend.managers.component import ComponentManager
  File "/app/share/bottles/bottles/backend/managers/component.py", line 25, in <module>
    import pycurl
ImportError: pycurl: libcurl link-time version (8.2.1-DEV) is older than compile-time version (8.5.0-DEV)
```

### Troubleshooting Logs

```shell
Traceback (most recent call last):
  File "/app/bin/bottles", line 45, in <module>
    from bottles.frontend import main
  File "/app/share/bottles/bottles/frontend/main.py", line 36, in <module>
    from bottles.frontend.windows.main_window import MainWindow
  File "/app/share/bottles/bottles/frontend/windows/main_window.py", line 30, in <module>
    from bottles.backend.managers.manager import Manager
  File "/app/share/bottles/bottles/backend/managers/manager.py", line 39, in <module>
    from bottles.backend.managers.component import ComponentManager
  File "/app/share/bottles/bottles/backend/managers/component.py", line 25, in <module>
    import pycurl
ImportError: pycurl: libcurl link-time version (8.2.1-DEV) is older than compile-time version (8.5.0-DEV)
```

### Additional context

flatpak info com.usebottles.bottles            2024년 04월 28일 (일) 오후 09시 11분 50초
Bottles - Run Windows Software

          ID: com.usebottles.bottles
         Ref: app/com.usebottles.bottles/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 51.11
     License: GPL-3.0-only
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 456.4 MB
     Runtime: org.gnome.Platform/x86_64/45
         Sdk: org.gnome.Sdk/x86_64/45

      Commit: 45778204c773b7f489a9a88ca24ef325cea99a0dd1cd8eff24b6201a96c4f724
      Parent: 34fd84393ff5717222995783ae052c4da78ab0e15bfeb9649b1bdf3f72592235
     Subject: Update Bottles to 51.11 (5d801701)
        Date: 2024-02-18 21:57:46 +000

**Comment by dull4h4n** [comment]
Added bottles to flatpak, still opens, but none of the bottled apps open.
