### ISSUE TITLE
[Bug]: run Executable button doesn't run the executable picked, "AttributeError".

### ISSUE THREAD

**Issue by zukigay** [bottlesdevs/Bottles#3372]
### Describe the bug

the bottles "run Executable" button doesn't run the file picked by the file picker, and just does nothing.

### To Reproduce

1.create a bottle
2.press the "run Executable"
3.pick executable
4.watch as it doesn't do anything

### Package

Flatpak from Flathub

### Distribution

arch linux

### Debugging Information

```shell
F: Can't get document portal: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
Official Package: true
Version: '51.11'
DE/WM: null
Display:
    X.org: true
    X.org (port): :1
    Wayland: false
Graphics:
    vendors:
        nvidia: &amp;id002
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
            nvngx_path: /usr/lib/x86_64-linux-gnu/GL/nvidia-550-67/extra/nvidia/wine
        intel: &amp;id001
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.x86_64.json:/usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.i686.json
    prime:
        integrated: *id001
        discrete: *id002
Kernel:
    Type: Linux
    Version: 6.6.31-1-lts
Disk:
    Total: 8199122944
    Free: 8198938624
RAM:
    MemTotal: 15.3GiB
    MemAvailable: 7.0GiB
Bottles_envs: null
```

### Troubleshooting Logs

```shell
zuki ~ > com.usebottles.bottles 
F: Can't get document portal: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
21:15:51 (INFO) Bottles Started! 
21:15:52 (INFO) Performing Bottles checks… 
21:15:52 (INFO) Dxvks found:
	- dxvk-2.3
 
21:15:52 (INFO) Vkd3ds found:
	- vkd3d-proton-2.11.1
 
21:15:52 (INFO) Nvapis found:
	- dxvk-nvapi-v0.6.4
 
21:15:52 (INFO) Latencyflexs found:
	- latencyflex-v0.1.1
 
21:15:52 (INFO) Runners found:
	- soda-8.0-2
	- sys-wine-9.0
 
21:15:52 (INFO) Bottles found:
	- toontown
 
21:15:52 (INFO) Catalog dependencies loaded 
21:15:52 (INFO) Catalog installers loaded 
21:15:52 (INFO) Catalog components loaded 
21:15:53 (INFO) Setting Key sync=fsync for bottle toontown… 
21:15:53 (INFO) There is no running wineserver. 
Traceback (most recent call last):
  File "/app/share/bottles/bottles/frontend/views/bottle_details.py", line 405, in execute
    _('Launching "{0}"…').format(dialog.get_file().get_basename())
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_basename'
```

### Additional context

``F: Can't get document portal: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying`` shows up at the start of all flatpak related logs

**Comment by RLB2310** [comment]
Same here. Arch Linux, Bottles VIA flatpak because AUR bottles wouldn't even start
`Traceback` (most recent call last):
  File "/app/share/bottles/bottles/frontend/views/bottle_details.py", line 405, in execute
    _('Launching "{0}"…').format(dialog.get_file().get_basename())
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_basename'
