### ISSUE TITLE
[Bug]: No way to run .bat files (Can't recognize '<Path to .bat file> None')

### ISSUE THREAD

**Issue by ztx-lyghters** [bottlesdevs/Bottles#3403]
### Describe the bug

Batch files are a common thing which wine handles just fine, but not Bottles, for some reason. 
Running it via "Run Executable" doesn't work, no error or anything. Adding a shortcut and running it results in the same behavior. But opening a console for that shortcut reveals the error - `Can't recognize '<Path to a .bat file> None' as an internal or external command, or batch script.` Notice the word `None` after the path to a file. It is a part of the path to the file and I don't know what it is and why it's there. At first I thought that this is the reason.
However, as you will see in the troubleshooting log, first try to open the batch file doesn't have this "None" at the end of the path. That was an attempt to run batch file via "Run application" method. I then try to run a shortcut I have previously added, which adds this very 'None' thing.

The only way to run a .bat file in Bottles for me currently is to select a bottle and run a "command line", cd to a target directory and run a file from there. This is a very inconvenient method, to say the least.

I'm using a Flatpak version (51.11) of Bottles on Gentoo with i3wm.

### To Reproduce

1. Select a bottle
2. Try running .bat file via "Run executable"
3. Get nothing in return
4. Try adding it via "Add shortcuts" and run it
5. Get nothing in return
6. Check the console for that shortcut. Get `Can't recognize '<Path to .bat file> None' as an internal or external command, or batch script.` error.

### Package

Flatpak from Flathub

### Distribution

Gentoo

### Debugging Information

```shell
$ flatpak run --command=bottles-cli com.usebottles.bottles info health-check

(process:2): GLib-GIO-WARNING **: 00:26:54.003: Can't find module 'dconf' specified
Official Package: true
Version: '51.11'
DE/WM: null
Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/u
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.8.9-gentoo-dist
Disk:
    Total: 16785776640
    Free: 16785612800
RAM:
    MemTotal: 31.3GiB
    MemAvailable: 19.3GiB
Bottles_envs: null
```

### Troubleshooting Logs

```shell
(process:2): GLib-GIO-WARNING **: 00:27:50.485: Can't find module 'dconf' specified
00:27:50 (INFO) Bottles Started!
00:27:52 (INFO) Performing Bottles checks…
00:27:52 (INFO) Dxvks found:
         - dxvk-2.3
         - dxvk-2.3-7-eb80695
         - dxvk-2.3-8-d4c5fc7

00:27:52 (INFO) Vkd3ds found:
         - vkd3d-proton-2.11
         - vkd3d-proton-2.11.1-1-bb3948f
         - vkd3d-proton-2.12-4-0fe5a5a

00:27:52 (INFO) Nvapis found:
         - dxvk-nvapi-v0.6.4
         - dxvk-nvapi-v0.6.4-4-ad2d3f9
         - dxvk-nvapi-v0.7.0

00:27:52 (INFO) Latencyflexs found:
         - latencyflex-v0.1.1
         - latencyflex-v0.1.1-2-3bc9636

00:27:52 (INFO) Runners found:
         - soda-9.0-1
         - soda-8.0-2
         - caffe-9.7
         - caffe-9.2
         - caffe-8.21
         - vaniglia-8.6
         - lutris-ge-lol-p8-12
         - wine-ge-proton8-27-lol
         - wine-ge-proton8-25
         - kron4ek-wine-proton-9.0-1-amd64
         - kron4ek-wine-9.9-staging-tkg-amd64
         - kron4ek-wine-9.9-staging-amd64
         - kron4ek-wine-9.9-amd64
         - kron4ek-wine-9.4-staging-tkg-amd64
         - kron4ek-wine-9.1-staging-tkg-amd64
         - kron4ek-wine-9.0-staging-tkg-amd64
         - kron4ek-wine-8.21-staging-tkg-amd64
         - ge-proton9-5
         - ge-proton9-1
         - ge-proton8-32
         - ge-proton8-25
         - sys-wine-9.0


00:27:52 (ERROR) Config file not exists
Traceback (most recent call last):
  File "/app/share/bottles/bottles/backend/models/config.py", line 183, in load
    raise FileNotFoundError("Config file not exists")
FileNotFoundError: Config file not exists
00:27:52 (ERROR) Config file not exists
Traceback (most recent call last):
  File "/app/share/bottles/bottles/backend/models/config.py", line 183, in load
    raise FileNotFoundError("Config file not exists")
FileNotFoundError: Config file not exists
00:27:52 (INFO) Bottles found:
         - bdo
         - test
         - votv
         - AMS2
         - hl_won

00:27:52 (ERROR) /home/ztx/.local/share/Steam/compatibilitytools.d/GE-Proton7-53 is
not a valid Steam Proton path
00:27:52 (WARNING) A Steam prefix was found, but there is no Proton for it: 13210, skipping…
00:27:52 (ERROR) /home/ztx/.local/share/Steam/compatibilitytools.d/GE-Proton7-41 is
not a valid Steam Proton path
00:27:52 (INFO) Catalog installers loaded
00:27:52 (INFO) Catalog dependencies loaded
00:27:52 (WARNING) A Steam prefix was found, but there is no Proton for it: 212680,
skipping…
00:27:52 (INFO) Catalog components loaded

00:27:52 (ERROR) /home/ztx/.local/share/Steam/compatibilitytools.d/GE-Proton7-19 is
not a valid Steam Proton path
00:27:52 (WARNING) A Steam prefix was found, but there is no Proton for it: 225140,
skipping…
00:27:52 (ERROR) /home/ztx/.local/share/Steam/compatibilitytools.d/GE-Proton7-53 is
not a valid Steam Proton path
00:27:52 (WARNING) A Steam prefix was found, but there is no Proton for it: 858210,
skipping…
00:27:52 (WARNING) A Steam prefix was found, but it is a Proton one: 961940, skipping…
00:27:52 (WARNING) A Steam prefix was found, but it is a Proton one: 858280, skipping…
00:27:53 (WARNING) A Steam prefix was found, but it is a Proton one: 2805730, skipping…
00:27:53 (WARNING) A Steam prefix was found, but there is no Proton for it: 13210, skipping…
00:27:53 (WARNING) A Steam prefix was found, but there is no Proton for it: 212680,
skipping…
00:27:53 (WARNING) A Steam prefix was found, but there is no Proton for it: 225140,
skipping…
00:27:53 (WARNING) A Steam prefix was found, but there is no Proton for it: 858210,
skipping…
00:27:53 (WARNING) A Steam prefix was found, but it is a Proton one: 961940, skipping…
00:27:53 (WARNING) A Steam prefix was found, but it is a Proton one: 858280, skipping…
00:27:53 (WARNING) A Steam prefix was found, but it is a Proton one: 2805730, skipping…
00:28:19 (INFO) Setting Key use_steam_runtime=True for bottle hl_won…
00:28:19 (INFO) Setting Key sync=fsync for bottle hl_won…
00:28:19 (INFO) There is no running wineserver.

(bottles:2): GVFS-WARNING **: 00:28:20.124: The peer-to-peer connection failed: Error when getting information for file “/run/user/1000/gvfsd”: No such file or directory. Falling back to the session bus. Your application is probably missing --filesystem=xdg-run/gvfsd privileges.

(bottles:2): GVFS-WARNING **: 00:28:20.124: The peer-to-peer connection failed: Error when getting information for file “/run/user/1000/gvfsd”: No such file or directory. Falling back to the session bus. Your application is probably missing --filesystem=xdg-run/gvfsd privileges.


(bottles:2): GVFS-WARNING **: 00:28:20.160: The peer-to-peer connection failed: Error when getting information for file “/run/user/1000/gvfsd”: No such file or directory. Falling back to the session bus. Your application is probably missing --filesystem=xdg-run/gvfsd privileges.

(bottles:2): GVFS-WARNING **: 00:28:20.160: The peer-to-peer connection failed: Error when getting information for file “/run/user/1000/gvfsd”: No such file or directory. Falling back to the session bus. Your application is probably missing --filesystem=xdg-run/gvfsd privileges.

(bottles:2): GVFS-WARNING **: 00:28:20.161: The peer-to-peer connection failed: Error when getting information for file “/run/user/1000/gvfsd”: No such file or directory. Falling back to the session bus. Your application is probably missing --filesystem=xdg-run/gvfsd privileges.

(bottles:2): GVFS-WARNING **: 00:28:20.161: The peer-to-peer connection failed: Error when getting information for file “/run/user/1000/gvfsd”: No such file or directory. Falling back to the session bus. Your application is probably missing --filesystem=xdg-run/gvfsd privileges.

(bottles:2): GVFS-WARNING **: 00:28:20.161: The peer-to-peer connection failed: Error when getting information for file “/run/user/1000/gvfsd”: No such file or directory. Falling back to the session bus. Your application is probably missing --filesystem=xdg-run/gvfsd privileges.
00:28:41 (INFO) Launching an executable…
00:28:41 (INFO) Using Wine Command Line -- run_batch
00:28:41 (INFO) Using Steam runtime scout
Can't recognize '/mnt/void/home/ztx/GoldSrc Package 2.4/Half-Life (WON).bat' as an i
nternal or external command, or batch script.
00:28:42 (INFO) Using Wine debug tool -- get_processes
00:28:42 (INFO) Using Steam runtime scout
00:28:42 (INFO) Using Wine debug tool -- get_processes
00:28:42 (INFO) Using Steam runtime scout
00:28:48 (INFO) Using Wine debug tool -- get_processes
00:28:48 (INFO) Using Steam runtime scout
00:28:54 (INFO) Using Wine debug tool -- get_processes
00:28:54 (INFO) Using Steam runtime scout
00:28:59 (INFO) Using Wine debug tool -- get_processes
00:28:59 (INFO) Using Steam runtime scout
Can't recognize '/mnt/void/home/ztx/GoldSrc Package 2.4/Half-Life (WON).bat None' as
 an internal or external command, or batch script.
```

**Comment by s373r** [comment]
I have the exact same problem

**Comment by s373r** [comment]
I can confirm that excluding spaces from the path solves the problem -- I moved the script to `C:\\` and it worked fine

The bug is related to https://github.com/bottlesdevs/Bottles/issues/1357

**Comment by carpetdev** [comment]
Had the same problem. Thanks for the workaround
