### ISSUE TITLE
[Bug]: Snapshot newer as the active state can not be restored

### ISSUE THREAD

**Issue by Borgvall** [bottlesdevs/Bottles#3416]
### Describe the bug

Trying to restore a bottle state, that is newer than the "active" state, fails with "State not found". See the steps to reproduce for details. The log output of a full steps to reproduce is pasted below.

### To Reproduce

1. Create new bottle named 'Test Snapshot'
2. Create a snapshot
3. `touch <bottle_path>/drive_c/TestFile`
4. Create a second snapshot
5. Reset the bottle state to the snapshot created in step 2
6. Check, that <bottle_path>/drive_c/TestFile has been removed, as expected
7. Try to restore the bottle state to the snapshot of step 4. This fails with message "State not found", the TestFile has not been restored.
8. Restart Bottles and the snapshot of step 4 is not shown in the list.

### Package

Flatpak from Flathub

### Distribution

Fedora 40

### Debugging Information

```shell
Official Package: true
Version: '51.11'
DE/WM: sway
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.9.6-200.fc40.x86_64
Disk:
    Total: 8353239040
    Free: 8353075200
RAM:
    MemTotal: 15.6GiB
    MemAvailable: 12.6GiB
Bottles_envs: null
```

### Troubleshooting Logs

```shell
johannes@johannes-pc:~$ flatpak run com.usebottles.bottles
18:31:59 (INFO) Bottles Started! 
18:32:00 (INFO) Performing Bottles checks… 
18:32:00 (INFO) Dxvks found:
	 - dxvk-2.3.1
 
18:32:00 (INFO) Vkd3ds found:
	 - vkd3d-proton-2.12
 
18:32:00 (INFO) Nvapis found:
	 - dxvk-nvapi-v0.7.0
 
18:32:00 (INFO) Latencyflexs found:
	 - latencyflex-v0.1.1
 
18:32:00 (INFO) Runners found:
	 - soda-9.0-1
	 - sys-wine-9.0
 
18:32:00 (INFO) Catalog installers loaded 
18:32:00 (INFO) Catalog components loaded 
18:32:00 (INFO) Catalog dependencies loaded 
18:32:20 (INFO) Generating bottle configuration… 
18:32:20 (INFO) Using Wine Runtime tool -- send_status(-i) 
wineserver: using server-side synchronization.
wine: configuration in L"/home/johannes/.var/app/com.usebottles.bottles/data/bottles/bottles/Test-Snapshot" has been updated.
18:32:26 (INFO) Setting Windows version… 
18:32:26 (INFO) Setting CMD default settings… 
18:32:26 (INFO) Importing bundle to Test Snapshot registry 
18:32:26 (INFO) Using Wine Registry CLI -- import_bundle 
wineserver: using server-side synchronization.
18:32:27 (INFO) Import bundle result: '' 
18:32:27 (INFO) Using Wine Runtime tool -- send_status(-u) 
wineserver: using server-side synchronization.
wine: configuration in L"/home/johannes/.var/app/com.usebottles.bottles/data/bottles/bottles/Test-Snapshot" has been updated.
18:32:32 (INFO) Optimizing environment… 
18:32:32 (INFO) Adding Key: [HKEY_CURRENT_USER\Software\Wine\DllOverrides] with Value: [winemenubuilder.exe] and Data: [] in Test Snapshot registry 
18:32:32 (INFO) Using Wine Registry CLI -- add 
wineserver: using server-side synchronization.
18:32:33 (INFO) reg: Der Vorgang wurde erfolgreich abgeschlossen
	
 
18:32:33 (INFO) Applying environment: [application]… 
18:32:34 (INFO) Installing DXVK… 
18:32:34 (INFO) Importing bundle to Test Snapshot registry 
18:32:34 (INFO) Using Wine Registry CLI -- import_bundle 
wineserver: using server-side synchronization.
18:32:34 (INFO) Import bundle result: '' 
18:32:34 (INFO) Installing VKD3D… 
18:32:34 (INFO) Importing bundle to Test Snapshot registry 
18:32:35 (INFO) Using Wine Registry CLI -- import_bundle 
wineserver: using server-side synchronization.
18:32:36 (INFO) Import bundle result: '' 
18:32:36 (INFO) Installing dependency [arial32] in bottle [Test Snapshot]. 
18:32:39 (INFO) Cabinet arial32_exe extracted successfully 
18:32:39 (INFO) Adding Key: [HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Fonts] with Value: [Arial] and Data: [Arial.TTF] in Test Snapshot registry 
18:32:39 (INFO) Using Wine Registry CLI -- add 
wineserver: using server-side synchronization.
18:32:39 (INFO) reg: Der Vorgang wurde erfolgreich abgeschlossen
	
 
18:32:39 (INFO) Adding Key: [HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Fonts] with Value: [Arial Bold] and Data: [Arialbd.TTF] in Test Snapshot registry 
18:32:40 (INFO) Using Wine Registry CLI -- add 
wineserver: using server-side synchronization.
18:32:41 (INFO) reg: Der Vorgang wurde erfolgreich abgeschlossen
	
 
18:32:41 (INFO) Adding Key: [HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Fonts] with Value: [Arial Italic] and Data: [Ariali.TTF] in Test Snapshot registry 
18:32:41 (INFO) Using Wine Registry CLI -- add 
wineserver: using server-side synchronization.
18:32:42 (INFO) reg: Der Vorgang wurde erfolgreich abgeschlossen
	
 
18:32:42 (INFO) Adding Key: [HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Fonts] with Value: [Arial Bold Italic] and Data: [Arialbi.TTF] in Test Snapshot registry 
18:32:43 (INFO) Using Wine Registry CLI -- add 
wineserver: using server-side synchronization.
18:32:43 (INFO) reg: Der Vorgang wurde erfolgreich abgeschlossen
	
 
18:32:43 (INFO) Setting Key Installed_Dependencies=['arial32'] for bottle Test Snapshot… 
18:32:43 (INFO) Dependency installed: arial32 in Test Snapshot 
18:32:43 (INFO) Installing dependency [times32] in bottle [Test Snapshot]. 
18:32:46 (INFO) Cabinet times32_exe extracted successfully 
18:32:46 (INFO) Adding Key: [HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Fonts] with Value: [Times New Roman] and Data: [Times.TTF] in Test Snapshot registry 
18:32:46 (INFO) Using Wine Registry CLI -- add 
wineserver: using server-side synchronization.
18:32:47 (INFO) reg: Der Vorgang wurde erfolgreich abgeschlossen
	
 
18:32:47 (INFO) Adding Key: [HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Fonts] with Value: [Times New Roman Bold] and Data: [Timesbd.TTF] in Test Snapshot registry 
18:32:48 (INFO) Using Wine Registry CLI -- add 
wineserver: using server-side synchronization.
18:32:49 (INFO) reg: Der Vorgang wurde erfolgreich abgeschlossen
	
 
18:32:49 (INFO) Adding Key: [HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Fonts] with Value: [Times New Roman Italic] and Data: [Timesi.TTF] in Test Snapshot registry 
18:32:49 (INFO) Using Wine Registry CLI -- add 
wineserver: using server-side synchronization.
18:32:50 (INFO) reg: Der Vorgang wurde erfolgreich abgeschlossen
	
 
18:32:50 (INFO) Adding Key: [HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Fonts] with Value: [Times New Roman Bold Italic] and Data: [Timesbi.TTF] in Test Snapshot registry 
18:32:50 (INFO) Using Wine Registry CLI -- add 
wineserver: using server-side synchronization.
18:32:51 (INFO) reg: Der Vorgang wurde erfolgreich abgeschlossen
	
 
18:32:51 (INFO) Setting Key Installed_Dependencies=['arial32', 'times32'] for bottle Test Snapshot… 
18:32:51 (INFO) Dependency installed: times32 in Test Snapshot 
18:32:51 (INFO) Installing dependency [courie32] in bottle [Test Snapshot]. 
18:32:54 (INFO) Cabinet courie32_exe extracted successfully 
18:32:54 (INFO) Adding Key: [HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Fonts] with Value: [Courier New] and Data: [cour.ttf] in Test Snapshot registry 
18:32:54 (INFO) Using Wine Registry CLI -- add 
wineserver: using server-side synchronization.
18:32:55 (INFO) reg: Der Vorgang wurde erfolgreich abgeschlossen
	
 
18:32:55 (INFO) Adding Key: [HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Fonts] with Value: [Courier New Bold Italic] and Data: [courbi.ttf] in Test Snapshot registry 
18:32:56 (INFO) Using Wine Registry CLI -- add 
wineserver: using server-side synchronization.
18:32:56 (INFO) reg: Der Vorgang wurde erfolgreich abgeschlossen
	
 
18:32:56 (INFO) Adding Key: [HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Fonts] with Value: [Courier New Italic] and Data: [couri.ttf] in Test Snapshot registry 
18:32:57 (INFO) Using Wine Registry CLI -- add 
wineserver: using server-side synchronization.
18:32:58 (INFO) reg: Der Vorgang wurde erfolgreich abgeschlossen
	
 
18:32:58 (INFO) Adding Key: [HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Fonts] with Value: [Georgia Bold Italic] and Data: [Georgiaz.TTF] in Test Snapshot registry 
18:32:58 (INFO) Using Wine Registry CLI -- add 
wineserver: using server-side synchronization.
18:32:59 (INFO) reg: Der Vorgang wurde erfolgreich abgeschlossen
	
 
18:32:59 (INFO) Setting Key Installed_Dependencies=['arial32', 'times32', 'courie32'] for bottle Test Snapshot… 
18:32:59 (INFO) Dependency installed: courie32 in Test Snapshot 
18:32:59 (INFO) Installing dependency [mono] in bottle [Test Snapshot]. 
18:32:59 (INFO) Using Wine Uninstaller -- get_uuid 
wineserver: using server-side synchronization.
/home/johannes/.var/app/com.usebottles.bottles/data/bottles/dxvk/dxvk-2.3.1/x32/d3d9.dll -> /home/johannes/.var/app/com.usebottles.bottles/data/bottles/bottles/Test-Snapshot/drive_c/windows/syswow64/d3d9.dll
/home/johannes/.var/app/com.usebottles.bottles/data/bottles/dxvk/dxvk-2.3.1/x32/d3d10core.dll -> /home/johannes/.var/app/com.usebottles.bottles/data/bottles/bottles/Test-Snapshot/drive_c/windows/syswow64/d3d10core.dll
/home/johannes/.var/app/com.usebottles.bottles/data/bottles/dxvk/dxvk-2.3.1/x32/d3d11.dll -> /home/johannes/.var/app/com.usebottles.bottles/data/bottles/bottles/Test-Snapshot/drive_c/windows/syswow64/d3d11.dll
/home/johannes/.var/app/com.usebottles.bottles/data/bottles/dxvk/dxvk-2.3.1/x32/dxgi.dll -> /home/johannes/.var/app/com.usebottles.bottles/data/bottles/bottles/Test-Snapshot/drive_c/windows/syswow64/dxgi.dll
/home/johannes/.var/app/com.usebottles.bottles/data/bottles/dxvk/dxvk-2.3.1/x64/d3d9.dll -> /home/johannes/.var/app/com.usebottles.bottles/data/bottles/bottles/Test-Snapshot/drive_c/windows/system32/d3d9.dll
/home/johannes/.var/app/com.usebottles.bottles/data/bottles/dxvk/dxvk-2.3.1/x64/d3d10core.dll -> /home/johannes/.var/app/com.usebottles.bottles/data/bottles/bottles/Test-Snapshot/drive_c/windows/system32/d3d10core.dll
/home/johannes/.var/app/com.usebottles.bottles/data/bottles/dxvk/dxvk-2.3.1/x64/d3d11.dll -> /home/johannes/.var/app/com.usebottles.bottles/data/bottles/bottles/Test-Snapshot/drive_c/windows/system32/d3d11.dll
/home/johannes/.var/app/com.usebottles.bottles/data/bottles/dxvk/dxvk-2.3.1/x64/dxgi.dll -> /home/johannes/.var/app/com.usebottles.bottles/data/bottles/bottles/Test-Snapshot/drive_c/windows/system32/dxgi.dll
/home/johannes/.var/app/com.usebottles.bottles/data/bottles/vkd3d/vkd3d-proton-2.12/x86/d3d12.dll -> /home/johannes/.var/app/com.usebottles.bottles/data/bottles/bottles/Test-Snapshot/drive_c/windows/syswow64/d3d12.dll
/home/johannes/.var/app/com.usebottles.bottles/data/bottles/vkd3d/vkd3d-proton-2.12/x86/d3d12core.dll -> /home/johannes/.var/app/com.usebottles.bottles/data/bottles/bottles/Test-Snapshot/drive_c/windows/syswow64/d3d12core.dll
/home/johannes/.var/app/com.usebottles.bottles/data/bottles/vkd3d/vkd3d-proton-2.12/x64/d3d12.dll -> /home/johannes/.var/app/com.usebottles.bottles/data/bottles/bottles/Test-Snapshot/drive_c/windows/system32/d3d12.dll
/home/johannes/.var/app/com.usebottles.bottles/data/bottles/vkd3d/vkd3d-proton-2.12/x64/d3d12core.dll -> /home/johannes/.var/app/com.usebottles.bottles/data/bottles/bottles/Test-Snapshot/drive_c/windows/system32/d3d12core.dll
arial32.exe (100%) ━━━━━━━━━━━━━━━━━━━━━━━━━ (541.2KiB/541.2KiB - 949.6KiB)

times32.exe (100%) ━━━━━━━━━━━━━━━━━━━━━━━━━ (646.2KiB/646.2KiB - 789.0KiB)

courie32.exe (100%) ━━━━━━━━━━━━━━━━━━━━━━━━━ (631.2KiB/631.2KiB - 324.7KiB)

wine-mono-9.1.0-x86.msi (78%) ━━━━━━━━━━━━━ (63.0MiB/80.7MiB - 1.2MiB)18:34:05 (INFO) Renaming [wine-mono-9.1.0-x86.msi] to [wine-mono-9.1.0-x86.msi]. 
18:34:06 (INFO) Launching an executable… 
18:34:06 (INFO) Using Wine MSI Installer -- install 
wineserver: using server-side synchronization.
18:34:13 (INFO) Adding Key: [HKEY_CURRENT_USER\Software\Wine\DllOverrides] with Value: [mscoree] and Data: [native,builtin] in Test Snapshot registry 
18:34:13 (INFO) Using Wine Registry CLI -- add 
wineserver: using server-side synchronization.
18:34:14 (INFO) reg: Der Vorgang wurde erfolgreich abgeschlossen
	
 
18:34:14 (INFO) Setting Key Installed_Dependencies=['arial32', 'times32', 'courie32', 'mono'] for bottle Test Snapshot… 
18:34:14 (INFO) Dependency installed: mono in Test Snapshot 
18:34:14 (INFO) Installing dependency [gecko] in bottle [Test Snapshot]. 
18:34:57 (INFO) Renaming [wine_gecko-2.47.4-x86.msi] to [wine_gecko-2.47.4-x86.msi]. 
18:34:57 (INFO) Launching an executable… 
18:34:57 (INFO) Using Wine MSI Installer -- install 
wineserver: using server-side synchronization.
wine-mono-9.1.0-x86.msi (100%) ━━━━━━━━━━━━━━━━ (80.7MiB/80.7MiB - 1.2MiB)

wine_gecko-2.47.4-x86.msi (100%) ━━━━━━━━━━━━━━ (52.6MiB/52.6MiB - 1.2MiB)

wine_gecko-2.47.4-x86_64.msi (44%) ━━━━━ (23.0MiB/51.4MiB - 1.2MiB)18:35:42 (INFO) Renaming [wine_gecko-2.47.4-x86_64.msi] to [wine_gecko-2.47.4-x86_64.msi]. 
18:35:42 (INFO) Launching an executable… 
18:35:42 (INFO) Using Wine MSI Installer -- install 
wineserver: using server-side synchronization.
18:35:45 (INFO) Setting Key Installed_Dependencies=['arial32', 'times32', 'courie32', 'mono', 'gecko'] for bottle Test Snapshot… 
18:35:45 (INFO) Dependency installed: gecko in Test Snapshot 
18:35:45 (INFO) New bottle created: Test Snapshot 
18:35:45 (INFO) Using Wine Runtime tool -- send_status(-u) 
wineserver: using server-side synchronization.
wine: configuration in L"/home/johannes/.var/app/com.usebottles.bottles/data/bottles/bottles/Test-Snapshot" has been updated.
18:35:49 (INFO) Caching template… 
18:35:49 (INFO) Creating new template: 7bbf72b8-9a9e-475e-bb53-dea4be87ed66 
18:35:49 (INFO) Copying files … 
18:35:51 (INFO) New template application created 
18:35:51 (INFO) Bottles found:
	 - Test Snapshot
 

(bottles:2): Gdk-WARNING **: 18:36:00.413: Compositor doesn't support moving popups, relying on remapping
18:36:18 (INFO) Opening the file manager in the path … 
18:37:02 (INFO) Bottles found:
	 - Test Snapshot
 
Traceback (most recent call last):
  File "/app/share/bottles/bottles/frontend/widgets/state.py", line 111, in set_completed
    config = self.manager.local_bottles[self.config.Path]
             ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'Test-Snapshot'
18:37:06 (ERROR) State 1 not found. 
18:37:06 (INFO) Bottles found:
	 - Test Snapshot
 
Traceback (most recent call last):
  File "/app/share/bottles/bottles/frontend/widgets/state.py", line 111, in set_completed
    config = self.manager.local_bottles[self.config.Path]
             ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'Test-Snapshot'
wine_gecko-2.47.4-x86_64.msi (100%) ━━━━━━━━━━━━ (51.4MiB/51.4MiB - 1.2MiB)
```

**Comment by Borgvall** [comment]
Please reopen this issue. The behaviour with the current flathub version 52.1 is exactly the same as described and it *can easily lead to data loss*.

**Comment by Borgvall** [comment]
@mirkobrombin please reopen this issue.
