### ISSUE TITLE
[BUG] After update of snap version, does not work anymore

### ISSUE THREAD

**Issue by hovo1990** [bottlesdevs/Bottles#343]
Please don't fill issue for a Windows executable that doesn't work in Bottles. Our software is a Wine prefix manager. If a Windows application doesn't work, it could be a Wine problem (**Wine is NOT a software developed by Bottles**) or a misconfiguration of the wineprefix (take a look at WineHQ: https://www.winehq.org) or ProtonDB: https://www.protondb.com for more information on the software you are trying to run). 

We will support the installation of Windows software, only through our official installers: https://github.com/bottlesdevs/Bottles/issues/55 (when these are ready).
Please DO NOT open issues for this reason. Issues should be used to report Bugs and request New Features for Bottles.

**Describe the bug**

**Installation**
 - Method: Snap Store
 - Version [e.g. 2021.7.2 (find this in the about dialog)]

**To Reproduce**
1. Open Application
2. Missing created bottles
3. "About bottles" button does not work

**Screenshots**

![image](https://user-images.githubusercontent.com/7003230/124345432-d60d7080-dbe9-11eb-85ee-2f6e4041c6c4.png)

**Desktop (please complete the following information):**
 - OS: Pop OS
 - Version 20.04

**Additional context**

**Comment by mirkobrombin** [comment]
Hi, is this from the stable or edge channel? Check if your bottles are present in the /snap path of your home.

**Comment by hovo1990** [comment]
It is stable, and bottle has dissapeared.

**Comment by mirkobrombin** [comment]
> It is stable, and bottle has dissapeared.

Unlike other packages, bottles files in snap are saved in the snap itself. Could it be that you changed the channel or uninstalled and reinstalled the snap, losing files? Because I can't explain the behavior otherwise.

**Comment by hovo1990** [comment]
I have removed and reinstalled, still the same thing cannot create any bottles. Flatpak version works well.

**Comment by mirkobrombin** [comment]
> I have removed and reinstalled, still the same thing cannot create any bottles. Flatpak version works well.

Can you provide some logs?

**Comment by rubberneck** [comment]
I have the same issue on Ubuntu 20.04 with the 0+git.c76dc63 version. If i can provide anything else let me know.

snap info botttles
```
$ snap info bottles 
name:      bottles
summary:   Easily manage wineprefix using environments
publisher: Mirko Brombin (mirkobrombin)
store-url: https://snapcraft.io/bottles
contact:   send@mirko.pm
license:   GPL-3.0+
description: |
  Bottles allows you to run Windows software and games on Linux in preconfigured environments, in
  just a few clicks. Manage your wine prefixes better with Bottles!
commands:
  - bottles
snap-id:      USZuUjpP84Uz6TGFw8o4W1EwEF4IdeiK
tracking:     latest/stable
refresh-date: today at 13:48 CDT
channels:
  latest/stable:    0+git.c76dc63 2021-07-14 (227) 112MB -
  latest/candidate: ↑                                    
  latest/beta:      ↑                                    
  latest/edge:      0+git.1f7ed53 2021-07-14 (231) 112MB -
installed:          0+git.c76dc63            (227) 112MB -
```

app log
```
$ bottles 
Gtk-Message: 17:49:23.621: Failed to load module "canberra-gtk-module"
Traceback (most recent call last):
  File "/snap/bottles/227/usr/share/bottles/bottles/main.py", line 115, in do_activate
    win = BottlesWindow(application=self,
  File "/snap/bottles/227/usr/share/bottles/bottles/window.py", line 97, in __init__
    self.runner = BottlesRunner(self)
  File "/snap/bottles/227/usr/share/bottles/bottles/runner.py", line 168, in __init__
    self.check_gamemode()
  File "/snap/bottles/227/usr/share/bottles/bottles/runner.py", line 690, in check_gamemode
    status = subprocess.call([
  File "/snap/bottles/227/gnome-platform/usr/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/snap/bottles/227/gnome-platform/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/snap/bottles/227/gnome-platform/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'systemctl'

```

dmesg
```
[691678.057704] audit: type=1400 audit(1626303143.315:1611): apparmor="DENIED" operation="open" profile="snap.bottles.bottles" name="/proc/2488142/mounts" pid=2488142 comm="bottles" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000
[691678.087074] audit: type=1326 audit(1626303143.343:1612): auid=1000 uid=1000 gid=1000 ses=4 subj=snap.bottles.bottles pid=2488142 comm="bottles" exe="/usr/bin/python3.8" sig=0 arch=c000003e syscall=314 compat=0 ip=0x7fb3fda1389d code=0x50000
[691678.094423] audit: type=1326 audit(1626303143.351:1613): auid=1000 uid=1000 gid=1000 ses=4 subj=snap.bottles.bottles pid=2488222 comm="gsettings" exe="/snap/bottles/227/gnome-platform/usr/bin/gsettings" sig=0 arch=c000003e syscall=314 compat=0 ip=0x7f415a88189d code=0x50000
[691678.165920] audit: type=1400 audit(1626303143.423:1614): apparmor="DENIED" operation="exec" profile="snap.bottles.bottles" name="/usr/bin/systemctl" pid=2488226 comm="bottles" requested_mask="x" denied_mask="x" fsuid=1000 ouid=0
[691678.165924] audit: type=1400 audit(1626303143.423:1615): apparmor="DENIED" operation="exec" profile="snap.bottles.bottles" name="/usr/bin/systemctl" pid=2488226 comm="bottles" requested_mask="x" denied_mask="x" fsuid=1000 ouid=0
```

**Comment by mirkobrombin** [comment]
I just made a fix, in the next few hours it will arrive on the snapcraft branch edge. Let me know if it works 👀

**Comment by rubberneck** [comment]
This does seem to start now and I am able to create a bottle. I am unsure if anything works past that.
