### ISSUE TITLE
[Bug]: Flatpak fails to open as of v51.15 due to libadwaita-1.so.0

### ISSUE THREAD

**Issue by Ozymandias42** [bottlesdevs/Bottles#3552]
### Describe the bug

As of v51.15 the Bottles Flatpak fails to open with the following error under NixOS (and presumably other distros with no GNOME installed)

```
** (process:2): WARNING **: 10:32:27.622: Failed to load shared library 'libadwaita-1.so.0' referenced by the typelib: /nix/store/s94fwp43xhzkvw8l8nqslskib99yifzi-gcc-13.3.0-lib/lib/libstdc++.so.6: version `CXXABI_1.3.15' not found (required by /usr/lib/x86_64-linux-gnu/libicui18n.so.75)
/usr/lib/python3.12/site-packages/gi/types.py:217: Warning: cannot derive 'TaskEntry' from non-derivable parent type 'void'
  _gi.type_register(cls, namespace.get('__gtype_name__'))
Traceback (most recent call last):
  File "/app/bin/bottles", line 46, in <module>
    from bottles.frontend import main
  File "/app/share/bottles/bottles/frontend/main.py", line 36, in <module>
    from bottles.frontend.windows.main_window import MainWindow
  File "/app/share/bottles/bottles/frontend/windows/main_window.py", line 37, in <module>
    from bottles.frontend.operation import TaskSyncer
  File "/app/share/bottles/bottles/frontend/operation.py", line 30, in <module>
    class TaskEntry(Adw.ActionRow):
  File "/usr/lib/python3.12/site-packages/gi/types.py", line 226, in __init__
    super(GObjectMeta, cls).__init__(name, bases, dict_)
  File "/usr/lib/python3.12/site-packages/gi/types.py", line 205, in __init__
    cls._type_register(cls.__dict__)
  File "/usr/lib/python3.12/site-packages/gi/types.py", line 217, in _type_register
    _gi.type_register(cls, namespace.get('__gtype_name__'))
RuntimeError: could not create new GType: TaskEntry (subclass of void)
```

Presumably this would happen on other systems without libadwaita-1.so.0 too. 
So likely any system that doesn't run GNOME.

### To Reproduce

1. Open Flatpak via `flatpak run com.usebottles.bottles`
2. Observe it failing to open with the error described above.

### Package

Flatpak from Flathub

### Distribution

NixOS 24.11 Unstable

### Debugging Information

```shell
Official Package: true
Version: '51.15'
DE/WM: plasma
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        intel:
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.6.58
Disk:
    Total: 8287592448
    Free: 8287416320
RAM:
    MemTotal: 15.4GiB
    MemAvailable: 7.5GiB
Bottles_envs: null
```

### Troubleshooting Logs

```shell
** (process:2): WARNING **: 10:32:27.622: Failed to load shared library 'libadwaita-1.so.0' referenced by the typelib: /nix/store/s94fwp43xhzkvw8l8nqslskib99yifzi-gcc-13.3.0-lib/lib/libstdc++.so.6: version `CXXABI_1.3.15' not found (required by /usr/lib/x86_64-linux-gnu/libicui18n.so.75)
/usr/lib/python3.12/site-packages/gi/types.py:217: Warning: cannot derive 'TaskEntry' from non-derivable parent type 'void'
  _gi.type_register(cls, namespace.get('__gtype_name__'))
Traceback (most recent call last):
  File "/app/bin/bottles", line 46, in <module>
    from bottles.frontend import main
  File "/app/share/bottles/bottles/frontend/main.py", line 36, in <module>
    from bottles.frontend.windows.main_window import MainWindow
  File "/app/share/bottles/bottles/frontend/windows/main_window.py", line 37, in <module>
    from bottles.frontend.operation import TaskSyncer
  File "/app/share/bottles/bottles/frontend/operation.py", line 30, in <module>
    class TaskEntry(Adw.ActionRow):
  File "/usr/lib/python3.12/site-packages/gi/types.py", line 226, in __init__
    super(GObjectMeta, cls).__init__(name, bases, dict_)
  File "/usr/lib/python3.12/site-packages/gi/types.py", line 205, in __init__
    cls._type_register(cls.__dict__)
  File "/usr/lib/python3.12/site-packages/gi/types.py", line 217, in _type_register
    _gi.type_register(cls, namespace.get('__gtype_name__'))
RuntimeError: could not create new GType: TaskEntry (subclass of void)
```

### Additional context

Bottles runs just fine on NixOS if installed via the native package. However the native package is version 51.13
That aside it should be more likely to run as flatpak than native package as the flatpak should bundle everything needed to run anyway. Apparently as of v51.15 this is not the case (Bottles did run just fine as flatpak in prior versions), at least in regards to libadwaita-1.so.0

**Comment by Ozymandias42** [comment]
solved. apparently 
having /nix/store as globally shared path produces this issue.
Never had any issue with it before with any of the dozens of other flatpaks but seems like it.

Anyway disabling that share for bottles or removing it globally (it's not a default share anyway) resolves this strange issue.


So if anyone else stumbles upon this with something like this
```nix
  home.file."${config.xdg.dataHome}/flatpak/overrides/global".text = ''
  [Context]
   filesystems=/run/current-system/sw:ro;/nix/store:ro;xdg-config/gtk-3.0:ro;xdg-config/gtk-2.0:ro;xdg-config/gtk-4.0:ro;xdg-config/gtk-2.0/gtkrc:ro;xdg-data/icons:ro;
  '';
  ``` 
  in their home.nix config, copy-pasted from somewhere to fix fonts and themes and not having changed it.
  The first two filesystems shared here aren't really needed. In fact they might be downright dangerous being traversible from inside flatpaks.
