### ISSUE TITLE
[Bug]: commands/open with will not open programs correctly

### ISSUE THREAD

**Issue by rockrevenchy** [bottlesdevs/Bottles#3639]
### Describe the bug

if you try and open an executable via commands or by the option in some DE to "open with" bottles throws an error about the local variable "program" not being associated with a value (and will not open the executable)

if I open bottles and start an executable from within the GUI of the app it works flawlessly, I just cannot for the life of me do this via a command

```shell
rockrevenchy@Yggdrasil-Deb:/media/rockrevenchy/HDD/Personal-Files/Downloads/!~exe$ flatpak run com.usebottles.bottles -b Main /home/rockrevenchy/Desktop/CheckDiskPortable_1.4_Development_Release_1_English.paf.exe 

19:40:07 (INFO) Launching with executable: /home/rockrevenchy/Desktop/CheckDiskPortable_1.4_Development_Release_1_English.paf.exe 
19:40:07 (INFO) Launching with URI: ['/home/rockrevenchy/Desktop/CheckDiskPortable_1.4_Development_Release_1_English.paf.exe'] 
19:40:07 (INFO) Forcing offline mode 
Traceback (most recent call last):
  File "/app/bin/bottles-cli", line 758, in <module>
    cli = CLI()
          ^^^^^
  File "/app/bin/bottles-cli", line 236, in __init__
    self.__process_args()
  File "/app/bin/bottles-cli", line 285, in __process_args
    self.run_program()
  File "/app/bin/bottles-cli", line 699, in run_program
    WineExecutor.run_program(bottle, program)
                                     ^^^^^^^
UnboundLocalError: cannot access local variable 'program' where it is not associated with a value

```

### To Reproduce

use the option to open with bottles from the desktop environment or run
flatpak run com.usebottles.bottles <exe path>
or 
flatpak run com.usebottles.bottles -b <bottle> <exe path>

### Package

Flatpak from Flathub

### Distribution

Debian 12 + KDE

### Debugging Information

```shell
Official Package: true
Version: '51.17'
DE/WM: plasmawayland
Display:
    X.org: true
    X.org (port): :1
    Wayland: true
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: ''
            nvngx_path: null
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.1.0-28-amd64
Disk:
    Total: 16784588800
    Free: 16784416768
RAM:
    MemTotal: 31.3GiB
    MemAvailable: 24.9GiB
Bottles_envs: null
```

### Additional context
Neofetch of my computer
```shell
OS: Debian GNU/Linux 12 (bookworm) x86_64 
Kernel: 6.1.0-28-amd64 
Packages: 2819 (dpkg), 15 (flatpak) 
Shell: bash 5.2.15 
Resolution: 1280x1024 
DE: Plasma 5.27.5 
WM: kwin 
Theme: [Plasma], Breeze [GTK2/3] 
Icons: [Plasma], breeze-dark [GTK2/3] 
Terminal: konsole 
CPU: AMD Ryzen 7 3800X (16) @ 3.900GHz 
GPU: NVIDIA GeForce GTX 1660 Ti 
Memory: 6072MiB / 32014MiB 
"""

```

**Comment by jntesteves** [comment]
Duplicate of #3599, #3601
This was fixed in #3605, but a new release hasn't been made yet.

**Comment by martinotecco** [comment]
@jntesteves Please, provide some info about the next release and if it will have the fix for that 'cli.py' file.
I'm trying building Bottles by myself by following the instructions on the readme (I think you need to revisit them also, 'cause it's a mess *)
I thought: "It should let me clone the repo, I replace the 'cli.py' file with the updated one and then I build it"
But after building it (second method in the readme), if I run
`flatpak run --command=bottles-cli com.usebottles.bottles.Devel run --bottle Apps --executable "/home/<myUsername>/.var/app/com.usebottles.bottles.Devel/data/bottles/bottles/Apps/drive_c/<pathToExe>/<executable.exe>"`
I got this error:
`(process:2): GLib-GIO-ERROR **: <currentDate>: Settings schema 'com.usebottles.bottles.Devel' is not installed`.
What do I have to do to make things work? I can't find any solution online.
Thanks.



*...no instructions on how to download and install 'org.flatpak.Builder' from Flathub (first method), by using Discover with flatpak - I'm on Arch Linux, KDE Plasma (Wayland) - is impossible to find the package 'org.flatpak.Builder', the closest is "Builder" which is a completely different packages, to build GNOME apps. Neither online I've found some info.
I've had to ask ChatGPT about it and it told me that you can't install that way, at least on Arch Linux, you have to install it via pacman like basically all the packages - and you haven't stated it right, you don't mention it in the readme -.
...then if you run the command you suggested there, it gives: `error: app/org.flatpak.Builder/x86_64/master not installed`.
Then I don't remember exactly all the commands I've run because they're quite a lot and it was such a terrible mess, lots of errors, but I've given up trying the first method and managed to "successfully" build it by using the second method ...also there you've missed something:
Where is the "repo"? Should I clone it? I've had to clone it and that's not stated, you stated it only in the first method.
Where should I 'cd' in terminal after doing 'flatpak install bottles.flatpak'? because then you say: "from the root of the repository", but I don't know exactly what repository.)

**Comment by jntesteves** [comment]
@martinotecco The fix is already merged in the main branch of the code, it will be on the next version. Unfortunately, I can't give an estimate of when the next release will happen.

Building the Devel version is just for development, it's not good for users because it will save data to a different place, it doesn't share data with the stable version. As a user, when I want to build pre-release versions of an app I use from Flathub, I usually build the version from the store using `flatpak-builder`. I just replace the git repository line in the [manifest](https://github.com/flathub/com.usebottles.bottles) file to point to my personal repository, where I have applied whatever patches I want. It's a fairly simple process for a developer familiar with Flathub, but it can be a bit too technical for most users.

**Comment by rockrevenchy** [comment]
oh interesting, ill update the flatpak then thx for keeping us in the loop
