### ISSUE TITLE
[Crash report]  raise PatoolError(msg)

### ISSUE THREAD

**Issue by mrjones-plip** [bottlesdevs/Bottles#858]
This crash report was generated by Bottles.

**Details**
* **package**: AppImage
* **version**: 2021.12.14-treviso-3

**Log**
```python3
Command `['/tmp/.mount_Bottlevptpj5//usr/bin/7zr', 'x', '-o/home/USER/.local/share/bottles/temp/firefox_setup_6203_32bit', '--', '/home/USER/.local/share/bottles/temp/firefox_setup_6203_32bit.7z']' returned non-zero exit status -11  File "/tmp/.mount_Bottlevptpj5///usr/local/share/bottles/bottles/utils.py", line 335, in __target
    result = self.task_func(*args, **kwargs)

  File "/tmp/.mount_Bottlevptpj5///usr/local/share/bottles/bottles/backend/manager.py", line 1104, in create_bottle
    self.dependency_manager.install(config, [dep, _dep])

  File "/tmp/.mount_Bottlevptpj5///usr/local/share/bottles/bottles/backend/dependency.py", line 163, in install
    res = self.__perform_steps(config, step)

  File "/tmp/.mount_Bottlevptpj5///usr/local/share/bottles/bottles/backend/dependency.py", line 261, in __perform_steps
    if not self.__step_archive_extract(step):

  File "/tmp/.mount_Bottlevptpj5///usr/local/share/bottles/bottles/backend/dependency.py", line 553, in __step_archive_extract
    patoolib.extract_archive(

  File "/tmp/.mount_Bottlevptpj5/usr/lib/python3/dist-packages/patoolib/__init__.py", line 684, in extract_archive
    return _extract_archive(archive, verbosity=verbosity, interactive=interactive, outdir=outdir, program=program)

  File "/tmp/.mount_Bottlevptpj5/usr/lib/python3/dist-packages/patoolib/__init__.py", line 484, in _extract_archive
    run_archive_cmdlist(cmdlist, verbosity=verbosity)

  File "/tmp/.mount_Bottlevptpj5/usr/lib/python3/dist-packages/patoolib/__init__.py", line 421, in run_archive_cmdlist
    return util.run_checked(cmdlist, verbosity=verbosity, **runkwargs)

  File "/tmp/.mount_Bottlevptpj5/usr/lib/python3/dist-packages/patoolib/util.py", line 227, in run_checked
    raise PatoolError(msg)

```

**Comment by mirkobrombin** [comment]
Apparently Patool did not give any useful details, it seems a "momentary" error of the library, can you try again?

**Comment by mrjones-plip** [comment]
Yeah - trying again with the exact same bottle seems to have worked. This was my first ever bottle. Subsequent bottles did not have this error. If this report isn't helpful, feel free to close the ticket!

**Comment by mrjones-plip** [comment]
Oh - no - I spoke too soon! It's the gaming profile that seems to be problematic. I just creaed another and it errored out. Here's the output the command line:

```python3
(12:08:33) WARNING File [firefox_setup_6203_32bit.7z] already exists in temp, skipping. 
patool: Extracting /home/mrjones/.local/share/bottles/temp/firefox_setup_6203_32bit.7z ...
patool: running /tmp/.mount_BottlefOIw1f//usr/bin/7zr x -o/home/mrjones/.local/share/bottles/temp/firefox_setup_6203_32bit -- /home/mrjones/.local/share/bottles/temp/firefox_setup_6203_32bit.7z
(12:08:33) ERROR Error while running async job: <bound method Manager.create_bottle of <bottles.backend.manager.Manager object at 0x7ff5d7a14a00>>
Exception: Command `['/tmp/.mount_BottlefOIw1f//usr/bin/7zr', 'x', '-o/home/mrjones/.local/share/bottles/temp/firefox_setup_6203_32bit', '--', '/home/mrjones/.local/share/bottles/temp/firefox_setup_6203_32bit.7z']' returned non-zero exit status -11 
  File "/tmp/.mount_BottlefOIw1f///usr/local/share/bottles/bottles/utils.py", line 335, in __target
    result = self.task_func(*args, **kwargs)
  File "/tmp/.mount_BottlefOIw1f///usr/local/share/bottles/bottles/backend/manager.py", line 1104, in create_bottle
    self.dependency_manager.install(config, [dep, _dep])
  File "/tmp/.mount_BottlefOIw1f///usr/local/share/bottles/bottles/backend/dependency.py", line 163, in install
    res = self.__perform_steps(config, step)
  File "/tmp/.mount_BottlefOIw1f///usr/local/share/bottles/bottles/backend/dependency.py", line 261, in __perform_steps
    if not self.__step_archive_extract(step):
  File "/tmp/.mount_BottlefOIw1f///usr/local/share/bottles/bottles/backend/dependency.py", line 553, in __step_archive_extract
    patoolib.extract_archive(
  File "/tmp/.mount_BottlefOIw1f/usr/lib/python3/dist-packages/patoolib/__init__.py", line 684, in extract_archive
    return _extract_archive(archive, verbosity=verbosity, interactive=interactive, outdir=outdir, program=program)
  File "/tmp/.mount_BottlefOIw1f/usr/lib/python3/dist-packages/patoolib/__init__.py", line 484, in _extract_archive
    run_archive_cmdlist(cmdlist, verbosity=verbosity)
  File "/tmp/.mount_BottlefOIw1f/usr/lib/python3/dist-packages/patoolib/__init__.py", line 421, in run_archive_cmdlist
    return util.run_checked(cmdlist, verbosity=verbosity, **runkwargs)
  File "/tmp/.mount_BottlefOIw1f/usr/lib/python3/dist-packages/patoolib/util.py", line 227, in run_checked
    raise PatoolError(msg)
Traceback (most recent call last):
  File "/tmp/.mount_BottlefOIw1f///usr/local/share/bottles/bottles/views/new.py", line 238, in finish
    self.new_bottle_config = result.data.get("config")
AttributeError: 'NoneType' object has no attribute 'data'

```

**Comment by mrjones-plip** [comment]
And then here's the crash report the next time I re-launch bottles:

```python3
(12:08:33) WARNING File [firefox_setup_6203_32bit.7z] already exists in temp, skipping. 
patool: Extracting /home/mrjones/.local/share/bottles/temp/firefox_setup_6203_32bit.7z ...
patool: running /tmp/.mount_BottlefOIw1f//usr/bin/7zr x -o/home/mrjones/.local/share/bottles/temp/firefox_setup_6203_32bit -- /home/mrjones/.local/share/bottles/temp/firefox_setup_6203_32bit.7z
(12:08:33) ERROR Error while running async job: <bound method Manager.create_bottle of <bottles.backend.manager.Manager object at 0x7ff5d7a14a00>>
Exception: Command `['/tmp/.mount_BottlefOIw1f//usr/bin/7zr', 'x', '-o/home/mrjones/.local/share/bottles/temp/firefox_setup_6203_32bit', '--', '/home/mrjones/.local/share/bottles/temp/firefox_setup_6203_32bit.7z']' returned non-zero exit status -11 
  File "/tmp/.mount_BottlefOIw1f///usr/local/share/bottles/bottles/utils.py", line 335, in __target
    result = self.task_func(*args, **kwargs)
  File "/tmp/.mount_BottlefOIw1f///usr/local/share/bottles/bottles/backend/manager.py", line 1104, in create_bottle
    self.dependency_manager.install(config, [dep, _dep])
  File "/tmp/.mount_BottlefOIw1f///usr/local/share/bottles/bottles/backend/dependency.py", line 163, in install
    res = self.__perform_steps(config, step)
  File "/tmp/.mount_BottlefOIw1f///usr/local/share/bottles/bottles/backend/dependency.py", line 261, in __perform_steps
    if not self.__step_archive_extract(step):
  File "/tmp/.mount_BottlefOIw1f///usr/local/share/bottles/bottles/backend/dependency.py", line 553, in __step_archive_extract
    patoolib.extract_archive(
  File "/tmp/.mount_BottlefOIw1f/usr/lib/python3/dist-packages/patoolib/__init__.py", line 684, in extract_archive
    return _extract_archive(archive, verbosity=verbosity, interactive=interactive, outdir=outdir, program=program)
  File "/tmp/.mount_BottlefOIw1f/usr/lib/python3/dist-packages/patoolib/__init__.py", line 484, in _extract_archive
    run_archive_cmdlist(cmdlist, verbosity=verbosity)
  File "/tmp/.mount_BottlefOIw1f/usr/lib/python3/dist-packages/patoolib/__init__.py", line 421, in run_archive_cmdlist
    return util.run_checked(cmdlist, verbosity=verbosity, **runkwargs)
  File "/tmp/.mount_BottlefOIw1f/usr/lib/python3/dist-packages/patoolib/util.py", line 227, in run_checked
    raise PatoolError(msg)
Traceback (most recent call last):
  File "/tmp/.mount_BottlefOIw1f///usr/local/share/bottles/bottles/views/new.py", line 238, in finish
    self.new_bottle_config = result.data.get("config")
AttributeError: 'NoneType' object has no attribute 'data'
```

**Comment by mirkobrombin** [comment]
> Oh - no - I spoke too soon! It's the gaming profile that seems to be problematic. I just creaed another and it errored out. Here's the output the command line:
> 
> ```python
> (12:08:33) WARNING File [firefox_setup_6203_32bit.7z] already exists in temp, skipping. 
> patool: Extracting /home/mrjones/.local/share/bottles/temp/firefox_setup_6203_32bit.7z ...
> patool: running /tmp/.mount_BottlefOIw1f//usr/bin/7zr x -o/home/mrjones/.local/share/bottles/temp/firefox_setup_6203_32bit -- /home/mrjones/.local/share/bottles/temp/firefox_setup_6203_32bit.7z
> (12:08:33) ERROR Error while running async job: <bound method Manager.create_bottle of <bottles.backend.manager.Manager object at 0x7ff5d7a14a00>>
> Exception: Command `['/tmp/.mount_BottlefOIw1f//usr/bin/7zr', 'x', '-o/home/mrjones/.local/share/bottles/temp/firefox_setup_6203_32bit', '--', '/home/mrjones/.local/share/bottles/temp/firefox_setup_6203_32bit.7z']' returned non-zero exit status -11 
>   File "/tmp/.mount_BottlefOIw1f///usr/local/share/bottles/bottles/utils.py", line 335, in __target
>     result = self.task_func(*args, **kwargs)
>   File "/tmp/.mount_BottlefOIw1f///usr/local/share/bottles/bottles/backend/manager.py", line 1104, in create_bottle
>     self.dependency_manager.install(config, [dep, _dep])
>   File "/tmp/.mount_BottlefOIw1f///usr/local/share/bottles/bottles/backend/dependency.py", line 163, in install
>     res = self.__perform_steps(config, step)
>   File "/tmp/.mount_BottlefOIw1f///usr/local/share/bottles/bottles/backend/dependency.py", line 261, in __perform_steps
>     if not self.__step_archive_extract(step):
>   File "/tmp/.mount_BottlefOIw1f///usr/local/share/bottles/bottles/backend/dependency.py", line 553, in __step_archive_extract
>     patoolib.extract_archive(
>   File "/tmp/.mount_BottlefOIw1f/usr/lib/python3/dist-packages/patoolib/__init__.py", line 684, in extract_archive
>     return _extract_archive(archive, verbosity=verbosity, interactive=interactive, outdir=outdir, program=program)
>   File "/tmp/.mount_BottlefOIw1f/usr/lib/python3/dist-packages/patoolib/__init__.py", line 484, in _extract_archive
>     run_archive_cmdlist(cmdlist, verbosity=verbosity)
>   File "/tmp/.mount_BottlefOIw1f/usr/lib/python3/dist-packages/patoolib/__init__.py", line 421, in run_archive_cmdlist
>     return util.run_checked(cmdlist, verbosity=verbosity, **runkwargs)
>   File "/tmp/.mount_BottlefOIw1f/usr/lib/python3/dist-packages/patoolib/util.py", line 227, in run_checked
>     raise PatoolError(msg)
> Traceback (most recent call last):
>   File "/tmp/.mount_BottlefOIw1f///usr/local/share/bottles/bottles/views/new.py", line 238, in finish
>     self.new_bottle_config = result.data.get("config")
> AttributeError: 'NoneType' object has no attribute 'data'
> ```

The weird thing is that I've already fixed this :D Can you try to update to 2021.12.14-treviso-4 ?

**Comment by mrjones-plip** [comment]
Oh, interesting! I'm on  `Bottles-2021.12.14-treviso-3-x86_64.AppImage` which I think is the latest appimage version.

**Comment by mirkobrombin** [comment]
Ya but I think also the -4 also doesn't have this fix. Next release day is 2021.12.28. Is this bug reproducible with every new gaming bottle?

**Comment by mrjones-plip** [comment]
yup, reproducible - just created my third gaming bottle with the same error.

**Comment by mirkobrombin** [comment]
I got it, the appimage is missing one dependency from p7zip, I’m planning a fix. Thanks for reporting

**Comment by mrjones-plip** [comment]
Happy to help - good luck!

**Comment by mirkobrombin** [comment]
fix #858 doesn't fix

**Comment by mirkobrombin** [comment]
I'm not able to reproduce this anymore, tested on Arch, Ubuntu 21.04 and Silverblue

**Comment by mirkobrombin** [comment]
Not able to replicate this. Feel free to add more details and re-open the issue.
