### ISSUE TITLE
Webkit dependency in .deb

### ISSUE THREAD

**Issue by spcwingo** [bottlesdevs/Bottles#887]
Traceback (most recent call last):
  File "/usr/bin/bottles", line 56, in <module>
    from bottles import main
  File "/usr/share/bottles/bottles/main.py", line 28, in <module>
    gi.require_version('WebKit2', '4.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace WebKit2 not available

This is on Debian Bookworm with libwebkit2gtk-4.0-37 installed so I'm assuming it's not finding it for some reason. Maybe I'm reading the error message incorrectly. I have no idea.

**Comment by mirkobrombin** [comment]
Try installing ‘ gir1.2-webkit2-4.0’

**Comment by spcwingo** [comment]
That was the missing dependency. Thanks, mirkobrombin!
