### ISSUE TITLE
Health Check Button Causes Traceback Error

### ISSUE THREAD

**Issue by RippedCornet391** [bottlesdevs/Bottles#923]
Summary:

When clicking the "Health Check" button after opening the app, the button does not respond and the console shows a traceback error that says "Key Error: 'VERSION_ID'

Steps to Reproduce:

1. Open Bottles
2. Click the Health Check button

Expected Result:

The health check would be performed.

Actual Result:

The button does not function properly, and the console displays a traceback error.

PC Specs:

I am using Manjaro Linux. App obtained via the AUR.

Error Log:

`(12:19:52) INFO Bottles Started! 
Traceback (most recent call last):
  File "/usr/share/bottles/bottles/window.py", line 287, in show_health_view
    ht = HealthChecker().get_results(plain=True)
  File "/usr/share/bottles/bottles/backend/health.py", line 36, in __init__
    self.check_system_info()
  File "/usr/share/bottles/bottles/backend/health.py", line 132, in check_system_info
    distro = self.__get_distro()
  File "/usr/share/bottles/bottles/backend/health.py", line 81, in __get_distro
    "version": _platform["VERSION_ID"]
KeyError: 'VERSION_ID'`

**Comment by RippedCornet391** [comment]
For some reason, when I hit the "Create Issue" button, I wasn't given the regular Bug Report template. For that reason, I used a generic one.
