### ISSUE TITLE
[BUG] 'str' object has no attribute 'year' creating Bottle from Flatpak

### ISSUE THREAD

**Issue by walthaas** [bottlesdevs/Bottles#925]
**Creating a new bottle crashed with the following crash report on next startup:**

[Errno 2] No such file or directory: '/home/USER/.var/app/com.usebottles.bottles/data/bottles/temp/d3dx9_25'  File "/app/share/bottles/bottles/utils.py", line 335, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/backend/manager.py", line 1143, in create_bottle
    self.dependency_manager.install(config, [dep, _dep])

  File "/app/share/bottles/bottles/backend/dependency.py", line 164, in install
    res = self.__perform_steps(config, step)

  File "/app/share/bottles/bottles/backend/dependency.py", line 257, in __perform_steps
    if not self.__step_get_from_cab(config=config, step=step):

  File "/app/share/bottles/bottles/backend/dependency.py", line 522, in __step_get_from_cab
    shutil.copy(

  File "/usr/lib/python3.9/shutil.py", line 427, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)

  File "/usr/lib/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc:

**When Bottles was stared from the command line the output was:**

 Gtk-Message: 20:29:05.763: Failed to load module "xapp-gtk3-module"
(20:29:06) INFO Performing Bottles checks... 
(20:29:06) INFO DXVKs found:
	 - dxvk-1.9.3
 
(20:29:06) INFO VKD3Ds found:
	 - vkd3d-proton-2.5
 
(20:29:06) INFO NVAPIs found:
	 - dxvk-nvapi-v0.5.1
 
(20:29:06) INFO Runners found:
	 - lutris-ge-6.21-1
	 - Proton-6.21-GE-2
	 - vaniglia-6.23
	 - caffe-6.23
	 - lutris-6.21-6
 
Traceback (most recent call last):
  File "/app/share/bottles/bottles/main.py", line 168, in do_command_line
    self.do_activate()
  File "/app/share/bottles/bottles/main.py", line 233, in do_activate
    win = MainWindow(
  File "/app/share/bottles/bottles/window.py", line 172, in __init__
    self.__on_start()
  File "/app/share/bottles/bottles/window.py", line 242, in __on_start
    self.check_notifications()
  File "/app/share/bottles/bottles/window.py", line 338, in check_notifications
    messages = NotificationsManager().messages
  File "/app/share/bottles/bottles/backend/notifications.py", line 19, in __init__
    self.__get_messages()
  File "/app/share/bottles/bottles/backend/notifications.py", line 35, in __get_messages
    _date =  datetime(_date.year, _date.month, _date.day)
AttributeError: 'str' object has no attribute 'year'

**Installation**
Flatpak from Flathub
2021.12.28-treviso

**To Reproduce**
Start Bottles.
Click Create a new Bottle
Select Gaming and provide a name

**Expected behavior**
A new bottle suitable for a game

**Desktop**
 - Fedora
 - 35
 - Xorg

**Comment by mirkobrombin** [comment]
Dependencies repository is no more compatible with old Bottles release. Please upgrade to 2022.1.14-Trento.
