### ISSUE TITLE
[BUG] Can't manually add an executable to Programs

### ISSUE THREAD

**Issue by Flrian** [bottlesdevs/Bottles#976]
**Describe the bug**
Nothing happens when trying to add an exe to the programs list in a bottle

**Installation**
 - Method: Meson build
 - Version https://github.com/bottlesdevs/Bottles/commit/7b0ff979dc890b32e137ce1975d672f1b7607734

**To Reproduce**
1. Go to a bottle
2. Click on the programs tab
3. Try to "Add a custom executable path"
4. Nothing happens

**Expected behavior**
The exe should be added to the list of programs

Here is what I get when running bottles from the commandline:
```
❯ bottles
/usr/share/bottles/bottles/dialogs/generic.py:18: PyGIWarning: GtkSource was imported without specifying a version first. Use gi.require_version('GtkSource', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, GtkSource, Gdk, Handy, Pango, WebKit2
(17:44:52) INFO Performing Bottles checks... 
(17:44:52) INFO DXVKs found:
         - dxvk-1.9.2
         - dxvk-1.9.3
 
(17:44:52) INFO VKD3Ds found:
         - vkd3d-v2.4
 
(17:44:52) INFO NVAPIs found:
         - dxvk-nvapi-v0.5.1
 
(17:44:52) INFO Runners found:
         - sys-wine-7.0

         - lutris-ge-6.16-3-lol
         - lutris-ge-7.0rc3-1
 
(17:44:52) INFO Bottles found:
         - games-lol
         - games-wows
         - games-misc
 
(17:44:52) INFO Bottles Started! 
(17:44:53) INFO Setting Key: [pulseaudio_latency] to [True] for bottle: [games-lol]… 
(17:44:53) WARNING Cannot find states.yml file for bottle: [games-lol] 
(17:44:53) INFO Using WINE debug tool 
(17:44:53) INFO Using WINE debug tool 

(bottles:13871): Handy-CRITICAL **: 17:44:53.509: hdy_stackable_box_set_visible_child_name: assertion 'contains_child' failed
esync: up and running.
0034:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (2).
(17:44:54) INFO Using WINE debug tool 
(17:44:54) INFO Using WINE debug tool 
(17:45:10) INFO Setting Key: [LeagueClient.exe] to [{'executable': 'LeagueClient.exe', 'name': 'LeagueClient', 'path': '/home/florian/.local/share/bottles/bottles/games-lol/drive_c/Riot Games/League of Legends/LeagueClient.exe'}] for bottle: [games-lol]… 
Traceback (most recent call last):
  File "/usr/share/bottles/bottles/views/bottle_programs.py", line 89, in add
    self.manager.update_config(
  File "/usr/share/bottles/bottles/backend/manager.py", line 816, in update_config
    config[scope][key] = value
TypeError: list indices must be integers or slices, not str
```

I also get the same/similar error when trying to add a script to the launch option with the new feature added in https://github.com/bottlesdevs/Bottles/commit/216c3b217c9c518960329e6c34562803e9289233.

**Comment by mirkobrombin** [comment]
I'm not able to reproduce this, can you post your bottle.yml

**Comment by mirkobrombin** [comment]
Np, I'll make some tests with old bottles

**Comment by SeanRamey** [comment]
I'm having this issue and I've had this issue since the first time I tried bottles on another PC, I just didn't bother with reporting it and decided to use wine directly instead.
My bottle yml: https://www.toptal.com/developers/hastebin/abehuhusal.yaml

![Screenshot_20220505_120631](https://user-images.githubusercontent.com/3057229/166975910-9c554b2f-02d7-4054-bee0-5da5f2656ae7.png)

**Comment by SeanRamey** [comment]
Ok, so, this issue has something to do with the SPECIFIC game I tried to install and run. The game is Close Combat: Gateway to Caen. It's a GoG released game, which means it installs to C:\GOG Games by default. The reason I know it's an issue with this specific game is that when I tried installing notepad++ as it shows in the bottles demo video, it worked flawlessly. Another issue I noticed is that I can't select the bottle, and "go into it" (can't see the "details and utilities, preferences, dependencies, etc.. screen) after I exit it. However, I can still do this with the notepad++ bottle.

**Comment by SeanRamey** [comment]
Yes, I deleted the bottle for Close Combat from before, and I created a brand new bottle, but this time, I changed the install path from C:\GoG Games\Close Combat... to C:\Program Files\Close Combat...   It worked like a charm and fixed every issue I had. SO, there's definitely something wrong with Bottles with recognizing install paths in the C:\ drive.

**Comment by Flrian** [comment]
@SeanRamey You should probably open a new Issue for that, it doesn't seem to be related to why I originally opened this bug report and you are likely to get it fixed faster that way.
